package main

import (
	"bufio"
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"gopkg.in/yaml.v3"
)

const (
	baseFile   = ".golangci.base.yml"
	outFile    = ".golangci.yml"
	moduleLint = "lint.yml"
	header     = "# Code generated by scripts/gen-golangci from " + baseFile +
		" and internal/modules/*/" + moduleLint + ". DO NOT EDIT.\n"
)

type exclusion struct {
	Path    string   `yaml:"path"`
	Linters []string `yaml:"linters"`
	Text    string   `yaml:"text"`
	Reason  string   `yaml:"reason"`
}

func main() {
	root := "."
	if len(os.Args) > 1 {
		root = os.Args[1]
	}
	if err := generate(root); err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "gen-golangci: %v\n", err)
		os.Exit(1)
	}
}

func generate(root string) error {
	out, err := render(root)
	if err != nil {
		return err
	}
	path := filepath.Join(root, outFile)
	if cur, err := os.ReadFile(path); err == nil && bytes.Equal(cur, out) {
		return nil
	}
	if err := os.WriteFile(path, out, 0o644); err != nil {
		return fmt.Errorf("write config: %w", err)
	}
	return nil
}

func render(root string) ([]byte, error) {
	modPath, err := modulePath(filepath.Join(root, "go.mod"))
	if err != nil {
		return nil, err
	}
	modulesDir := filepath.Join(root, "internal", "modules")
	names, err := moduleNames(modulesDir)
	if err != nil {
		return nil, err
	}
	cfg, err := os.ReadFile(filepath.Join(root, baseFile))
	if err != nil {
		return nil, fmt.Errorf("read config: %w", err)
	}
	var walls, rules strings.Builder
	for _, name := range names {
		writeWall(&walls, modPath+"/internal/modules/", name)
		if err := writeExclusions(&rules, modulesDir, name); err != nil {
			return nil, err
		}
	}
	out := string(cfg)
	for _, region := range []struct{ name, body string }{{"depguard", walls.String()}, {"exclusions", rules.String()}} {
		if out, err = splice(out, region.name, region.body); err != nil {
			return nil, fmt.Errorf("%s: %w", baseFile, err)
		}
	}
	return []byte(header + out), nil
}

func modulePath(goMod string) (string, error) {
	b, err := os.ReadFile(goMod)
	if err != nil {
		return "", fmt.Errorf("read go.mod: %w", err)
	}
	sc := bufio.NewScanner(bytes.NewReader(b))
	for sc.Scan() {
		if path, ok := strings.CutPrefix(strings.TrimSpace(sc.Text()), "module "); ok {
			return strings.Trim(strings.TrimSpace(path), `"`), nil
		}
	}
	return "", fmt.Errorf("%s has no module line", goMod)
}

func moduleNames(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("list modules: %w", err)
	}
	var names []string
	for _, e := range entries {
		if e.IsDir() {
			names = append(names, e.Name())
		}
	}
	slices.Sort(names)
	return names, nil
}

func splice(cfg, region, body string) (string, error) {
	begin, end := "# BEGIN GENERATED "+region, "# END GENERATED "+region
	lines := strings.SplitAfter(cfg, "\n")
	b := slices.IndexFunc(lines, func(l string) bool { return strings.TrimSpace(l) == begin })
	e := slices.IndexFunc(lines, func(l string) bool { return strings.TrimSpace(l) == end })
	if b < 0 || e < b {
		return "", fmt.Errorf("want one %q line followed by one %q line", begin, end)
	}
	indent := lines[b][:len(lines[b])-len(strings.TrimLeft(lines[b], " "))]
	var out strings.Builder
	for _, l := range lines[:b+1] {
		out.WriteString(l)
	}
	for l := range strings.Lines(body) {
		out.WriteString(indent + l)
	}
	for _, l := range lines[e:] {
		out.WriteString(l)
	}
	return out.String(), nil
}

func writeWall(b *strings.Builder, modulesPkg, name string) {
	own := modulesPkg + name
	fmt.Fprintf(b, "module-%s: { list-mode: lax, files: [\"**/internal/modules/%s/**\"], "+
		"allow: [\"%s$\", \"%s/\"], deny: [{ pkg: \"%s\", "+
		"desc: \"modules never import each other; send an event or use a query port\" }] }\n",
		name, name, own, own, modulesPkg)
}

func writeExclusions(b *strings.Builder, modulesDir, name string) error {
	path := filepath.Join(modulesDir, name, moduleLint)
	raw, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("read %s: %w", path, err)
	}
	dec := yaml.NewDecoder(bytes.NewReader(raw))
	dec.KnownFields(true)
	var rules []exclusion
	if err := dec.Decode(&rules); err != nil {
		return fmt.Errorf("%s: %w", path, err)
	}
	own := "^internal/modules/" + name + "/"
	for i, r := range rules {
		if !strings.HasPrefix(r.Path, own) || len(r.Linters) == 0 || r.Reason == "" ||
			strings.Contains(r.Reason, "\n") {
			return fmt.Errorf("%s: rule %d needs a path starting %q, linters and a one-line reason",
				path, i+1, own)
		}
		text := ""
		if r.Text != "" {
			text = ", text: " + quote(r.Text)
		}
		fmt.Fprintf(b, "- { path: %s, linters: [%s]%s } # %s: %s\n",
			quote(r.Path), strings.Join(r.Linters, ", "), text, name, r.Reason)
	}
	return nil
}

func quote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}
