// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: boards.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const boardPage = `-- name: BoardPage :many
SELECT board, range, rank, subject_id, subject_name, subject_handle, subject_picture_url, subject_created_at,
  value_micros, pnl_micros, return_bps, prices_as_of, computed_at, flags
FROM leaderboard_entries
WHERE board = $1 AND range = $2 AND rank > $3
ORDER BY rank
LIMIT $4
`

type BoardPageParams struct {
	Board     string
	Range     string
	AfterRank int32
	RowLimit  int32
}

func (q *Queries) BoardPage(ctx context.Context, arg BoardPageParams) ([]LeaderboardEntry, error) {
	rows, err := q.db.Query(ctx, boardPage,
		arg.Board,
		arg.Range,
		arg.AfterRank,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeaderboardEntry
	for rows.Next() {
		var i LeaderboardEntry
		if err := rows.Scan(
			&i.Board,
			&i.Range,
			&i.Rank,
			&i.SubjectID,
			&i.SubjectName,
			&i.SubjectHandle,
			&i.SubjectPictureUrl,
			&i.SubjectCreatedAt,
			&i.ValueMicros,
			&i.PnlMicros,
			&i.ReturnBps,
			&i.PricesAsOf,
			&i.ComputedAt,
			&i.Flags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const boardRowFor = `-- name: BoardRowFor :one
SELECT board, range, rank, subject_id, subject_name, subject_handle, subject_picture_url, subject_created_at,
  value_micros, pnl_micros, return_bps, prices_as_of, computed_at, flags
FROM leaderboard_entries
WHERE board = $1 AND range = $2 AND subject_id = $3
`

type BoardRowForParams struct {
	Board     string
	Range     string
	SubjectID uuid.UUID
}

func (q *Queries) BoardRowFor(ctx context.Context, arg BoardRowForParams) (LeaderboardEntry, error) {
	row := q.db.QueryRow(ctx, boardRowFor, arg.Board, arg.Range, arg.SubjectID)
	var i LeaderboardEntry
	err := row.Scan(
		&i.Board,
		&i.Range,
		&i.Rank,
		&i.SubjectID,
		&i.SubjectName,
		&i.SubjectHandle,
		&i.SubjectPictureUrl,
		&i.SubjectCreatedAt,
		&i.ValueMicros,
		&i.PnlMicros,
		&i.ReturnBps,
		&i.PricesAsOf,
		&i.ComputedAt,
		&i.Flags,
	)
	return i, err
}
