// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entries.sql

package sqlc

import (
	"context"
)

const deleteAllLeaderboardEntries = `-- name: DeleteAllLeaderboardEntries :exec
DELETE FROM leaderboard_entries WHERE range = 'ALL'
`

func (q *Queries) DeleteAllLeaderboardEntries(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllLeaderboardEntries)
	return err
}

const insertLeaderboardEntries = `-- name: InsertLeaderboardEntries :exec
INSERT INTO leaderboard_entries (
  board, range, rank, subject_id, subject_name, subject_handle, subject_picture_url, subject_created_at,
  value_micros, pnl_micros, return_bps, prices_as_of, computed_at, flags
)
SELECT board, range, rank, subject_id, subject_name, subject_handle, subject_picture_url, subject_created_at,
  value_micros, pnl_micros, return_bps, prices_as_of, computed_at, flags
FROM jsonb_to_recordset($1::jsonb) AS rows(
  board text, range text, rank int, subject_id uuid, subject_name text, subject_handle text,
  subject_picture_url text, subject_created_at timestamptz, value_micros bigint, pnl_micros bigint,
  return_bps bigint, prices_as_of timestamptz, computed_at timestamptz, flags text[]
)
`

func (q *Queries) InsertLeaderboardEntries(ctx context.Context, rows []byte) error {
	_, err := q.db.Exec(ctx, insertLeaderboardEntries, rows)
	return err
}
