// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertLeaderboardRun = `-- name: InsertLeaderboardRun :exec
INSERT INTO leaderboard_runs (
  run_id, as_of, prices_as_of, started_at, finished_at, rows_written, cabals_excluded
) VALUES (
  $1, $2, $3, $4, $5,
  $6, $7
)
`

type InsertLeaderboardRunParams struct {
	RunID          uuid.UUID
	AsOf           time.Time
	PricesAsOf     time.Time
	StartedAt      time.Time
	FinishedAt     time.Time
	RowsWritten    int32
	CabalsExcluded int32
}

func (q *Queries) InsertLeaderboardRun(ctx context.Context, arg InsertLeaderboardRunParams) error {
	_, err := q.db.Exec(ctx, insertLeaderboardRun,
		arg.RunID,
		arg.AsOf,
		arg.PricesAsOf,
		arg.StartedAt,
		arg.FinishedAt,
		arg.RowsWritten,
		arg.CabalsExcluded,
	)
	return err
}

const lastLeaderboardRun = `-- name: LastLeaderboardRun :one
SELECT run_id, as_of, prices_as_of, started_at, finished_at, rows_written, cabals_excluded, rev
FROM leaderboard_runs
ORDER BY finished_at DESC, run_id DESC
LIMIT 1
`

func (q *Queries) LastLeaderboardRun(ctx context.Context) (LeaderboardRun, error) {
	row := q.db.QueryRow(ctx, lastLeaderboardRun)
	var i LeaderboardRun
	err := row.Scan(
		&i.RunID,
		&i.AsOf,
		&i.PricesAsOf,
		&i.StartedAt,
		&i.FinishedAt,
		&i.RowsWritten,
		&i.CabalsExcluded,
		&i.Rev,
	)
	return i, err
}
