// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: triggers.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteRankingTriggersThrough = `-- name: DeleteRankingTriggersThrough :exec
DELETE FROM ranking_triggers WHERE created_at <= $1
`

func (q *Queries) DeleteRankingTriggersThrough(ctx context.Context, startedAt time.Time) error {
	_, err := q.db.Exec(ctx, deleteRankingTriggersThrough, startedAt)
	return err
}

const insertRankingTrigger = `-- name: InsertRankingTrigger :exec
INSERT INTO ranking_triggers (cabal_id, reason, created_at)
VALUES ($1, $2, $3)
`

type InsertRankingTriggerParams struct {
	CabalID   uuid.UUID
	Reason    string
	CreatedAt time.Time
}

func (q *Queries) InsertRankingTrigger(ctx context.Context, arg InsertRankingTriggerParams) error {
	_, err := q.db.Exec(ctx, insertRankingTrigger, arg.CabalID, arg.Reason, arg.CreatedAt)
	return err
}

const oldestRankingTrigger = `-- name: OldestRankingTrigger :one
SELECT created_at FROM ranking_triggers ORDER BY created_at, id LIMIT 1
`

func (q *Queries) OldestRankingTrigger(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, oldestRankingTrigger)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}
