//go:build go1.22

// Package rankingapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by cmd/gen httpapi from api/spec/*.yaml. DO NOT EDIT.
package rankingapi

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	externalRef0 "github.com/monaco/monaco/apps/backend/internal/platform/httpx/api"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CabalValueHistoryRange.
const (
	CabalValueHistoryRangeALL CabalValueHistoryRange = "ALL"
	CabalValueHistoryRangeN1D CabalValueHistoryRange = "1D"
	CabalValueHistoryRangeN1H CabalValueHistoryRange = "1H"
	CabalValueHistoryRangeN1M CabalValueHistoryRange = "1M"
	CabalValueHistoryRangeN1W CabalValueHistoryRange = "1W"
)

// Valid indicates whether the value is a known member of the CabalValueHistoryRange enum.
func (e CabalValueHistoryRange) Valid() bool {
	switch e {
	case CabalValueHistoryRangeALL:
		return true
	case CabalValueHistoryRangeN1D:
		return true
	case CabalValueHistoryRangeN1H:
		return true
	case CabalValueHistoryRangeN1M:
		return true
	case CabalValueHistoryRangeN1W:
		return true
	default:
		return false
	}
}

// Defines values for LeaderboardPageRange.
const (
	LeaderboardPageRangeALL LeaderboardPageRange = "ALL"
	LeaderboardPageRangeN1D LeaderboardPageRange = "1D"
	LeaderboardPageRangeN1H LeaderboardPageRange = "1H"
	LeaderboardPageRangeN1M LeaderboardPageRange = "1M"
	LeaderboardPageRangeN1W LeaderboardPageRange = "1W"
)

// Valid indicates whether the value is a known member of the LeaderboardPageRange enum.
func (e LeaderboardPageRange) Valid() bool {
	switch e {
	case LeaderboardPageRangeALL:
		return true
	case LeaderboardPageRangeN1D:
		return true
	case LeaderboardPageRangeN1H:
		return true
	case LeaderboardPageRangeN1M:
		return true
	case LeaderboardPageRangeN1W:
		return true
	default:
		return false
	}
}

// Defines values for LeaderboardRowFlags.
const (
	StalePrices    LeaderboardRowFlags = "stale_prices"
	UnpricedAssets LeaderboardRowFlags = "unpriced_assets"
)

// Valid indicates whether the value is a known member of the LeaderboardRowFlags enum.
func (e LeaderboardRowFlags) Valid() bool {
	switch e {
	case StalePrices:
		return true
	case UnpricedAssets:
		return true
	default:
		return false
	}
}

// Defines values for LeaderboardSubjectKind.
const (
	Cabal LeaderboardSubjectKind = "cabal"
	User  LeaderboardSubjectKind = "user"
)

// Valid indicates whether the value is a known member of the LeaderboardSubjectKind enum.
func (e LeaderboardSubjectKind) Valid() bool {
	switch e {
	case Cabal:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for LeaderboardFilter.
const (
	LeaderboardFilterAll     LeaderboardFilter = "all"
	LeaderboardFilterFriends LeaderboardFilter = "friends"
)

// Valid indicates whether the value is a known member of the LeaderboardFilter enum.
func (e LeaderboardFilter) Valid() bool {
	switch e {
	case LeaderboardFilterAll:
		return true
	case LeaderboardFilterFriends:
		return true
	default:
		return false
	}
}

// Defines values for LeaderboardRange.
const (
	LeaderboardRangeALL LeaderboardRange = "ALL"
	LeaderboardRangeN1D LeaderboardRange = "1D"
	LeaderboardRangeN1H LeaderboardRange = "1H"
	LeaderboardRangeN1M LeaderboardRange = "1M"
	LeaderboardRangeN1W LeaderboardRange = "1W"
)

// Valid indicates whether the value is a known member of the LeaderboardRange enum.
func (e LeaderboardRange) Valid() bool {
	switch e {
	case LeaderboardRangeALL:
		return true
	case LeaderboardRangeN1D:
		return true
	case LeaderboardRangeN1H:
		return true
	case LeaderboardRangeN1M:
		return true
	case LeaderboardRangeN1W:
		return true
	default:
		return false
	}
}

// Defines values for ValueHistoryRange.
const (
	ValueHistoryRangeALL ValueHistoryRange = "ALL"
	ValueHistoryRangeN1D ValueHistoryRange = "1D"
	ValueHistoryRangeN1H ValueHistoryRange = "1H"
	ValueHistoryRangeN1M ValueHistoryRange = "1M"
	ValueHistoryRangeN1W ValueHistoryRange = "1W"
)

// Valid indicates whether the value is a known member of the ValueHistoryRange enum.
func (e ValueHistoryRange) Valid() bool {
	switch e {
	case ValueHistoryRangeALL:
		return true
	case ValueHistoryRangeN1D:
		return true
	case ValueHistoryRangeN1H:
		return true
	case ValueHistoryRangeN1M:
		return true
	case ValueHistoryRangeN1W:
		return true
	default:
		return false
	}
}

// Defines values for GetCabalLeaderboardParamsRange.
const (
	GetCabalLeaderboardParamsRangeALL GetCabalLeaderboardParamsRange = "ALL"
	GetCabalLeaderboardParamsRangeN1D GetCabalLeaderboardParamsRange = "1D"
	GetCabalLeaderboardParamsRangeN1H GetCabalLeaderboardParamsRange = "1H"
	GetCabalLeaderboardParamsRangeN1M GetCabalLeaderboardParamsRange = "1M"
	GetCabalLeaderboardParamsRangeN1W GetCabalLeaderboardParamsRange = "1W"
)

// Valid indicates whether the value is a known member of the GetCabalLeaderboardParamsRange enum.
func (e GetCabalLeaderboardParamsRange) Valid() bool {
	switch e {
	case GetCabalLeaderboardParamsRangeALL:
		return true
	case GetCabalLeaderboardParamsRangeN1D:
		return true
	case GetCabalLeaderboardParamsRangeN1H:
		return true
	case GetCabalLeaderboardParamsRangeN1M:
		return true
	case GetCabalLeaderboardParamsRangeN1W:
		return true
	default:
		return false
	}
}

// Defines values for GetCabalValueHistoryParamsRange.
const (
	GetCabalValueHistoryParamsRangeALL GetCabalValueHistoryParamsRange = "ALL"
	GetCabalValueHistoryParamsRangeN1D GetCabalValueHistoryParamsRange = "1D"
	GetCabalValueHistoryParamsRangeN1H GetCabalValueHistoryParamsRange = "1H"
	GetCabalValueHistoryParamsRangeN1M GetCabalValueHistoryParamsRange = "1M"
	GetCabalValueHistoryParamsRangeN1W GetCabalValueHistoryParamsRange = "1W"
)

// Valid indicates whether the value is a known member of the GetCabalValueHistoryParamsRange enum.
func (e GetCabalValueHistoryParamsRange) Valid() bool {
	switch e {
	case GetCabalValueHistoryParamsRangeALL:
		return true
	case GetCabalValueHistoryParamsRangeN1D:
		return true
	case GetCabalValueHistoryParamsRangeN1H:
		return true
	case GetCabalValueHistoryParamsRangeN1M:
		return true
	case GetCabalValueHistoryParamsRangeN1W:
		return true
	default:
		return false
	}
}

// Defines values for GetCabalsLeaderboardParamsRange.
const (
	GetCabalsLeaderboardParamsRangeALL GetCabalsLeaderboardParamsRange = "ALL"
	GetCabalsLeaderboardParamsRangeN1D GetCabalsLeaderboardParamsRange = "1D"
	GetCabalsLeaderboardParamsRangeN1H GetCabalsLeaderboardParamsRange = "1H"
	GetCabalsLeaderboardParamsRangeN1M GetCabalsLeaderboardParamsRange = "1M"
	GetCabalsLeaderboardParamsRangeN1W GetCabalsLeaderboardParamsRange = "1W"
)

// Valid indicates whether the value is a known member of the GetCabalsLeaderboardParamsRange enum.
func (e GetCabalsLeaderboardParamsRange) Valid() bool {
	switch e {
	case GetCabalsLeaderboardParamsRangeALL:
		return true
	case GetCabalsLeaderboardParamsRangeN1D:
		return true
	case GetCabalsLeaderboardParamsRangeN1H:
		return true
	case GetCabalsLeaderboardParamsRangeN1M:
		return true
	case GetCabalsLeaderboardParamsRangeN1W:
		return true
	default:
		return false
	}
}

// Defines values for GetPeopleLeaderboardParamsRange.
const (
	GetPeopleLeaderboardParamsRangeALL GetPeopleLeaderboardParamsRange = "ALL"
	GetPeopleLeaderboardParamsRangeN1D GetPeopleLeaderboardParamsRange = "1D"
	GetPeopleLeaderboardParamsRangeN1H GetPeopleLeaderboardParamsRange = "1H"
	GetPeopleLeaderboardParamsRangeN1M GetPeopleLeaderboardParamsRange = "1M"
	GetPeopleLeaderboardParamsRangeN1W GetPeopleLeaderboardParamsRange = "1W"
)

// Valid indicates whether the value is a known member of the GetPeopleLeaderboardParamsRange enum.
func (e GetPeopleLeaderboardParamsRange) Valid() bool {
	switch e {
	case GetPeopleLeaderboardParamsRangeALL:
		return true
	case GetPeopleLeaderboardParamsRangeN1D:
		return true
	case GetPeopleLeaderboardParamsRangeN1H:
		return true
	case GetPeopleLeaderboardParamsRangeN1M:
		return true
	case GetPeopleLeaderboardParamsRangeN1W:
		return true
	default:
		return false
	}
}

// Defines values for GetPeopleLeaderboardParamsFilter.
const (
	GetPeopleLeaderboardParamsFilterAll     GetPeopleLeaderboardParamsFilter = "all"
	GetPeopleLeaderboardParamsFilterFriends GetPeopleLeaderboardParamsFilter = "friends"
)

// Valid indicates whether the value is a known member of the GetPeopleLeaderboardParamsFilter enum.
func (e GetPeopleLeaderboardParamsFilter) Valid() bool {
	switch e {
	case GetPeopleLeaderboardParamsFilterAll:
		return true
	case GetPeopleLeaderboardParamsFilterFriends:
		return true
	default:
		return false
	}
}

// CabalValueHistory A cabal's value curve.
type CabalValueHistory struct {
	// CabalId The cabal.
	//
	// Examples: 01890a5d-ac96-774b-bcce-b302099a8058
	CabalId openapi_types.UUID `json:"cabal_id"`

	// Points One point per bucket, oldest first.
	//
	// Examples: []
	Points []CabalValuePoint `json:"points"`

	// PricesAsOf The price time of the run the curve ends at. Null before the first run.
	//
	// Examples: 2026-10-04T11:59:00Z
	PricesAsOf *time.Time `json:"prices_as_of"`

	// Range The window the curve covers.
	//
	// Examples: ALL
	Range CabalValueHistoryRange `json:"range"`
}

// CabalValueHistoryRange The window the curve covers.
//
// Examples: ALL
type CabalValueHistoryRange string

// CabalValuePoint The cabal's value at the end of one bucket.
type CabalValuePoint struct {
	// At The end of the bucket.
	//
	// Examples: 2026-10-04T12:00:00Z
	At time.Time `json:"at"`

	// NavPerShareMicros The pot value per share in USDC micros.
	//
	// Examples: 1000000
	NavPerShareMicros int64 `json:"nav_per_share_micros"`

	// PnlMicros The pot value minus the net contributed, negative for a loss.
	//
	// Examples: -5
	PnlMicros int64 `json:"pnl_micros"`

	// ValueMicros The pot value in USDC micros.
	//
	// Examples: 1000000
	ValueMicros int64 `json:"value_micros"`
}

// LeaderboardPage One page of a leaderboard from one run.
type LeaderboardPage struct {
	// Board `cabals`, `people` or `cabal_members:<cabal id>`.
	//
	// Examples: cabals
	Board string `json:"board"`

	// ComputedAt When the rows were computed.
	//
	// Examples: 2026-10-04T12:00:00Z
	ComputedAt time.Time `json:"computed_at"`

	// Me The caller's own row on this board. Null when the caller has none.
	//
	// Examples: null
	Me *LeaderboardRow `json:"me"`

	// NextCursor The cursor for the next page. Null on the last page.
	//
	// Examples: null
	NextCursor *string `json:"next_cursor"`

	// PricesAsOf The price time the rows were valued at.
	//
	// Examples: 2026-10-04T11:59:00Z
	PricesAsOf time.Time `json:"prices_as_of"`

	// Range The window the return is measured over.
	//
	// Examples: ALL
	Range LeaderboardPageRange `json:"range"`

	// Rows The page, best rank first.
	//
	// Examples: []
	Rows []LeaderboardRow `json:"rows"`

	// RunId The run the page was read from. Null before the first run.
	//
	// Examples: 01890a5d-ac96-774b-bcce-b302099a8060
	RunId *openapi_types.UUID `json:"run_id"`
}

// LeaderboardPageRange The window the return is measured over.
//
// Examples: ALL
type LeaderboardPageRange string

// LeaderboardRow One ranked subject.
type LeaderboardRow struct {
	// Flags Why the row may be less exact.
	//
	// Examples: []
	Flags []LeaderboardRowFlags `json:"flags"`

	// PnlMicros Profit and loss in USDC micros, negative for a loss.
	//
	// Examples: -5
	PnlMicros int64 `json:"pnl_micros"`

	// Rank The dense rank on the board.
	//
	// Examples: 1
	Rank int32 `json:"rank"`

	// ReturnBps The return in basis points. Null when unranked.
	//
	// Examples: 250
	ReturnBps *int64 `json:"return_bps"`

	// Subject The cabal or person a row ranks.
	Subject LeaderboardSubject `json:"subject"`

	// ValueMicros Current value in USDC micros.
	//
	// Examples: 1000000
	ValueMicros int64 `json:"value_micros"`
}

// LeaderboardRowFlags defines model for LeaderboardRow.Flags.
type LeaderboardRowFlags string

// LeaderboardSubject The cabal or person a row ranks.
type LeaderboardSubject struct {
	// Handle The user's handle. Null for a cabal.
	//
	// Examples: null
	Handle *string `json:"handle"`

	// Id The cabal or user id.
	//
	// Examples: 01890a5d-ac96-774b-bcce-b302099a8058
	Id openapi_types.UUID `json:"id"`

	// Kind What the subject is.
	//
	// Examples: cabal
	Kind LeaderboardSubjectKind `json:"kind"`

	// Name The cabal or display name.
	//
	// Examples: Alpha
	Name string `json:"name"`

	// PictureUrl The picture. Null when there is none.
	//
	// Examples: null
	PictureUrl *string `json:"picture_url"`
}

// LeaderboardSubjectKind What the subject is.
//
// Examples: cabal
type LeaderboardSubjectKind string

// LeaderboardCursor Examples: MjA
type LeaderboardCursor = string

// LeaderboardFilter Examples: friends
type LeaderboardFilter string

// LeaderboardLimit Examples: 20
type LeaderboardLimit = int

// LeaderboardRange Examples: ALL
type LeaderboardRange string

// ValueHistoryRange Examples: ALL
type ValueHistoryRange string

// GetCabalLeaderboardParams defines parameters for GetCabalLeaderboard.
type GetCabalLeaderboardParams struct {
	// Range The window the return is measured over. Defaults to `ALL`.
	Range *GetCabalLeaderboardParamsRange `form:"range,omitempty" json:"range,omitempty"`

	// Cursor The `next_cursor` from the previous page. Absent reads the first page.
	Cursor *LeaderboardCursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Page size. Defaults to 20 and cannot exceed 50.
	Limit *LeaderboardLimit `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetCabalLeaderboardParamsRange defines parameters for GetCabalLeaderboard.
type GetCabalLeaderboardParamsRange string

// GetCabalValueHistoryParams defines parameters for GetCabalValueHistory.
type GetCabalValueHistoryParams struct {
	// Range The window the curve covers. Defaults to `ALL`.
	Range *GetCabalValueHistoryParamsRange `form:"range,omitempty" json:"range,omitempty"`
}

// GetCabalValueHistoryParamsRange defines parameters for GetCabalValueHistory.
type GetCabalValueHistoryParamsRange string

// GetCabalsLeaderboardParams defines parameters for GetCabalsLeaderboard.
type GetCabalsLeaderboardParams struct {
	// Range The window the return is measured over. Defaults to `ALL`.
	Range *GetCabalsLeaderboardParamsRange `form:"range,omitempty" json:"range,omitempty"`

	// Cursor The `next_cursor` from the previous page. Absent reads the first page.
	Cursor *LeaderboardCursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Page size. Defaults to 20 and cannot exceed 50.
	Limit *LeaderboardLimit `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetCabalsLeaderboardParamsRange defines parameters for GetCabalsLeaderboard.
type GetCabalsLeaderboardParamsRange string

// GetPeopleLeaderboardParams defines parameters for GetPeopleLeaderboard.
type GetPeopleLeaderboardParams struct {
	// Range The window the return is measured over. Defaults to `ALL`.
	Range *GetPeopleLeaderboardParamsRange `form:"range,omitempty" json:"range,omitempty"`

	// Cursor The `next_cursor` from the previous page. Absent reads the first page.
	Cursor *LeaderboardCursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Page size. Defaults to 20 and cannot exceed 50.
	Limit *LeaderboardLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Filter `all` reads the whole board. `friends` reads the people the caller follows and the caller.
	Filter *GetPeopleLeaderboardParamsFilter `form:"filter,omitempty" json:"filter,omitempty"`
}

// GetPeopleLeaderboardParamsRange defines parameters for GetPeopleLeaderboard.
type GetPeopleLeaderboardParamsRange string

// GetPeopleLeaderboardParamsFilter defines parameters for GetPeopleLeaderboard.
type GetPeopleLeaderboardParamsFilter string

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetCabalLeaderboard Read a cabal's members leaderboard.
	// (GET /v1/cabals/{id}/leaderboard)
	GetCabalLeaderboard(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params GetCabalLeaderboardParams)
	// GetCabalValueHistory Read a cabal's value history.
	// (GET /v1/cabals/{id}/value-history)
	GetCabalValueHistory(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params GetCabalValueHistoryParams)
	// GetCabalsLeaderboard Read the cabals leaderboard.
	// (GET /v1/leaderboards/cabals)
	GetCabalsLeaderboard(w http.ResponseWriter, r *http.Request, params GetCabalsLeaderboardParams)
	// GetPeopleLeaderboard Read the people leaderboard.
	// (GET /v1/leaderboards/people)
	GetPeopleLeaderboard(w http.ResponseWriter, r *http.Request, params GetPeopleLeaderboardParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetCabalLeaderboard operation middleware
func (siw *ServerInterfaceWrapper) GetCabalLeaderboard(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCabalLeaderboardParams

	// ------------- Optional query parameter "range" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "range", r.URL.Query(), &params.Range, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "range"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "range", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCabalLeaderboard(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCabalValueHistory operation middleware
func (siw *ServerInterfaceWrapper) GetCabalValueHistory(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCabalValueHistoryParams

	// ------------- Optional query parameter "range" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "range", r.URL.Query(), &params.Range, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "range"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "range", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCabalValueHistory(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCabalsLeaderboard operation middleware
func (siw *ServerInterfaceWrapper) GetCabalsLeaderboard(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCabalsLeaderboardParams

	// ------------- Optional query parameter "range" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "range", r.URL.Query(), &params.Range, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "range"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "range", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCabalsLeaderboard(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPeopleLeaderboard operation middleware
func (siw *ServerInterfaceWrapper) GetPeopleLeaderboard(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPeopleLeaderboardParams

	// ------------- Optional query parameter "range" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "range", r.URL.Query(), &params.Range, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "range"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "range", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "filter" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "filter", r.URL.Query(), &params.Filter, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "filter"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "filter", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPeopleLeaderboard(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/cabals/{id}/leaderboard", wrapper.GetCabalLeaderboard)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/cabals/{id}/value-history", wrapper.GetCabalValueHistory)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/leaderboards/cabals", wrapper.GetCabalsLeaderboard)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/leaderboards/people", wrapper.GetPeopleLeaderboard)

	return m
}

type GetCabalLeaderboardRequestObject struct {
	Id     openapi_types.UUID `json:"id"`
	Params GetCabalLeaderboardParams
}

type GetCabalLeaderboardResponseObject interface {
	VisitGetCabalLeaderboardResponse(w http.ResponseWriter) error
}

type GetCabalLeaderboard200JSONResponse LeaderboardPage

func (response GetCabalLeaderboard200JSONResponse) VisitGetCabalLeaderboardResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetCabalLeaderboarddefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response GetCabalLeaderboarddefaultApplicationProblemPlusJSONResponse) VisitGetCabalLeaderboardResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetCabalValueHistoryRequestObject struct {
	Id     openapi_types.UUID `json:"id"`
	Params GetCabalValueHistoryParams
}

type GetCabalValueHistoryResponseObject interface {
	VisitGetCabalValueHistoryResponse(w http.ResponseWriter) error
}

type GetCabalValueHistory200JSONResponse CabalValueHistory

func (response GetCabalValueHistory200JSONResponse) VisitGetCabalValueHistoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetCabalValueHistorydefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response GetCabalValueHistorydefaultApplicationProblemPlusJSONResponse) VisitGetCabalValueHistoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetCabalsLeaderboardRequestObject struct {
	Params GetCabalsLeaderboardParams
}

type GetCabalsLeaderboardResponseObject interface {
	VisitGetCabalsLeaderboardResponse(w http.ResponseWriter) error
}

type GetCabalsLeaderboard200JSONResponse LeaderboardPage

func (response GetCabalsLeaderboard200JSONResponse) VisitGetCabalsLeaderboardResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetCabalsLeaderboarddefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response GetCabalsLeaderboarddefaultApplicationProblemPlusJSONResponse) VisitGetCabalsLeaderboardResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetPeopleLeaderboardRequestObject struct {
	Params GetPeopleLeaderboardParams
}

type GetPeopleLeaderboardResponseObject interface {
	VisitGetPeopleLeaderboardResponse(w http.ResponseWriter) error
}

type GetPeopleLeaderboard200JSONResponse LeaderboardPage

func (response GetPeopleLeaderboard200JSONResponse) VisitGetPeopleLeaderboardResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPeopleLeaderboarddefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response GetPeopleLeaderboarddefaultApplicationProblemPlusJSONResponse) VisitGetPeopleLeaderboardResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetCabalLeaderboard Read a cabal's members leaderboard.
	// (GET /v1/cabals/{id}/leaderboard)
	GetCabalLeaderboard(ctx context.Context, request GetCabalLeaderboardRequestObject) (GetCabalLeaderboardResponseObject, error)
	// GetCabalValueHistory Read a cabal's value history.
	// (GET /v1/cabals/{id}/value-history)
	GetCabalValueHistory(ctx context.Context, request GetCabalValueHistoryRequestObject) (GetCabalValueHistoryResponseObject, error)
	// GetCabalsLeaderboard Read the cabals leaderboard.
	// (GET /v1/leaderboards/cabals)
	GetCabalsLeaderboard(ctx context.Context, request GetCabalsLeaderboardRequestObject) (GetCabalsLeaderboardResponseObject, error)
	// GetPeopleLeaderboard Read the people leaderboard.
	// (GET /v1/leaderboards/people)
	GetPeopleLeaderboard(ctx context.Context, request GetPeopleLeaderboardRequestObject) (GetPeopleLeaderboardResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetCabalLeaderboard operation middleware
func (sh *strictHandler) GetCabalLeaderboard(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params GetCabalLeaderboardParams) {
	var request GetCabalLeaderboardRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCabalLeaderboard(ctx, request.(GetCabalLeaderboardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCabalLeaderboard")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCabalLeaderboardResponseObject); ok {
		if err := validResponse.VisitGetCabalLeaderboardResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCabalValueHistory operation middleware
func (sh *strictHandler) GetCabalValueHistory(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params GetCabalValueHistoryParams) {
	var request GetCabalValueHistoryRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCabalValueHistory(ctx, request.(GetCabalValueHistoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCabalValueHistory")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCabalValueHistoryResponseObject); ok {
		if err := validResponse.VisitGetCabalValueHistoryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCabalsLeaderboard operation middleware
func (sh *strictHandler) GetCabalsLeaderboard(w http.ResponseWriter, r *http.Request, params GetCabalsLeaderboardParams) {
	var request GetCabalsLeaderboardRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCabalsLeaderboard(ctx, request.(GetCabalsLeaderboardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCabalsLeaderboard")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCabalsLeaderboardResponseObject); ok {
		if err := validResponse.VisitGetCabalsLeaderboardResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPeopleLeaderboard operation middleware
func (sh *strictHandler) GetPeopleLeaderboard(w http.ResponseWriter, r *http.Request, params GetPeopleLeaderboardParams) {
	var request GetPeopleLeaderboardRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPeopleLeaderboard(ctx, request.(GetPeopleLeaderboardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPeopleLeaderboard")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPeopleLeaderboardResponseObject); ok {
		if err := validResponse.VisitGetPeopleLeaderboardResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
