package main

import (
	"fmt"
	"io"
	"io/fs"
	"os"
	"slices"
	"strings"

	"github.com/monaco/monaco/apps/backend/internal/errs"
	"github.com/monaco/monaco/apps/backend/internal/events"
	"github.com/monaco/monaco/apps/backend/internal/platform/observability"
	"github.com/monaco/monaco/apps/backend/internal/tools/flows"
)

func docs(args []string, stdout, stderr io.Writer) int {
	switch {
	case slices.Equal(args, []string{"errors"}):
		_, _ = io.WriteString(stdout, errorTable(errs.All()))
		return 0
	case slices.Equal(args, []string{"events"}):
		_, _ = io.WriteString(stdout, eventCatalog(events.Catalog()))
		return 0
	case slices.Equal(args, []string{"flows"}):
		return docsFlows(os.DirFS("../.."), stdout, stderr)
	case slices.Equal(args, []string{"logs"}):
		return docsLogs(stdout, stderr)
	default:
		_, _ = fmt.Fprintln(stderr, "usage: monacoctl docs errors|events|flows|logs")
		return 2
	}
}

func docsFlows(repo fs.FS, stdout, stderr io.Writer) int {
	parsed, problems, err := readFlows(repo)
	if err != nil {
		_, _ = fmt.Fprintf(stderr, "monacoctl docs flows: %v\n", err)
		return 1
	}
	for _, p := range problems {
		_, _ = fmt.Fprintln(stderr, p)
	}
	if len(problems) > 0 {
		return 1
	}
	_, _ = io.WriteString(stdout, flows.Markdown(parsed))
	return 0
}

func docsLogs(stdout, stderr io.Writer) int {
	if err := observability.WriteCatalog(stdout); err != nil {
		_, _ = fmt.Fprintf(stderr, "monacoctl docs logs: %v\n", err)
		return 1
	}
	return 0
}

func eventCatalog(entries []events.Entry) string {
	var b strings.Builder
	b.WriteString(
		"# Event catalog\n\nGenerated by `monacoctl docs events` from the `internal/events` registry. Do not edit.\n",
	)
	for _, e := range entries {
		fmt.Fprintf(
			&b,
			"\n## `%s`\n\nSubject `%s`, version %d.\n\n| Field | Go type |\n| --- | --- |\n",
			e.Type,
			e.Subject,
			e.Version,
		)
		for _, f := range e.Fields {
			fmt.Fprintf(&b, "| `%s` | `%s` |\n", f.Name, f.GoType)
		}
	}
	return b.String()
}

func errorTable(codes []errs.Code) string {
	yesNo := map[bool]string{true: "yes", false: "no"}
	var b strings.Builder
	b.WriteString("| Code | HTTP status | Retryable | Alerts | Message |\n| --- | --- | --- | --- | --- |\n")
	for _, c := range codes {
		fmt.Fprintf(&b, "| `%s` | %d | %s | %s | %s |\n",
			c, errs.HTTPStatus(errs.KindOf(c)), yesNo[errs.Retryable(c)], yesNo[errs.Alert(c)], errs.Message(c))
	}
	return b.String()
}

func toolDocs(_ toolEnv) tool { return docs }
