package main

import (
	"bytes"
	"strings"
	"testing"
	"testing/fstest"

	"github.com/monaco/monaco/apps/backend/internal/tools/flows"
)

func TestDocsRejectsAnUnknownTopic(t *testing.T) {
	t.Parallel()
	for _, args := range [][]string{
		{"docs"},
		{"docs", "nope"},
		{"docs", "events"},
		{"docs", "flows", "extra"},
		{"docs", "flows", "--nope"},
		{"docs", "flows", "--feature-map"},
	} {
		var stdout, stderr bytes.Buffer
		if code := run(commands(), tools(nil), nil, args, &stdout, &stderr); code != 2 || stdout.Len() != 0 ||
			stderr.String() != "usage: monacoctl docs flows\n" {
			t.Fatalf("%q: code=%d stdout=%q stderr=%q", args, code, stdout.String(), stderr.String())
		}
	}
}

func TestDocsFlowsRendersTheTSV(t *testing.T) {
	t.Parallel()
	for _, tc := range []struct {
		name, tsv      string
		code           int
		stdout, stderr string
	}{
		{
			"valid", flows.Header + "\n" + pingRow + "\n", 0,
			"| # | Flow | Command / trigger | Events | Consumers |\n| --- | --- | --- | --- | --- |\n" +
				"| 01 | Ping | `Ping` on `poller:platform.retention` | `system.pinged` | none |\n", "",
		},
		{"malformed", flows.Header + "\n01\tPing\n", 1, "", flows.Dir + "/01.tsv:2: has 2 columns, want 10\n"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			var stdout, stderr bytes.Buffer
			code := docsFlows(envWith(t, tc.tsv).Repo, flows.Markdown, &stdout, &stderr)
			if code != tc.code || stdout.String() != tc.stdout || stderr.String() != tc.stderr {
				t.Fatalf("code=%d stdout=%q stderr=%q", code, stdout.String(), stderr.String())
			}
		})
	}
}

func featureMapPage(t *testing.T, row string) string {
	t.Helper()
	parsed, problems := flows.Parse(flows.Dir+"/00.tsv", strings.NewReader(flows.Header+"\n"+row+"\n"))
	if len(problems) != 0 || len(parsed) != 1 {
		t.Fatalf("parse = %v, %v", parsed, problems)
	}
	return flows.FeatureMapPage(parsed[0])
}

func TestFeatureMapPageListsEachOutcomeWithItsTestAndVerifyCommand(t *testing.T) {
	t.Parallel()
	row := "00\tPing\tsystem\tPOST /v1/system/pings\tRecordPing\tsystem.pinged\tsystem.echo\t" +
		"ok;InvalidInput;crash:after-publish\tverified\tdocs/flows.md#ping"
	want := "# Flow 00: Ping\n\n" +
		"Generated by `cmd/gen flows` from `packages/flows/backend/00.tsv`. Do not edit.\n\n" +
		"- Module: `system`\n- Status: `verified`\n- Trigger: `POST /v1/system/pings`\n" +
		"- Command: `RecordPing`\n- Events: `system.pinged`\n- Consumers: `system.echo`\n" +
		"- Doc: `docs/flows.md#ping`\n\n" +
		"| Outcome | Test | Verify |\n| --- | --- | --- |\n" +
		"| `ok` | `TestFlow00_RecordPing_OK` | `monacoctl verify flow 00 --outcome ok` |\n" +
		"| `InvalidInput` | `TestFlow00_RecordPing_InvalidInput` | `monacoctl verify flow 00 --outcome InvalidInput` |\n" +
		"| `crash:after-publish` | `TestFlow00_RecordPing_CrashAfterPublish` | " +
		"`monacoctl verify flow 00 --outcome crash:after-publish` |\n"
	if got := featureMapPage(t, row); got != want {
		t.Fatalf("page =\n%s\nwant\n%s", got, want)
	}
}

func TestFeatureMapPageWritesNoneForAnEmptyCommandOrConsumerList(t *testing.T) {
	t.Parallel()
	got := featureMapPage(t, pingRow)
	for _, line := range []string{
		"- Command: `Ping`\n",
		"- Consumers: none\n",
		"- Trigger: `poller:platform.retention`\n",
	} {
		if !strings.Contains(got, line) {
			t.Fatalf("page =\n%s\nwant a line %q", got, line)
		}
	}
	noCommand := strings.NewReplacer("\tPing\tsystem.pinged", "\t\tsystem.pinged", "\tbuilt\t", "\tplanned\t").
		Replace(pingRow)
	if got := featureMapPage(t, noCommand); !strings.Contains(got, "- Command: none\n") {
		t.Fatalf("page =\n%s\nwant Command: none", got)
	}
}

func TestDocsFlowsFailsWhenTheTSVIsMissing(t *testing.T) {
	t.Parallel()
	var stdout, stderr bytes.Buffer
	code := docsFlows(fstest.MapFS{}, flows.Markdown, &stdout, &stderr)
	if code != 1 || stdout.Len() != 0 || !strings.HasPrefix(stderr.String(), "monacoctl docs flows: ") {
		t.Fatalf("code=%d stdout=%q stderr=%q", code, stdout.String(), stderr.String())
	}
}
