package main

import (
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/monaco/monaco/apps/backend/internal/errs"
	codegen "github.com/monaco/monaco/apps/backend/internal/tools/gen"
)

const errorCodesHeader = `# Code generated by monacoctl gen errors from internal/errs. DO NOT EDIT.
components:
  schemas:
    ErrorCode:
      type: string
      description: The closed list of error codes. Generated from the errs table by monacoctl gen errors.
      examples: [not_found]
      enum:
`

func toolGen(env toolEnv) tool {
	return func(args []string, stdout, stderr io.Writer) int {
		if len(args) > 0 && args[0] == "migration" {
			return migrate(codegen.NewMigrator(env.wd, runIn(env.wd)), args[1:], stdout, stderr)
		}
		if len(args) > 0 {
			if g, ok := codegen.Find(args[0]); ok {
				return scaffold(g, env.wd, args[1:], stdout, stderr)
			}
		}
		return gen(args, stdout, stderr)
	}
}

func scaffold(g codegen.Generator, root string, args []string, stdout, stderr io.Writer) int {
	touched, err := g.Run(context.Background(), root, args)
	for _, rel := range touched {
		_, _ = fmt.Fprintln(stdout, rel)
	}
	if err != nil {
		_, _ = fmt.Fprintf(stderr, "monacoctl: %v\n", err)
		return 1
	}
	return 0
}

func migrate(m codegen.Migrator, args []string, stdout, stderr io.Writer) int {
	touched, err := m.Run(context.Background(), args)
	for _, rel := range touched {
		_, _ = fmt.Fprintln(stdout, rel)
	}
	if err != nil {
		_, _ = fmt.Fprintf(stderr, "monacoctl: %v\n", err)
		return 1
	}
	return 0
}

func genUsage(stderr io.Writer) int {
	_, _ = fmt.Fprintln(stderr, "usage: monacoctl gen errors <spec/error_codes.yaml> [<ErrorCodeCases.gen.swift>]")
	_, _ = fmt.Fprintln(stderr, "       monacoctl gen openapi <spec-dir> <openapi.yaml>")
	_, _ = fmt.Fprintln(stderr, "       monacoctl gen flows")
	for _, g := range codegen.Generators() {
		_, _ = fmt.Fprintln(stderr, "       monacoctl "+g.Usage())
	}
	_, _ = fmt.Fprintln(stderr, "       monacoctl "+codegen.MigrationUsage())
	return 2
}

func gen(args []string, stdout, stderr io.Writer) int {
	if len(args) == 1 && args[0] == "flows" {
		return runGenFlows("../..", stdout, stderr)
	}
	if len(args) == 3 && args[0] == "openapi" {
		return runGenOpenAPI([3]string(args), stdout, stderr)
	}
	if len(args) < 2 || len(args) > 3 || args[0] != "errors" {
		return genUsage(stderr)
	}
	if err := writeErrorCodes(args[1], errs.All()); err != nil {
		_, _ = fmt.Fprintf(stderr, "monacoctl: %v\n", err)
		return 1
	}
	if len(args) == 3 {
		if err := writeSwiftCases(args[2], errs.All()); err != nil {
			_, _ = fmt.Fprintf(stderr, "monacoctl: %v\n", err)
			return 1
		}
	}
	_, _ = fmt.Fprintf(stdout, "wrote %d error codes to %s\n", len(errs.All()), args[1])
	return 0
}

func writeErrorCodes(path string, codes []errs.Code) error {
	dir, err := os.OpenRoot(filepath.Dir(path))
	if err != nil {
		return errs.Wrap(err, errs.CodeInvalidInput, "monacoctl.writeErrorCodes")
	}
	defer func() { _ = dir.Close() }()
	if err := dir.WriteFile(filepath.Base(path), []byte(renderErrorCodes(codes)), 0o600); err != nil {
		return errs.Wrap(err, errs.CodeInternal, "monacoctl.writeErrorCodes")
	}
	return nil
}

func renderErrorCodes(codes []errs.Code) string {
	var b strings.Builder
	b.WriteString(errorCodesHeader)
	for _, code := range codes {
		b.WriteString("        - " + string(code) + "\n")
	}
	return b.String()
}

func runGenOpenAPI(args [3]string, stdout, stderr io.Writer) int {
	if err := genOpenAPI(args[1], args[2]); err != nil {
		_, _ = fmt.Fprintf(stderr, "monacoctl: %v\n", err)
		return 1
	}
	_, _ = fmt.Fprintf(stdout, "wrote %s from %s\n", args[2], args[1])
	return 0
}
