package main

import (
	"fmt"
	"io/fs"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/monaco/monaco/apps/backend/internal/errs"
)

const (
	baseSpec     = "base.yaml"
	bundleHeader = "# Code generated by monacoctl gen openapi from api/spec/*.yaml. DO NOT EDIT."
	bundleOp     = "monacoctl.bundleOpenAPI"

	pathColumn  = 3
	entryColumn = 5
)

func genOpenAPI(specDir, out string) error {
	bundle, err := bundleOpenAPI(specDir)
	if err != nil {
		return err
	}
	dir, err := os.OpenRoot(filepath.Dir(out))
	if err != nil {
		return errs.Wrap(err, errs.CodeInvalidInput, bundleOp)
	}
	defer func() { _ = dir.Close() }()
	if err := dir.WriteFile(filepath.Base(out), bundle, 0o600); err != nil {
		return errs.Wrap(err, errs.CodeInternal, bundleOp)
	}
	return nil
}

func bundleOpenAPI(specDir string) ([]byte, error) {
	root, err := os.OpenRoot(specDir)
	if err != nil {
		return nil, errs.Wrap(err, errs.CodeInvalidInput, bundleOp)
	}
	defer func() { _ = root.Close() }()
	names, _ := fs.Glob(root.FS(), "*.yaml")
	if !slices.Contains(names, baseSpec) {
		return nil, specProblem("%s has no %s", specDir, baseSpec)
	}
	slices.Sort(names)
	var b bundler
	for _, name := range slices.Concat([]string{baseSpec}, slices.DeleteFunc(names, func(n string) bool { return n == baseSpec })) {
		src, err := root.ReadFile(name)
		if err != nil {
			return nil, errs.Wrap(err, errs.CodeInvalidInput, bundleOp)
		}
		if err := b.add(name, string(src)); err != nil {
			return nil, err
		}
	}
	return []byte(b.render()), nil
}

type block struct {
	file  string
	lines []string
}

type group struct {
	label   string
	entries map[string]block
}

type bundler struct {
	order    []string
	raw      map[string][]string
	paths    group
	kinds    map[string]*group
	kindList []string
}

type specError string

func (e specError) Error() string { return string(e) }

func specProblem(format string, args ...any) error {
	return errs.Wrap(specError(fmt.Sprintf(format, args...)), errs.CodeInvalidInput, bundleOp)
}

func componentLabel(kind string) string {
	if label, ok := map[string]string{
		"schemas": "schema", "parameters": "parameter", "responses": "response", "securitySchemes": "security scheme",
	}[kind]; ok {
		return label
	}
	return kind
}

func (b *bundler) add(file, src string) error {
	lines := strings.Split(strings.TrimRight(src, "\n"), "\n")
	var doc yaml.Node
	if err := yaml.Unmarshal([]byte(src), &doc); err != nil {
		return specProblem("%s: %v", file, err)
	}
	if len(doc.Content) != 1 || doc.Content[0].Kind != yaml.MappingNode {
		return specProblem("%s: want a mapping at the top level", file)
	}
	if line := nullBranchLine(doc.Content[0]); line > 0 {
		return specProblem("%s:%d: a null branch in anyOf or oneOf makes the Swift generator drop the property; "+
			"write type: [object, \"null\"] with the properties inline instead", file, line)
	}
	isBase := file == baseSpec
	if isBase {
		b.raw = map[string][]string{}
		b.paths = group{label: "path", entries: map[string]block{}}
		b.kinds = map[string]*group{}
	}
	top := doc.Content[0].Content
	var found []string
	for i := 0; i < len(top); i += 2 {
		end := len(lines)
		if i+2 < len(top) {
			end = top[i+2].Line - 1
		}
		key := top[i].Value
		if err := b.addKey(file, key, top[i], top[i+1], lines, end); err != nil {
			return err
		}
		found = append(found, key)
	}
	if isBase && (!slices.Contains(found, "paths") || !slices.Contains(found, "components")) {
		return specProblem("%s: want both paths and components", file)
	}
	return nil
}

func nullBranchLine(node *yaml.Node) int {
	if line := nullBranchHere(node); line > 0 {
		return line
	}
	for _, child := range node.Content {
		if line := nullBranchLine(child); line > 0 {
			return line
		}
	}
	return 0
}

func nullBranchHere(node *yaml.Node) int {
	if node.Kind != yaml.MappingNode {
		return 0
	}
	for i := 0; i+1 < len(node.Content); i += 2 {
		key, value := node.Content[i], node.Content[i+1]
		if (key.Value == "anyOf" || key.Value == "oneOf") && slices.ContainsFunc(value.Content, isNullType) {
			return key.Line
		}
	}
	return 0
}

func isNullType(node *yaml.Node) bool {
	if node.Kind != yaml.MappingNode {
		return false
	}
	for i := 0; i+1 < len(node.Content); i += 2 {
		if node.Content[i].Value == "type" && node.Content[i+1].Value == "null" {
			return true
		}
	}
	return false
}

func (b *bundler) addKey(file, key string, keyNode, value *yaml.Node, lines []string, end int) error {
	switch key {
	case "paths":
		if err := b.addEntries(file, &b.paths, value, pathColumn, lines, end); err != nil {
			return err
		}
	case "components":
		if err := b.addComponents(file, value, lines, end); err != nil {
			return err
		}
	default:
		if file != baseSpec {
			return specProblem("%s: top-level key %q belongs in %s", file, key, baseSpec)
		}
		b.raw[key] = lines[keyNode.Line-1 : end]
	}
	if file == baseSpec {
		b.order = append(b.order, key)
	}
	return nil
}

func (b *bundler) addComponents(file string, node *yaml.Node, lines []string, end int) error {
	if node.Kind != yaml.MappingNode {
		return specProblem("%s: components must be a mapping", file)
	}
	for j := 0; j < len(node.Content); j += 2 {
		kind := node.Content[j].Value
		if node.Content[j].Column != pathColumn {
			return specProblem("%s: components.%s must be indented two spaces", file, kind)
		}
		g := b.kinds[kind]
		if g == nil {
			g = &group{label: componentLabel(kind), entries: map[string]block{}}
			b.kinds[kind] = g
			b.kindList = append(b.kindList, kind)
		}
		kindEnd := end
		if j+2 < len(node.Content) {
			kindEnd = node.Content[j+2].Line - 1
		}
		if err := b.addEntries(file, g, node.Content[j+1], entryColumn, lines, kindEnd); err != nil {
			return err
		}
	}
	return nil
}

func (b *bundler) addEntries(file string, g *group, node *yaml.Node, column int, lines []string, end int) error {
	if node.Kind != yaml.MappingNode {
		return specProblem("%s: %s entries must be a mapping", file, g.label)
	}
	if node.Style&yaml.FlowStyle != 0 && len(node.Content) > 0 {
		return specProblem("%s: %s entries must be in block style", file, g.label)
	}
	for k := 0; k < len(node.Content); k += 2 {
		key := node.Content[k]
		if key.Column != column {
			return specProblem("%s: %s %s must be indented %d spaces", file, g.label, key.Value, column-1)
		}
		stop := end
		if k+2 < len(node.Content) {
			stop = node.Content[k+2].Line - 1
		}
		if first, dup := g.entries[key.Value]; dup {
			return specProblem("%s %s is defined in both %s and %s", g.label, key.Value, first.file, file)
		}
		body := lines[key.Line-1 : stop]
		for len(body) > 0 && strings.TrimSpace(body[len(body)-1]) == "" {
			body = body[:len(body)-1]
		}
		g.entries[key.Value] = block{file: file, lines: body}
	}
	return nil
}

func (b *bundler) render() string {
	out := []string{bundleHeader}
	for _, key := range b.order {
		switch key {
		case "paths":
			if len(b.paths.entries) == 0 {
				out = append(out, "paths: {}")
				continue
			}
			out = append(out, "paths:")
			out = append(out, b.paths.sorted()...)
		case "components":
			out = append(out, "components:")
			for _, kind := range b.kindList {
				out = append(out, "  "+kind+":")
				out = append(out, b.kinds[kind].sorted()...)
			}
		default:
			out = append(out, b.raw[key]...)
		}
	}
	return strings.Join(out, "\n") + "\n"
}

func (g *group) sorted() []string {
	var out []string
	for _, key := range slices.Sorted(maps.Keys(g.entries)) {
		out = append(out, g.entries[key].lines...)
	}
	return out
}
