// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deposits.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const advanceDepositCursor = `-- name: AdvanceDepositCursor :exec
INSERT INTO deposit_cursors (wallet_address, last_signature, cursor_slot, scanned_at)
VALUES ($1, $4::text, $2, $3)
ON CONFLICT (wallet_address) DO UPDATE
SET last_signature = EXCLUDED.last_signature,
    cursor_slot = EXCLUDED.cursor_slot,
    scanned_at = EXCLUDED.scanned_at
WHERE EXCLUDED.cursor_slot >= deposit_cursors.cursor_slot
`

type AdvanceDepositCursorParams struct {
	WalletAddress string
	CursorSlot    int64
	ScannedAt     time.Time
	LastSignature string
}

func (q *Queries) AdvanceDepositCursor(ctx context.Context, arg AdvanceDepositCursorParams) error {
	_, err := q.db.Exec(ctx, advanceDepositCursor,
		arg.WalletAddress,
		arg.CursorSlot,
		arg.ScannedAt,
		arg.LastSignature,
	)
	return err
}

const checkpointDepositWatchPage = `-- name: CheckpointDepositWatchPage :exec
UPDATE deposit_watch_accounts
SET page_before = NULLIF($2::text, ''),
    page_top_signature = CASE WHEN page_top_signature IS NULL AND $3::text <> '' THEN $3::text ELSE page_top_signature END,
    page_top_slot = CASE WHEN page_top_slot IS NULL AND $4::bigint > 0 THEN $4::bigint ELSE page_top_slot END,
    scanned_at = $5::timestamptz
WHERE token_account = $1
`

type CheckpointDepositWatchPageParams struct {
	TokenAccount     string
	PageBefore       string
	PageTopSignature string
	PageTopSlot      int64
	ScannedAt        time.Time
}

func (q *Queries) CheckpointDepositWatchPage(ctx context.Context, arg CheckpointDepositWatchPageParams) error {
	_, err := q.db.Exec(ctx, checkpointDepositWatchPage,
		arg.TokenAccount,
		arg.PageBefore,
		arg.PageTopSignature,
		arg.PageTopSlot,
		arg.ScannedAt,
	)
	return err
}

const completeDepositWatchPage = `-- name: CompleteDepositWatchPage :exec
UPDATE deposit_watch_accounts
SET high_signature = page_top_signature,
    high_slot = COALESCE(page_top_slot, high_slot),
    page_before = NULL,
    page_top_signature = NULL,
    page_top_slot = NULL,
    clean_gen = GREATEST(clean_gen, $2),
    scanned_at = $3::timestamptz
WHERE token_account = $1
`

type CompleteDepositWatchPageParams struct {
	TokenAccount string
	CleanGen     int64
	ScannedAt    time.Time
}

func (q *Queries) CompleteDepositWatchPage(ctx context.Context, arg CompleteDepositWatchPageParams) error {
	_, err := q.db.Exec(ctx, completeDepositWatchPage, arg.TokenAccount, arg.CleanGen, arg.ScannedAt)
	return err
}

const depositCursorsForWallets = `-- name: DepositCursorsForWallets :many
WITH wallets AS (SELECT unnest($1::text[])::text AS wallet_address)
SELECT wallets.wallet_address,
  COALESCE(deposit_cursors.last_signature, '') AS last_signature,
  COALESCE(deposit_cursors.cursor_slot, 0) AS cursor_slot,
  COALESCE(deposit_cursors.backfill_before_signature, '') AS backfill_before_signature,
  COALESCE(deposit_cursors.backfill_head_signature, '') AS backfill_head_signature,
  COALESCE(deposit_cursors.backfill_head_slot, 0) AS backfill_head_slot,
  COALESCE(deposit_cursors.scanned_at, to_timestamp(0)) AS scanned_at,
  (deposit_cursors.wallet_address IS NOT NULL)::bool AS exists
FROM wallets
LEFT JOIN deposit_cursors ON deposit_cursors.wallet_address = wallets.wallet_address
ORDER BY COALESCE(deposit_cursors.scanned_at, to_timestamp(0))
`

type DepositCursorsForWalletsRow struct {
	WalletAddress           string
	LastSignature           string
	CursorSlot              int64
	BackfillBeforeSignature string
	BackfillHeadSignature   string
	BackfillHeadSlot        int64
	ScannedAt               time.Time
	Exists                  bool
}

func (q *Queries) DepositCursorsForWallets(ctx context.Context, walletAddresses []string) ([]DepositCursorsForWalletsRow, error) {
	rows, err := q.db.Query(ctx, depositCursorsForWallets, walletAddresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DepositCursorsForWalletsRow
	for rows.Next() {
		var i DepositCursorsForWalletsRow
		if err := rows.Scan(
			&i.WalletAddress,
			&i.LastSignature,
			&i.CursorSlot,
			&i.BackfillBeforeSignature,
			&i.BackfillHeadSignature,
			&i.BackfillHeadSlot,
			&i.ScannedAt,
			&i.Exists,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const depositWatchDirtyAccounts = `-- name: DepositWatchDirtyAccounts :many
SELECT a.token_account, a.wallet_address, w.user_id, a.dirty_gen, a.clean_gen,
  a.dirty_slot, a.observed_slot, a.high_signature, a.high_slot, a.page_before,
  a.page_top_signature, a.page_top_slot
FROM deposit_watch_accounts a
JOIN deposit_watch_wallets w ON w.wallet_address = a.wallet_address
WHERE a.dirty_gen > a.clean_gen AND a.state != 'foreign'
ORDER BY a.dirty_slot, a.token_account
LIMIT $1
`

type DepositWatchDirtyAccountsRow struct {
	TokenAccount     string
	WalletAddress    string
	UserID           uuid.UUID
	DirtyGen         int64
	CleanGen         int64
	DirtySlot        int64
	ObservedSlot     int64
	HighSignature    pgtype.Text
	HighSlot         int64
	PageBefore       pgtype.Text
	PageTopSignature pgtype.Text
	PageTopSlot      pgtype.Int8
}

func (q *Queries) DepositWatchDirtyAccounts(ctx context.Context, limit int32) ([]DepositWatchDirtyAccountsRow, error) {
	rows, err := q.db.Query(ctx, depositWatchDirtyAccounts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DepositWatchDirtyAccountsRow
	for rows.Next() {
		var i DepositWatchDirtyAccountsRow
		if err := rows.Scan(
			&i.TokenAccount,
			&i.WalletAddress,
			&i.UserID,
			&i.DirtyGen,
			&i.CleanGen,
			&i.DirtySlot,
			&i.ObservedSlot,
			&i.HighSignature,
			&i.HighSlot,
			&i.PageBefore,
			&i.PageTopSignature,
			&i.PageTopSlot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const depositWatchKnownWallets = `-- name: DepositWatchKnownWallets :many
SELECT wallet_address
FROM deposit_watch_wallets
WHERE wallet_address = ANY($1::text[])
`

func (q *Queries) DepositWatchKnownWallets(ctx context.Context, walletAddresses []string) ([]string, error) {
	rows, err := q.db.Query(ctx, depositWatchKnownWallets, walletAddresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var wallet_address string
		if err := rows.Scan(&wallet_address); err != nil {
			return nil, err
		}
		items = append(items, wallet_address)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDeposit = `-- name: InsertDeposit :execrows
INSERT INTO deposits (
  id, user_id, wallet_address, tx_signature, amount_micros, slot, block_time, credited_at
) VALUES ($1, $2, $3, $4, $7::text::numeric, $5,
  NULLIF($8::timestamptz, '0001-01-01 00:00:00+00'::timestamptz), $6)
ON CONFLICT (tx_signature, wallet_address) DO NOTHING
`

type InsertDepositParams struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	WalletAddress string
	TxSignature   string
	Slot          int64
	CreditedAt    time.Time
	AmountMicros  string
	BlockTime     time.Time
}

func (q *Queries) InsertDeposit(ctx context.Context, arg InsertDepositParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertDeposit,
		arg.ID,
		arg.UserID,
		arg.WalletAddress,
		arg.TxSignature,
		arg.Slot,
		arg.CreditedAt,
		arg.AmountMicros,
		arg.BlockTime,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertDepositCandidate = `-- name: InsertDepositCandidate :execrows
INSERT INTO deposit_candidates (
  tx_signature, wallet_address, user_id, slot, block_time, source, status, seen_at
) VALUES ($1, $2, $3, $4,
  NULLIF($7::timestamptz, '0001-01-01 00:00:00+00'::timestamptz),
  $5, 'pending', $6)
ON CONFLICT (tx_signature, wallet_address) DO NOTHING
`

type InsertDepositCandidateParams struct {
	TxSignature   string
	WalletAddress string
	UserID        uuid.UUID
	Slot          int64
	Source        string
	SeenAt        time.Time
	BlockTime     time.Time
}

func (q *Queries) InsertDepositCandidate(ctx context.Context, arg InsertDepositCandidateParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertDepositCandidate,
		arg.TxSignature,
		arg.WalletAddress,
		arg.UserID,
		arg.Slot,
		arg.Source,
		arg.SeenAt,
		arg.BlockTime,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertDepositWatchAccount = `-- name: InsertDepositWatchAccount :exec
INSERT INTO deposit_watch_accounts (
  token_account, wallet_address, canonical, state, last_amount, observed_slot,
  high_signature, high_slot, recovery_due_at
) VALUES ($1, $2, $3, $4, $5::text::numeric, $6::bigint,
  NULLIF($7::text, ''), $8::bigint, $9::timestamptz)
ON CONFLICT (token_account) DO NOTHING
`

type InsertDepositWatchAccountParams struct {
	TokenAccount  string
	WalletAddress string
	Canonical     bool
	State         string
	LastAmount    string
	ObservedSlot  int64
	HighSignature string
	HighSlot      int64
	RecoveryDueAt time.Time
}

func (q *Queries) InsertDepositWatchAccount(ctx context.Context, arg InsertDepositWatchAccountParams) error {
	_, err := q.db.Exec(ctx, insertDepositWatchAccount,
		arg.TokenAccount,
		arg.WalletAddress,
		arg.Canonical,
		arg.State,
		arg.LastAmount,
		arg.ObservedSlot,
		arg.HighSignature,
		arg.HighSlot,
		arg.RecoveryDueAt,
	)
	return err
}

const insertDepositWatchWallet = `-- name: InsertDepositWatchWallet :exec
INSERT INTO deposit_watch_wallets (wallet_address, user_id, first_seen_slot, first_seen_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (wallet_address) DO NOTHING
`

type InsertDepositWatchWalletParams struct {
	WalletAddress string
	UserID        uuid.UUID
	FirstSeenSlot int64
	FirstSeenAt   time.Time
}

func (q *Queries) InsertDepositWatchWallet(ctx context.Context, arg InsertDepositWatchWalletParams) error {
	_, err := q.db.Exec(ctx, insertDepositWatchWallet,
		arg.WalletAddress,
		arg.UserID,
		arg.FirstSeenSlot,
		arg.FirstSeenAt,
	)
	return err
}

const resolveDepositCandidate = `-- name: ResolveDepositCandidate :execrows
UPDATE deposit_candidates
SET status = $1,
    resolved_at = NULLIF($4::timestamptz, '0001-01-01T00:00:00Z'::timestamptz)
WHERE tx_signature = $2 AND wallet_address = $3 AND status = 'pending'
`

type ResolveDepositCandidateParams struct {
	Status        string
	TxSignature   string
	WalletAddress string
	ResolvedAt    time.Time
}

func (q *Queries) ResolveDepositCandidate(ctx context.Context, arg ResolveDepositCandidateParams) (int64, error) {
	result, err := q.db.Exec(ctx, resolveDepositCandidate,
		arg.Status,
		arg.TxSignature,
		arg.WalletAddress,
		arg.ResolvedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setDepositBackfill = `-- name: SetDepositBackfill :exec
UPDATE deposit_cursors
SET backfill_before_signature = $2::text,
    backfill_head_signature = $3::text,
    backfill_head_slot = $4::bigint
WHERE wallet_address = $1
`

type SetDepositBackfillParams struct {
	WalletAddress   string
	BeforeSignature string
	HeadSignature   string
	HeadSlot        int64
}

func (q *Queries) SetDepositBackfill(ctx context.Context, arg SetDepositBackfillParams) error {
	_, err := q.db.Exec(ctx, setDepositBackfill,
		arg.WalletAddress,
		arg.BeforeSignature,
		arg.HeadSignature,
		arg.HeadSlot,
	)
	return err
}

const touchDepositCursor = `-- name: TouchDepositCursor :exec
INSERT INTO deposit_cursors (wallet_address, last_signature, cursor_slot, scanned_at)
VALUES ($1, '', 0, $2)
ON CONFLICT (wallet_address) DO UPDATE SET scanned_at = EXCLUDED.scanned_at
`

type TouchDepositCursorParams struct {
	WalletAddress string
	ScannedAt     time.Time
}

func (q *Queries) TouchDepositCursor(ctx context.Context, arg TouchDepositCursorParams) error {
	_, err := q.db.Exec(ctx, touchDepositCursor, arg.WalletAddress, arg.ScannedAt)
	return err
}
