// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: withdrawals.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const confirmWithdrawal = `-- name: ConfirmWithdrawal :execrows
UPDATE withdrawals
SET status = 'confirmed', completed_at = $2::timestamptz
WHERE id = $1 AND status = 'submitted'
`

type ConfirmWithdrawalParams struct {
	ID          uuid.UUID
	CompletedAt time.Time
}

func (q *Queries) ConfirmWithdrawal(ctx context.Context, arg ConfirmWithdrawalParams) (int64, error) {
	result, err := q.db.Exec(ctx, confirmWithdrawal, arg.ID, arg.CompletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failWithdrawal = `-- name: FailWithdrawal :execrows
UPDATE withdrawals
SET status = 'failed', fail_code = $2::text, completed_at = $3::timestamptz
WHERE id = $1 AND status IN ('created', 'submitted')
`

type FailWithdrawalParams struct {
	ID          uuid.UUID
	FailCode    string
	CompletedAt time.Time
}

func (q *Queries) FailWithdrawal(ctx context.Context, arg FailWithdrawalParams) (int64, error) {
	result, err := q.db.Exec(ctx, failWithdrawal, arg.ID, arg.FailCode, arg.CompletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWithdrawal = `-- name: GetWithdrawal :one
SELECT id, user_id, amount_micros::text AS amount_micros, to_address, status,
  COALESCE(tx_signature, '')::text AS tx_signature, COALESCE(fail_code, '')::text AS fail_code,
  created_at, completed_at
FROM withdrawals
WHERE id = $1 AND user_id = $2
`

type GetWithdrawalParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetWithdrawalRow struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	AmountMicros string
	ToAddress    string
	Status       string
	TxSignature  string
	FailCode     string
	CreatedAt    time.Time
	CompletedAt  pgtype.Timestamptz
}

func (q *Queries) GetWithdrawal(ctx context.Context, arg GetWithdrawalParams) (GetWithdrawalRow, error) {
	row := q.db.QueryRow(ctx, getWithdrawal, arg.ID, arg.UserID)
	var i GetWithdrawalRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AmountMicros,
		&i.ToAddress,
		&i.Status,
		&i.TxSignature,
		&i.FailCode,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const inFlightWithdrawalMicros = `-- name: InFlightWithdrawalMicros :one
SELECT COALESCE(SUM(amount_micros), 0)::text AS micros
FROM withdrawals
WHERE user_id = $1 AND status IN ('created', 'submitted')
`

func (q *Queries) InFlightWithdrawalMicros(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, inFlightWithdrawalMicros, userID)
	var micros string
	err := row.Scan(&micros)
	return micros, err
}

const insertWithdrawal = `-- name: InsertWithdrawal :exec
INSERT INTO withdrawals (id, user_id, amount_micros, to_address, status, created_at)
VALUES ($1, $2, $5::text::numeric, $3, 'created', $4)
`

type InsertWithdrawalParams struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	ToAddress    string
	CreatedAt    time.Time
	AmountMicros string
}

func (q *Queries) InsertWithdrawal(ctx context.Context, arg InsertWithdrawalParams) error {
	_, err := q.db.Exec(ctx, insertWithdrawal,
		arg.ID,
		arg.UserID,
		arg.ToAddress,
		arg.CreatedAt,
		arg.AmountMicros,
	)
	return err
}

const listOpenWithdrawals = `-- name: ListOpenWithdrawals :many
SELECT id, status, (-amount_micros)::bigint AS amount, tx_signature, created_at
FROM withdrawals
WHERE user_id = $1 AND status <> 'confirmed'
  AND (NOT $2::bool OR (created_at, id) < ($3::timestamptz, $4::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListOpenWithdrawalsParams struct {
	UserID    uuid.UUID
	HasCursor bool
	CursorAt  time.Time
	CursorID  uuid.UUID
	RowLimit  int32
}

type ListOpenWithdrawalsRow struct {
	ID          uuid.UUID
	Status      string
	Amount      int64
	TxSignature pgtype.Text
	CreatedAt   time.Time
}

func (q *Queries) ListOpenWithdrawals(ctx context.Context, arg ListOpenWithdrawalsParams) ([]ListOpenWithdrawalsRow, error) {
	rows, err := q.db.Query(ctx, listOpenWithdrawals,
		arg.UserID,
		arg.HasCursor,
		arg.CursorAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenWithdrawalsRow
	for rows.Next() {
		var i ListOpenWithdrawalsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Amount,
			&i.TxSignature,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleCreatedWithdrawals = `-- name: ListStaleCreatedWithdrawals :many
SELECT id, user_id, amount_micros::text AS amount_micros
FROM withdrawals
WHERE status = 'created' AND created_at < $1::timestamptz
ORDER BY created_at, id
LIMIT $2
`

type ListStaleCreatedWithdrawalsParams struct {
	OlderThan time.Time
	MaxRows   int32
}

type ListStaleCreatedWithdrawalsRow struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	AmountMicros string
}

func (q *Queries) ListStaleCreatedWithdrawals(ctx context.Context, arg ListStaleCreatedWithdrawalsParams) ([]ListStaleCreatedWithdrawalsRow, error) {
	rows, err := q.db.Query(ctx, listStaleCreatedWithdrawals, arg.OlderThan, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaleCreatedWithdrawalsRow
	for rows.Next() {
		var i ListStaleCreatedWithdrawalsRow
		if err := rows.Scan(&i.ID, &i.UserID, &i.AmountMicros); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmittedWithdrawals = `-- name: ListSubmittedWithdrawals :many
SELECT id, user_id, amount_micros::text AS amount_micros, to_address, signed_tx, tx_signature,
  last_valid_block_height
FROM withdrawals
WHERE status = 'submitted'
ORDER BY submitted_at, id
LIMIT $1
`

type ListSubmittedWithdrawalsRow struct {
	ID                   uuid.UUID
	UserID               uuid.UUID
	AmountMicros         string
	ToAddress            string
	SignedTx             []byte
	TxSignature          pgtype.Text
	LastValidBlockHeight pgtype.Int8
}

func (q *Queries) ListSubmittedWithdrawals(ctx context.Context, maxRows int32) ([]ListSubmittedWithdrawalsRow, error) {
	rows, err := q.db.Query(ctx, listSubmittedWithdrawals, maxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubmittedWithdrawalsRow
	for rows.Next() {
		var i ListSubmittedWithdrawalsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AmountMicros,
			&i.ToAddress,
			&i.SignedTx,
			&i.TxSignature,
			&i.LastValidBlockHeight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWalletOutflow = `-- name: LockWalletOutflow :exec
SELECT pg_advisory_xact_lock(hashtextextended('wallet-outflow:' || $1::uuid::text, 0))
`

func (q *Queries) LockWalletOutflow(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockWalletOutflow, userID)
	return err
}

const submitWithdrawal = `-- name: SubmitWithdrawal :execrows
UPDATE withdrawals
SET status = 'submitted', signed_tx = $2::bytea, tx_signature = $3::text,
  last_valid_block_height = $4::text::bigint,
  submitted_at = $5::timestamptz
WHERE id = $1 AND status = 'created'
`

type SubmitWithdrawalParams struct {
	ID                   uuid.UUID
	SignedTx             []byte
	TxSignature          string
	LastValidBlockHeight string
	SubmittedAt          time.Time
}

func (q *Queries) SubmitWithdrawal(ctx context.Context, arg SubmitWithdrawalParams) (int64, error) {
	result, err := q.db.Exec(ctx, submitWithdrawal,
		arg.ID,
		arg.SignedTx,
		arg.TxSignature,
		arg.LastValidBlockHeight,
		arg.SubmittedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
