site_name: Monaco
site_url: https://lognorman20.github.io/monaco/
repo_url: https://github.com/lognorman20/monaco
edit_uri: edit/main/docs/
docs_dir: docs
strict: true

theme:
  name: material
  features:
    - navigation.sections
    - navigation.indexes
    - search.suggest
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Light mode

extra_css:
  - stylesheets/swagger.css

plugins:
  - search
  - render_swagger

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn
