// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type IdempotencyKey struct {
	ActorKey        string
	Key             string
	RequestHash     []byte
	Status          int16
	ResponseStatus  pgtype.Int4
	ResponseBody    []byte
	ResponseHeaders []byte
	CreatedAt       time.Time
	CompletedAt     pgtype.Timestamptz
}
