// Code generated by scripts/gen-registry. DO NOT EDIT.

package observability

func init() {
	register(
		FundingDepositDuplicate,
		FundingDepositCredited,
		FundingCandidateRecorded,
		FundingBalanceClamped,
		FundingPauseChanged,
		FundingWatchOwnTransfer,
		FundingWatchIgnored,
		FundingWatchDetected,
		FundingBounceMoved,
		FundingBounceFailed,
		FundingBounceOps,
		FundingReconcileFailed,
	)
}
