// Code generated by scripts/gen-registry. DO NOT EDIT.

package observability

func init() {
	register(
		MarketBackfillSkippedNoKey,
		MarketBackfillUnlisted,
		MarketCoinGeckoSubMicroDropped,
		MarketReconcileSkippedNoKey,
		MarketChartBackfillQueueFailed,
		MarketHistoryDisabled,
		MarketHistoryCooldown,
	)
}
