// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_tokens.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const activeTokensForUser = `-- name: ActiveTokensForUser :many
SELECT token, environment FROM device_tokens
WHERE user_id = $1 AND disabled_at IS NULL
ORDER BY last_seen_at DESC, token
`

type ActiveTokensForUserRow struct {
	Token       string
	Environment string
}

func (q *Queries) ActiveTokensForUser(ctx context.Context, userID uuid.UUID) ([]ActiveTokensForUserRow, error) {
	rows, err := q.db.Query(ctx, activeTokensForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActiveTokensForUserRow
	for rows.Next() {
		var i ActiveTokensForUserRow
		if err := rows.Scan(&i.Token, &i.Environment); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteOwnToken = `-- name: DeleteOwnToken :one
DELETE FROM device_tokens
WHERE token = $1 AND user_id = $2
RETURNING environment
`

type DeleteOwnTokenParams struct {
	Token  string
	UserID uuid.UUID
}

func (q *Queries) DeleteOwnToken(ctx context.Context, arg DeleteOwnTokenParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteOwnToken, arg.Token, arg.UserID)
	var environment string
	err := row.Scan(&environment)
	return environment, err
}

const disableToken = `-- name: DisableToken :execrows
UPDATE device_tokens SET disabled_at = $1::timestamptz
WHERE token = $2 AND disabled_at IS NULL
`

type DisableTokenParams struct {
	DisabledAt time.Time
	Token      string
}

func (q *Queries) DisableToken(ctx context.Context, arg DisableTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, disableToken, arg.DisabledAt, arg.Token)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const registerToken = `-- name: RegisterToken :exec
INSERT INTO device_tokens (id, user_id, token, environment, created_at, last_seen_at)
VALUES ($1, $2, $3, $4, $5, $5)
ON CONFLICT (token) DO UPDATE
SET user_id = excluded.user_id,
    environment = excluded.environment,
    last_seen_at = excluded.last_seen_at,
    disabled_at = NULL
`

type RegisterTokenParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Token       string
	Environment string
	CreatedAt   time.Time
}

func (q *Queries) RegisterToken(ctx context.Context, arg RegisterTokenParams) error {
	_, err := q.db.Exec(ctx, registerToken,
		arg.ID,
		arg.UserID,
		arg.Token,
		arg.Environment,
		arg.CreatedAt,
	)
	return err
}
