// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countKindSince = `-- name: CountKindSince :one
SELECT count(*) FROM notifications
WHERE user_id = $1 AND kind = $2 AND created_at >= $3
`

type CountKindSinceParams struct {
	UserID    uuid.UUID
	Kind      string
	CreatedAt time.Time
}

func (q *Queries) CountKindSince(ctx context.Context, arg CountKindSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countKindSince, arg.UserID, arg.Kind, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const eventActor = `-- name: EventActor :one
SELECT actor_type, actor_id FROM events WHERE id = $1
`

type EventActorRow struct {
	ActorType string
	ActorID   string
}

func (q *Queries) EventActor(ctx context.Context, id uuid.UUID) (EventActorRow, error) {
	row := q.db.QueryRow(ctx, eventActor, id)
	var i EventActorRow
	err := row.Scan(&i.ActorType, &i.ActorID)
	return i, err
}

const insertBroadcast = `-- name: InsertBroadcast :one
INSERT INTO notification_broadcasts (id, kind, source_event_id, recipient_count, created_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (source_event_id) DO NOTHING
RETURNING id
`

type InsertBroadcastParams struct {
	ID             uuid.UUID
	Kind           string
	SourceEventID  uuid.UUID
	RecipientCount int32
	CreatedAt      time.Time
}

func (q *Queries) InsertBroadcast(ctx context.Context, arg InsertBroadcastParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertBroadcast,
		arg.ID,
		arg.Kind,
		arg.SourceEventID,
		arg.RecipientCount,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertNotification = `-- name: InsertNotification :one
INSERT INTO notifications (
  id, broadcast_id, user_id, kind, source_event_id, title, body, data, collapse_id, state, created_at
)
VALUES (
  $1, NULLIF($2::uuid, '00000000-0000-0000-0000-000000000000'), $3,
  $4, $5, $6, $7, $8, $9,
  $10, $11
)
ON CONFLICT (source_event_id, user_id, kind) DO NOTHING
RETURNING id
`

type InsertNotificationParams struct {
	ID            uuid.UUID
	BroadcastID   uuid.UUID
	UserID        uuid.UUID
	Kind          string
	SourceEventID uuid.UUID
	Title         string
	Body          string
	Data          []byte
	CollapseID    string
	State         string
	CreatedAt     time.Time
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertNotification,
		arg.ID,
		arg.BroadcastID,
		arg.UserID,
		arg.Kind,
		arg.SourceEventID,
		arg.Title,
		arg.Body,
		arg.Data,
		arg.CollapseID,
		arg.State,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const markDelivered = `-- name: MarkDelivered :execrows
UPDATE notifications SET state = 'delivered', delivered_at = $1::timestamptz
WHERE id = $2 AND state = 'pending'
`

type MarkDeliveredParams struct {
	DeliveredAt time.Time
	ID          uuid.UUID
}

func (q *Queries) MarkDelivered(ctx context.Context, arg MarkDeliveredParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDelivered, arg.DeliveredAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNoDevice = `-- name: MarkNoDevice :execrows
UPDATE notifications SET state = 'no_device'
WHERE id = $1 AND state = 'pending'
`

func (q *Queries) MarkNoDevice(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markNoDevice, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const undeliveredForEvent = `-- name: UndeliveredForEvent :many
SELECT id, broadcast_id, user_id, kind, title, body, data, collapse_id, created_at FROM notifications
WHERE source_event_id = $1 AND state = 'pending'
ORDER BY created_at, id
`

type UndeliveredForEventRow struct {
	ID          uuid.UUID
	BroadcastID pgtype.UUID
	UserID      uuid.UUID
	Kind        string
	Title       string
	Body        string
	Data        []byte
	CollapseID  string
	CreatedAt   time.Time
}

func (q *Queries) UndeliveredForEvent(ctx context.Context, sourceEventID uuid.UUID) ([]UndeliveredForEventRow, error) {
	rows, err := q.db.Query(ctx, undeliveredForEvent, sourceEventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UndeliveredForEventRow
	for rows.Next() {
		var i UndeliveredForEventRow
		if err := rows.Scan(
			&i.ID,
			&i.BroadcastID,
			&i.UserID,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.Data,
			&i.CollapseID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
