// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_proposal.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getProposal = `-- name: GetProposal :one
SELECT
  p.id, p.cabal_id, p.proposer_id, p.kind, p.symbol, p.usdc_micros, p.token_amount, p.quote_out_amount,
  p.thesis, p.threshold, p.status, p.status_reason, p.expires_at, p.created_at,
  coalesce(mine.choice, '')::text AS my_ballot
FROM proposals AS p
LEFT JOIN votes AS mine ON mine.proposal_id = p.id AND mine.voter_id = $1
WHERE p.id = $2
`

type GetProposalParams struct {
	CallerID uuid.UUID
	ID       uuid.UUID
}

type GetProposalRow struct {
	ID             uuid.UUID
	CabalID        uuid.UUID
	ProposerID     uuid.UUID
	Kind           string
	Symbol         string
	UsdcMicros     pgtype.Int8
	TokenAmount    pgtype.Int8
	QuoteOutAmount int64
	Thesis         pgtype.Text
	Threshold      string
	Status         string
	StatusReason   pgtype.Text
	ExpiresAt      time.Time
	CreatedAt      time.Time
	MyBallot       string
}

func (q *Queries) GetProposal(ctx context.Context, arg GetProposalParams) (GetProposalRow, error) {
	row := q.db.QueryRow(ctx, getProposal, arg.CallerID, arg.ID)
	var i GetProposalRow
	err := row.Scan(
		&i.ID,
		&i.CabalID,
		&i.ProposerID,
		&i.Kind,
		&i.Symbol,
		&i.UsdcMicros,
		&i.TokenAmount,
		&i.QuoteOutAmount,
		&i.Thesis,
		&i.Threshold,
		&i.Status,
		&i.StatusReason,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.MyBallot,
	)
	return i, err
}

const proposalVoters = `-- name: ProposalVoters :many
SELECT proposal_voters.voter_id, votes.choice, votes.cast_at
FROM proposal_voters
LEFT JOIN votes USING (proposal_id, voter_id)
WHERE proposal_voters.proposal_id = $1
ORDER BY proposal_voters.voter_id
`

type ProposalVotersRow struct {
	VoterID uuid.UUID
	Choice  pgtype.Text
	CastAt  pgtype.Timestamptz
}

func (q *Queries) ProposalVoters(ctx context.Context, proposalID uuid.UUID) ([]ProposalVotersRow, error) {
	rows, err := q.db.Query(ctx, proposalVoters, proposalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProposalVotersRow
	for rows.Next() {
		var i ProposalVotersRow
		if err := rows.Scan(&i.VoterID, &i.Choice, &i.CastAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
