// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proposed_mints.sql

package sqlc

import (
	"context"
)

const proposedMints = `-- name: ProposedMints :many
SELECT DISTINCT mint FROM proposals WHERE status IN ('open', 'passed') ORDER BY mint
`

func (q *Queries) ProposedMints(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, proposedMints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var mint string
		if err := rows.Scan(&mint); err != nil {
			return nil, err
		}
		items = append(items, mint)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
