// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dev_x_links.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteDevXLink = `-- name: DeleteDevXLink :exec
DELETE FROM dev_x_links WHERE user_id = $1
`

func (q *Queries) DeleteDevXLink(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDevXLink, userID)
	return err
}

const devXLinkByPrivyUserID = `-- name: DevXLinkByPrivyUserID :one
SELECT d.x_user_id, d.x_username
FROM dev_x_links d
JOIN users u ON u.id = d.user_id
WHERE u.privy_user_id = $1
`

type DevXLinkByPrivyUserIDRow struct {
	XUserID   string
	XUsername string
}

func (q *Queries) DevXLinkByPrivyUserID(ctx context.Context, privyUserID string) (DevXLinkByPrivyUserIDRow, error) {
	row := q.db.QueryRow(ctx, devXLinkByPrivyUserID, privyUserID)
	var i DevXLinkByPrivyUserIDRow
	err := row.Scan(&i.XUserID, &i.XUsername)
	return i, err
}

const upsertDevXLink = `-- name: UpsertDevXLink :exec
INSERT INTO dev_x_links (user_id, x_user_id, x_username, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE SET x_user_id = EXCLUDED.x_user_id, x_username = EXCLUDED.x_username
`

type UpsertDevXLinkParams struct {
	UserID    uuid.UUID
	XUserID   string
	XUsername string
	Now       time.Time
}

func (q *Queries) UpsertDevXLink(ctx context.Context, arg UpsertDevXLinkParams) error {
	_, err := q.db.Exec(ctx, upsertDevXLink,
		arg.UserID,
		arg.XUserID,
		arg.XUsername,
		arg.Now,
	)
	return err
}
