// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nudges.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const markNudged = `-- name: MarkNudged :many
UPDATE users SET last_nudged_at = $1::timestamptz, nudge_count = nudge_count + 1
WHERE id = ANY($2::uuid[])
  AND auth_state IN ('AWAITING_PHONE', 'AWAITING_SOCIALS')
  AND account_status = 'active' AND deleted_at IS NULL
  AND auth_state_changed_at <= $3::timestamptz
  AND (last_nudged_at IS NULL OR last_nudged_at <= $4::timestamptz)
  AND nudge_count < $5::smallint
RETURNING id, auth_state, nudge_count
`

type MarkNudgedParams struct {
	Now           time.Time
	Ids           []uuid.UUID
	ChangedBefore time.Time
	NudgedBefore  time.Time
	MaxNudges     int16
}

type MarkNudgedRow struct {
	ID         uuid.UUID
	AuthState  string
	NudgeCount int16
}

func (q *Queries) MarkNudged(ctx context.Context, arg MarkNudgedParams) ([]MarkNudgedRow, error) {
	rows, err := q.db.Query(ctx, markNudged,
		arg.Now,
		arg.Ids,
		arg.ChangedBefore,
		arg.NudgedBefore,
		arg.MaxNudges,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarkNudgedRow
	for rows.Next() {
		var i MarkNudgedRow
		if err := rows.Scan(&i.ID, &i.AuthState, &i.NudgeCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nudgeCandidates = `-- name: NudgeCandidates :many
SELECT id FROM users
WHERE auth_state IN ('AWAITING_PHONE', 'AWAITING_SOCIALS')
  AND account_status = 'active' AND deleted_at IS NULL
  AND auth_state_changed_at <= $1::timestamptz
  AND (last_nudged_at IS NULL OR last_nudged_at <= $2::timestamptz)
  AND nudge_count < $3::smallint
  AND id > $4::uuid
ORDER BY id
LIMIT $5
`

type NudgeCandidatesParams struct {
	ChangedBefore time.Time
	NudgedBefore  time.Time
	MaxNudges     int16
	After         uuid.UUID
	Page          int32
}

func (q *Queries) NudgeCandidates(ctx context.Context, arg NudgeCandidatesParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, nudgeCandidates,
		arg.ChangedBefore,
		arg.NudgedBefore,
		arg.MaxNudges,
		arg.After,
		arg.Page,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
