// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: qa_pot.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const qAPotDestination = `-- name: QAPotDestination :one
SELECT address FROM user_wallets WHERE user_id = $1
`

func (q *Queries) QAPotDestination(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, qAPotDestination, userID)
	var address string
	err := row.Scan(&address)
	return address, err
}
