// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cash_out_payouts.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cashOutPayoutJob = `-- name: CashOutPayoutJob :one
SELECT j.id, j.cabal_id, j.user_id, j.share_units::text AS share_units, j.returned_units::text AS returned_units,
  j.payout_micros::text AS payout_micros, j.slice_micros::text AS slice_micros, j.sell_usdc_micros > 0 AS selling,
  j.status, coalesce(p.attempt, 0)::smallint AS attempt, coalesce(p.signature, '')::text AS signature,
  coalesce(p.signed_tx, '\x'::bytea)::bytea AS signed_tx, coalesce(p.status, '')::text AS payout_status,
  coalesce(p.last_valid_block_height, 0)::bigint AS last_valid_block_height
FROM cash_out_jobs AS j
LEFT JOIN LATERAL (
  SELECT attempt, signature, signed_tx, status, last_valid_block_height FROM cash_out_payouts
  WHERE job_id = j.id ORDER BY attempt DESC LIMIT 1
) AS p ON true
WHERE j.id = $1::uuid
`

type CashOutPayoutJobRow struct {
	ID                   uuid.UUID
	CabalID              uuid.UUID
	UserID               uuid.UUID
	ShareUnits           string
	ReturnedUnits        string
	PayoutMicros         string
	SliceMicros          string
	Selling              bool
	Status               string
	Attempt              int16
	Signature            string
	SignedTx             []byte
	PayoutStatus         string
	LastValidBlockHeight int64
}

func (q *Queries) CashOutPayoutJob(ctx context.Context, id uuid.UUID) (CashOutPayoutJobRow, error) {
	row := q.db.QueryRow(ctx, cashOutPayoutJob, id)
	var i CashOutPayoutJobRow
	err := row.Scan(
		&i.ID,
		&i.CabalID,
		&i.UserID,
		&i.ShareUnits,
		&i.ReturnedUnits,
		&i.PayoutMicros,
		&i.SliceMicros,
		&i.Selling,
		&i.Status,
		&i.Attempt,
		&i.Signature,
		&i.SignedTx,
		&i.PayoutStatus,
		&i.LastValidBlockHeight,
	)
	return i, err
}

const cashOutPayoutsDue = `-- name: CashOutPayoutsDue :many
SELECT j.id
FROM cash_out_jobs AS j
LEFT JOIN LATERAL (
  SELECT status, created_at FROM cash_out_payouts WHERE job_id = j.id ORDER BY attempt DESC LIMIT 1
) AS p ON true
WHERE (j.status = 'started' AND j.sell_usdc_micros = 0 AND j.created_at < $1::timestamptz)
  OR (j.status = 'paying' AND (p.status IS NULL OR p.status IN ('expired', 'failed')
    OR p.created_at < $1::timestamptz))
ORDER BY j.updated_at, j.id
LIMIT $2::integer
`

type CashOutPayoutsDueParams struct {
	StaleBefore time.Time
	MaxRows     int32
}

func (q *Queries) CashOutPayoutsDue(ctx context.Context, arg CashOutPayoutsDueParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, cashOutPayoutsDue, arg.StaleBefore, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const endCashOutJob = `-- name: EndCashOutJob :execrows
UPDATE cash_out_jobs
SET status = $1::text, result_code = coalesce(NULLIF($2::text, ''), result_code),
  updated_at = $3::timestamptz
WHERE id = $4::uuid AND status = $5::text
`

type EndCashOutJobParams struct {
	ToStatus   string
	ResultCode string
	At         time.Time
	ID         uuid.UUID
	FromStatus string
}

func (q *Queries) EndCashOutJob(ctx context.Context, arg EndCashOutJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, endCashOutJob,
		arg.ToStatus,
		arg.ResultCode,
		arg.At,
		arg.ID,
		arg.FromStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failUnpairedUserTransfer = `-- name: FailUnpairedUserTransfer :execrows
UPDATE user_txns SET status = 'failed'
WHERE transfer_id = $1::uuid AND status = 'pending'
  AND NOT EXISTS (SELECT 1 FROM cabal_txns WHERE transfer_id = $1::uuid)
`

func (q *Queries) FailUnpairedUserTransfer(ctx context.Context, transferID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, failUnpairedUserTransfer, transferID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertCashOutPayout = `-- name: InsertCashOutPayout :execrows
INSERT INTO cash_out_payouts (job_id, attempt, signature, signed_tx, last_valid_block_height, status, created_at)
VALUES ($1::uuid, $2::smallint, $3::text,
  $4::bytea, $5::text::bigint, 'signed', $6::timestamptz)
ON CONFLICT DO NOTHING
`

type InsertCashOutPayoutParams struct {
	JobID                uuid.UUID
	Attempt              int16
	Signature            string
	SignedTx             []byte
	LastValidBlockHeight string
	At                   time.Time
}

func (q *Queries) InsertCashOutPayout(ctx context.Context, arg InsertCashOutPayoutParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertCashOutPayout,
		arg.JobID,
		arg.Attempt,
		arg.Signature,
		arg.SignedTx,
		arg.LastValidBlockHeight,
		arg.At,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const moveCashOutPayout = `-- name: MoveCashOutPayout :execrows
UPDATE cash_out_payouts SET status = $1::text
WHERE job_id = $2::uuid AND attempt = $3::smallint
  AND status = ANY($4::text[])
`

type MoveCashOutPayoutParams struct {
	ToStatus     string
	JobID        uuid.UUID
	Attempt      int16
	FromStatuses []string
}

func (q *Queries) MoveCashOutPayout(ctx context.Context, arg MoveCashOutPayoutParams) (int64, error) {
	result, err := q.db.Exec(ctx, moveCashOutPayout,
		arg.ToStatus,
		arg.JobID,
		arg.Attempt,
		arg.FromStatuses,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
