package main

import (
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/monaco/monaco/apps/backend/internal/testkit"
)

func TestMain(m *testing.M) {
	testkit.Main(m, testkit.NoDB(), testkit.WithChild(main))
}

func writeTree(t *testing.T, files map[string]string) string {
	t.Helper()
	root := t.TempDir()
	for rel, body := range files {
		path := filepath.Join(root, rel)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return root
}

func read(t *testing.T, root, rel string) string {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(root, rel))
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}

const moduleAlpha = header + "\npackage main\n\n" +
	"import (\n\t\"example.com/app/internal/modules/alpha\"\n\t\"example.com/app/internal/platform/module\"\n)\n\n" +
	"func init() {\n\tregistered.Add(func(d module.Deps) module.Module { return alpha.New(d) })\n}\n"

const moduleGammaTool = header + "\npackage main\n\n" +
	"import (\n\t\"example.com/app/internal/modules/gamma\"\n\t\"example.com/app/internal/platform/module\"\n" +
	"\t\"example.com/app/internal/tools/ops/replay\"\n)\n\n" +
	"func init() {\n\tregistered.Add(func(d module.Deps) module.Module { return gamma.New(d) })\n" +
	"\treplay.RegisterLedgerCheck(gamma.LedgerCheck)\n}\n"

func sampleTree(t *testing.T) string {
	t.Helper()
	return writeTree(t, map[string]string{
		"go.mod": "module example.com/app\n",
		"internal/platform/observability/msgs_boot.go": "package observability\n\nconst limit = 1\n\nvar (\n" +
			"\tBootA = Msg{Name: \"boot.a\"}\n\tBootB = Msg{Name: \"boot.b\"}\n\tnotAMsg = 3\n)\n",
		"internal/platform/observability/msgs_none.go":   "package observability\n\nvar x = 1\n",
		"internal/platform/observability/msgs_x_test.go": "package observability\n\nvar T = Msg{}\n",
		"cmd/monacoctl/report.go": "package main\n\n" +
			"func toolTestReport(_ toolEnv) tool { return nil }\n" +
			"func toolWrongArgs(n int) tool { return nil }\n" +
			"func helper(_ toolEnv) tool { return nil }\n" +
			"func (r rec) toolMethod(_ toolEnv) tool { return nil }\n",
		"cmd/monacoctl/plain.go":                "package main\n\nfunc plain() {}\n",
		"cmd/worker/api.gen.go":                 "// Code generated by oapi-codegen. DO NOT EDIT.\n\npackage main\n",
		"cmd/worker/consumers_gone.gen.go":      header + "\npackage main\n",
		"cmd/api/module_gone.gen.go":            header + "\npackage main\n",
		"internal/modules/alpha/module.go":      "package alpha\n\nfunc New() {}\n\nfunc (M) LedgerCheck() {}\n",
		"internal/modules/gamma/module.go":      "package gamma\n\nfunc New() {}\n\nfunc LedgerCheck() {}\n",
		"internal/modules/alpha/module_test.go": "package alpha\n",
		"internal/modules/beta/beta.go":         "package beta\n\nfunc Consumers() {}\n",
		"internal/modules/README.md":            "not a module\n",
	})
}

func TestGenerate_writesOneCompanionPerRegistrationFileAndDropsStaleOnes(t *testing.T) {
	t.Parallel()
	root := sampleTree(t)
	for range 2 {
		if err := generate(root); err != nil {
			t.Fatal(err)
		}
	}
	for rel, want := range map[string]string{
		"internal/platform/observability/msgs_boot.gen.go": header + "\npackage observability\n\n" +
			"func init() {\n\tregister(\n\t\tBootA,\n\t\tBootB,\n\t)\n}\n",
		"cmd/monacoctl/report.gen.go": header + "\npackage main\n\n" +
			"func init() {\n\tregisterTool(\"test-report\", toolTestReport)\n}\n",
		"cmd/api/module_alpha.gen.go":       moduleAlpha,
		"cmd/monacoctl/module_alpha.gen.go": moduleAlpha,
		"cmd/worker/module_alpha.gen.go":    moduleAlpha,
		"cmd/api/module_gamma.gen.go":       strings.ReplaceAll(moduleAlpha, "alpha", "gamma"),
		"cmd/monacoctl/module_gamma.gen.go": moduleGammaTool,
	} {
		if got := read(t, root, rel); got != want {
			t.Errorf("%s =\n%s\nwant\n%s", rel, got, want)
		}
	}
	for _, rel := range []string{
		"internal/platform/observability/msgs_none.gen.go", "cmd/monacoctl/plain.gen.go",
		"cmd/worker/module_beta.gen.go", "cmd/worker/consumers_gone.gen.go", "cmd/api/module_gone.gen.go",
	} {
		if _, err := os.Stat(filepath.Join(root, rel)); !os.IsNotExist(err) {
			t.Errorf("%s exists (%v), want no companion", rel, err)
		}
	}
	if read(t, root, "cmd/worker/api.gen.go") == "" {
		t.Error("removed a generated file another generator owns")
	}
	if got, err := drift(root); err != nil || len(got) != 0 {
		t.Fatalf("drift after generate = %v, %v, want none", got, err)
	}
}

func TestDrift_namesHandEditedMissingAndStaleCompanions(t *testing.T) {
	t.Parallel()
	root := sampleTree(t)
	if err := generate(root); err != nil {
		t.Fatal(err)
	}
	edits := map[string]string{
		"cmd/monacoctl/report.gen.go":                "hand edit\n",
		"internal/platform/observability/msgs_db.go": "package observability\n\nvar DBX = Msg{Name: \"db.x\"}\n",
		"cmd/worker/consumers_old.gen.go":            header + "\npackage main\n",
	}
	for rel, body := range edits {
		if err := os.WriteFile(filepath.Join(root, rel), []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	got, err := drift(root)
	want := []string{
		"cmd/monacoctl/report.gen.go",
		"internal/platform/observability/msgs_db.gen.go",
		"cmd/worker/consumers_old.gen.go (stale)",
	}
	if err != nil || !slices.Equal(got, want) {
		t.Fatalf("drift = %q, %v, want %q", got, err, want)
	}
}

func TestGenerate_rejectsTwoFactoriesForOneToolName(t *testing.T) {
	t.Parallel()
	factory := "package main\n\nfunc toolTestReport(_ toolEnv) tool { return nil }\n"
	root := writeTree(
		t,
		map[string]string{"go.mod": "module m\n", "cmd/monacoctl/a.go": factory, "cmd/monacoctl/b.go": factory},
	)
	err := generate(root)
	if err == nil || !strings.Contains(err.Error(), `tool "test-report" is declared by both`) {
		t.Fatalf("generate = %v, want a duplicate tool error", err)
	}
}

func TestGenerate_namesTheInputItCannotReadParseOrWrite(t *testing.T) {
	t.Parallel()
	for name, tc := range map[string]struct {
		files    map[string]string
		readOnly string
		want     string
	}{
		"missing go.mod": {map[string]string{}, "", "read go.mod: "},
		"modules is a file": {
			map[string]string{"go.mod": "module m\n", "internal/modules": "x"}, "", "list modules: ",
		},
		"broken msgs file": {
			map[string]string{"go.mod": "module m\n", "internal/platform/observability/msgs_a.go": "package"},
			"", "parse ",
		},
		"broken module file": {
			map[string]string{"go.mod": "module m\n", "internal/modules/alpha/a.go": "package"}, "", "parse ",
		},
		"tools dir is a file":  {map[string]string{"go.mod": "module m\n", "cmd/monacoctl": "x"}, "", "list cmd/monacoctl: "},
		"worker dir is a file": {map[string]string{"go.mod": "module m\n", "cmd/worker": "x"}, "", "list cmd/worker: "},
		"flows dir is a file": {
			map[string]string{"go.mod": "module m\n", "internal/testkit/flows": "x"}, "", "list internal/testkit/flows: ",
		},
		"unreadable owned file": {
			map[string]string{"go.mod": "module m\n", "cmd/worker/x.gen.go/keep": ""}, "", "read ",
		},
		"read-only companion": {
			map[string]string{
				"go.mod":                 "module m\n",
				"cmd/monacoctl/a.go":     "package main\n\nfunc toolA(_ toolEnv) tool { return nil }\n",
				"cmd/monacoctl/a.gen.go": "stale\n",
			},
			"cmd/monacoctl/a.gen.go", "write cmd/monacoctl/a.gen.go: ",
		},
		"stale file in a read-only dir": {
			map[string]string{"go.mod": "module m\n", "cmd/worker/consumers_x.gen.go": header},
			"cmd/worker", "remove stale cmd/worker/consumers_x.gen.go: ",
		},
	} {
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			root := writeTree(t, tc.files)
			if tc.readOnly != "" {
				freeze(t, filepath.Join(root, tc.readOnly))
			}
			if err := generate(root); err == nil || !strings.HasPrefix(err.Error(), tc.want) {
				t.Fatalf("generate = %v, want an error starting %q", err, tc.want)
			}
		})
	}
}

func TestDrift_failsWhereGenerateWould(t *testing.T) {
	t.Parallel()
	for _, files := range []map[string]string{
		{},
		{"go.mod": "module m\n", "cmd/worker": "x"},
	} {
		if got, err := drift(writeTree(t, files)); err == nil {
			t.Fatalf("drift = %v, nil, want an error", got)
		}
	}
}

func TestMain_generatesInTheWorkingDirOrExitsOneNamingTheError(t *testing.T) {
	t.Parallel()
	root := sampleTree(t)
	cmd := testkit.MainCommand(t, nil)
	cmd.Dir = root
	if out, err := cmd.CombinedOutput(); err != nil || len(out) != 0 {
		t.Fatalf("gen-registry in %s = %v %q", root, err, out)
	}
	if got, err := drift(root); err != nil || len(got) != 0 {
		t.Fatalf("drift after running main = %v, %v", got, err)
	}
	failing := testkit.MainCommand(t, nil, filepath.Join(root, "missing"))
	out, _ := failing.CombinedOutput()
	if code := failing.ProcessState.ExitCode(); code != 1 ||
		!strings.HasPrefix(string(out), "gen-registry: read go.mod: ") {
		t.Fatalf("gen-registry on a missing dir = %d %q", code, out)
	}
}

const flowScriptsF01a = header + "\npackage flows\n\n" +
	"func (defined) ScriptsF01a() map[string]Script {\n\treturn map[string]Script{\n" +
	"\t\t\"F01aSetHandleOK\":    F01aSetHandleOK,\n\t\t\"F01aSetHandleTaken\": F01aSetHandleTaken,\n\t}\n}\n"

func TestGenerate_writesOneScriptsCompanionPerFlowFile(t *testing.T) {
	t.Parallel()
	for name, tc := range map[string]struct {
		files   map[string]string
		want    map[string]string
		missing []string
	}{
		"a flow file gets its scripts": {
			files: map[string]string{
				"internal/testkit/flows/f01a.go": "package flows\n\n" +
					"func F01aSetHandleOK(s *scenario.Scenario) {}\n" +
					"func F01aSetHandleTaken(*scenario.Scenario) {}\n" +
					"func f01aHelper(s *scenario.Scenario) {}\n" +
					"func (defined) F01aMethod(s *scenario.Scenario) {}\n",
			},
			want: map[string]string{"internal/testkit/flows/f01a.gen.go": flowScriptsF01a},
		},
		"a file with no scripts gets no companion": {
			files: map[string]string{
				"internal/testkit/flows/scripts.go":  "package flows\n\nfunc Scripts() {}\n",
				"internal/testkit/flows/f02_test.go": "package flows\n\nfunc F02X(s *scenario.Scenario) {}\n",
			},
			missing: []string{"internal/testkit/flows/scripts.gen.go", "internal/testkit/flows/f02_test.gen.go"},
		},
		"a companion whose flow file is gone is removed": {
			files: map[string]string{
				"internal/testkit/flows/f09.gen.go":   header + "\npackage flows\n",
				"internal/testkit/flows/other.gen.go": "// Code generated by another tool. DO NOT EDIT.\n",
			},
			want:    map[string]string{"internal/testkit/flows/other.gen.go": "// Code generated by another tool. DO NOT EDIT.\n"},
			missing: []string{"internal/testkit/flows/f09.gen.go"},
		},
	} {
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			tc.files["go.mod"] = "module m\n"
			root := writeTree(t, tc.files)
			if err := generate(root); err != nil {
				t.Fatal(err)
			}
			expectFiles(t, root, tc.want, tc.missing)
		})
	}
}

func expectFiles(t *testing.T, root string, want map[string]string, missing []string) {
	t.Helper()
	for rel, body := range want {
		if got := read(t, root, rel); got != body {
			t.Errorf("%s =\n%s\nwant\n%s", rel, got, body)
		}
	}
	for _, rel := range missing {
		if _, err := os.Stat(filepath.Join(root, rel)); !os.IsNotExist(err) {
			t.Errorf("%s exists (%v), want no companion", rel, err)
		}
	}
}

func TestGenerate_rejectsAFlowScriptNameWithTheWrongSignature(t *testing.T) {
	t.Parallel()
	const want = "internal/testkit/flows/f01.go: F01Bad is named like a flow script but is not func(*scenario.Scenario)"
	for name, decl := range map[string]string{
		"an int parameter":       "func F01Bad(n int) {}",
		"two parameters":         "func F01Bad(a, b *scenario.Scenario) {}",
		"a result":               "func F01Bad(s *scenario.Scenario) error { return nil }",
		"a value parameter":      "func F01Bad(s scenario.Scenario) {}",
		"another package":        "func F01Bad(s *other.Scenario) {}",
		"another scenario type":  "func F01Bad(s *scenario.Step) {}",
		"an unqualified pointer": "func F01Bad(s *Scenario) {}",
		"no parameters":          "func F01Bad() {}",
	} {
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			root := writeTree(t, map[string]string{
				"go.mod":                        "module m\n",
				"internal/testkit/flows/f01.go": "package flows\n\n" + decl + "\n",
			})
			if err := generate(root); err == nil || err.Error() != want {
				t.Fatalf("generate = %v, want %q", err, want)
			}
		})
	}
}

func TestGenerate_namesAFlowFileWhoseStemIsNotAGoName(t *testing.T) {
	t.Parallel()
	root := writeTree(t, map[string]string{
		"go.mod":                        "module m\n",
		"internal/testkit/flows/f-1.go": "package flows\n\nfunc F01OK(s *scenario.Scenario) {}\n",
	})
	if err := generate(
		root,
	); err == nil ||
		!strings.HasPrefix(err.Error(), "format internal/testkit/flows/f-1.gen.go: ") {
		t.Fatalf("generate = %v, want a format error naming the companion", err)
	}
}

func TestRepo_generatedRegistrationsMatchTheirSources(t *testing.T) {
	t.Parallel()
	got, err := drift("../..")
	if err != nil {
		t.Fatal(err)
	}
	if len(got) > 0 {
		t.Fatalf("generated registrations are out of date or hand-edited; run go generate ./...:\n%s",
			strings.Join(got, "\n"))
	}
}
