// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feed_consumer.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const advanceFeedProposal = `-- name: AdvanceFeedProposal :one
WITH moved AS (
  UPDATE feed_objects
  SET status = $2::text, payload = payload || $3::jsonb, updated_at = $4
  WHERE ref_type = 'proposals' AND ref_id = $1::uuid AND kind = 'proposal'
    AND status = ANY($5::text[])
  RETURNING 1
)
SELECT
  (SELECT count(*) FROM moved)::int AS moved,
  EXISTS(
    SELECT 1 FROM feed_objects WHERE ref_type = 'proposals' AND ref_id = $1::uuid AND kind = 'proposal'
  ) AS found
`

type AdvanceFeedProposalParams struct {
	ProposalID   uuid.UUID
	ToStatus     string
	Patch        []byte
	At           time.Time
	FromStatuses []string
}

type AdvanceFeedProposalRow struct {
	Moved int32
	Found bool
}

func (q *Queries) AdvanceFeedProposal(ctx context.Context, arg AdvanceFeedProposalParams) (AdvanceFeedProposalRow, error) {
	row := q.db.QueryRow(ctx, advanceFeedProposal,
		arg.ProposalID,
		arg.ToStatus,
		arg.Patch,
		arg.At,
		arg.FromStatuses,
	)
	var i AdvanceFeedProposalRow
	err := row.Scan(&i.Moved, &i.Found)
	return i, err
}

const deleteFeedMembership = `-- name: DeleteFeedMembership :execrows
INSERT INTO feed_memberships (cabal_id, user_id, joined_at, event_id, active)
VALUES ($1, $2, $3, $4, false)
ON CONFLICT (cabal_id, user_id) DO UPDATE SET
  event_id = excluded.event_id,
  active = false
WHERE feed_memberships.event_id < excluded.event_id
`

type DeleteFeedMembershipParams struct {
	CabalID uuid.UUID
	UserID  uuid.UUID
	At      time.Time
	EventID uuid.UUID
}

func (q *Queries) DeleteFeedMembership(ctx context.Context, arg DeleteFeedMembershipParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFeedMembership,
		arg.CabalID,
		arg.UserID,
		arg.At,
		arg.EventID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const feedCabalExists = `-- name: FeedCabalExists :one
SELECT EXISTS(SELECT 1 FROM feed_cabals WHERE cabal_id = $1)
`

func (q *Queries) FeedCabalExists(ctx context.Context, cabalID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, feedCabalExists, cabalID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const feedCabalName = `-- name: FeedCabalName :one
SELECT name FROM feed_cabals WHERE cabal_id = $1
`

func (q *Queries) FeedCabalName(ctx context.Context, cabalID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, feedCabalName, cabalID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const insertFeedConsumerItem = `-- name: InsertFeedConsumerItem :exec
INSERT INTO feed_objects (
  id, kind, ref_type, ref_id, cabal_id, cabal_name, actor_id, asset_id, symbol, title, payload, status,
  created_at, updated_at
)
VALUES (
  $1, $2, $3, $4, $5, $6,
  $7, $8, $9, $10, $11,
  $12, $13, $13
)
ON CONFLICT (ref_type, ref_id, kind) DO NOTHING
`

type InsertFeedConsumerItemParams struct {
	ID        uuid.UUID
	Kind      string
	RefType   string
	RefID     uuid.UUID
	CabalID   pgtype.UUID
	CabalName pgtype.Text
	ActorID   pgtype.UUID
	AssetID   pgtype.UUID
	Symbol    pgtype.Text
	Title     string
	Payload   []byte
	Status    pgtype.Text
	At        time.Time
}

func (q *Queries) InsertFeedConsumerItem(ctx context.Context, arg InsertFeedConsumerItemParams) error {
	_, err := q.db.Exec(ctx, insertFeedConsumerItem,
		arg.ID,
		arg.Kind,
		arg.RefType,
		arg.RefID,
		arg.CabalID,
		arg.CabalName,
		arg.ActorID,
		arg.AssetID,
		arg.Symbol,
		arg.Title,
		arg.Payload,
		arg.Status,
		arg.At,
	)
	return err
}

const upsertFeedCabal = `-- name: UpsertFeedCabal :exec
INSERT INTO feed_cabals (cabal_id, name, updated_at)
VALUES ($1, $2, $3)
ON CONFLICT (cabal_id) DO UPDATE SET name = excluded.name, updated_at = excluded.updated_at
`

type UpsertFeedCabalParams struct {
	CabalID uuid.UUID
	Name    string
	At      time.Time
}

func (q *Queries) UpsertFeedCabal(ctx context.Context, arg UpsertFeedCabalParams) error {
	_, err := q.db.Exec(ctx, upsertFeedCabal, arg.CabalID, arg.Name, arg.At)
	return err
}

const upsertFeedMembership = `-- name: UpsertFeedMembership :execrows
INSERT INTO feed_memberships (cabal_id, user_id, joined_at, event_id, active)
VALUES ($1, $2, $3, $4, true)
ON CONFLICT (cabal_id, user_id) DO UPDATE SET
  joined_at = excluded.joined_at,
  event_id = excluded.event_id,
  active = true
WHERE feed_memberships.event_id < excluded.event_id
`

type UpsertFeedMembershipParams struct {
	CabalID  uuid.UUID
	UserID   uuid.UUID
	JoinedAt time.Time
	EventID  uuid.UUID
}

func (q *Queries) UpsertFeedMembership(ctx context.Context, arg UpsertFeedMembershipParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertFeedMembership,
		arg.CabalID,
		arg.UserID,
		arg.JoinedAt,
		arg.EventID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
