// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: follows.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertFollow = `-- name: InsertFollow :one
INSERT INTO follows (id, follower_id, followee_id, source, created_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (follower_id, followee_id) WHERE deleted_at IS NULL DO NOTHING
RETURNING id
`

type InsertFollowParams struct {
	ID         uuid.UUID
	FollowerID uuid.UUID
	FolloweeID uuid.UUID
	Source     string
	CreatedAt  time.Time
}

func (q *Queries) InsertFollow(ctx context.Context, arg InsertFollowParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertFollow,
		arg.ID,
		arg.FollowerID,
		arg.FolloweeID,
		arg.Source,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const removeFollow = `-- name: RemoveFollow :one
UPDATE follows SET deleted_at = $3::timestamptz
WHERE follower_id = $1 AND followee_id = $2 AND deleted_at IS NULL
RETURNING id
`

type RemoveFollowParams struct {
	FollowerID uuid.UUID
	FolloweeID uuid.UUID
	RemovedAt  time.Time
}

func (q *Queries) RemoveFollow(ctx context.Context, arg RemoveFollowParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, removeFollow, arg.FollowerID, arg.FolloweeID, arg.RemovedAt)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
