// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Asset struct {
	ID               uuid.UUID
	Symbol           string
	Mint             string
	Decimals         int16
	Issuer           string
	Kind             string
	DisplayName      string
	LogoUrl          pgtype.Text
	UiMultiplierNum  int64
	UiMultiplierDen  int64
	IssuerTradable   bool
	TradableOverride pgtype.Bool
	PopularRank      pgtype.Int2
	CompanyKey       string
	FirstSeenAt      time.Time
	UpdatedAt        time.Time
	ChainCheckedAt   pgtype.Timestamptz
}

type AssetPriceMove struct {
	AssetID      uuid.UUID
	ThresholdBps int32
	TradingDay   pgtype.Date
	EventID      uuid.UUID
	CreatedAt    time.Time
}

type Cabal struct {
	ID                    uuid.UUID
	Name                  string
	PictureUrl            pgtype.Text
	CreatorID             uuid.UUID
	JoinMode              string
	VoterMode             string
	Threshold             string
	ProposalExpirySeconds int32
	SlippageBps           int32
	InviteCode            string
	Status                string
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type CabalAccessRequest struct {
	ID        uuid.UUID
	CabalID   uuid.UUID
	UserID    uuid.UUID
	Direction string
	InvitedBy pgtype.UUID
	Status    string
	ExpiresAt pgtype.Timestamptz
	DecidedBy pgtype.UUID
	CreatedAt time.Time
	DecidedAt pgtype.Timestamptz
}

type CabalMember struct {
	CabalID  uuid.UUID
	UserID   uuid.UUID
	Role     string
	CanVote  bool
	JoinedAt time.Time
}

type CabalPosition struct {
	CabalID         uuid.UUID
	Asset           string
	Units           pgtype.Numeric
	CostBasisMicros pgtype.Numeric
	UpdatedAt       time.Time
}

type CabalTxn struct {
	ID          uuid.UUID
	CabalID     uuid.UUID
	Kind        string
	Status      string
	SwapID      pgtype.UUID
	TransferID  pgtype.UUID
	TxSignature pgtype.Text
	CreatedAt   time.Time
}

type CabalTxnEntry struct {
	TxnID   uuid.UUID
	Seq     int16
	Account string
	Asset   string
	Amount  int64
}

type DeviceToken struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Token       string
	Environment string
	CreatedAt   time.Time
	LastSeenAt  time.Time
	DisabledAt  pgtype.Timestamptz
}

type Event struct {
	ID            uuid.UUID
	AggregateType string
	AggregateID   uuid.UUID
	Type          string
	Payload       []byte
	ActorType     string
	ActorID       string
	TraceParent   pgtype.Text
	CreatedAt     time.Time
	PublishedAt   pgtype.Timestamptz
}

type EventDelivery struct {
	Handler   string
	EventID   uuid.UUID
	Code      string
	HandledAt time.Time
}

type Follow struct {
	ID         uuid.UUID
	FollowerID uuid.UUID
	FolloweeID uuid.UUID
	Source     string
	CreatedAt  time.Time
	DeletedAt  pgtype.Timestamptz
}

type IdempotencyKey struct {
	ActorKey        string
	Key             string
	RequestHash     []byte
	Status          int16
	ResponseStatus  pgtype.Int4
	ResponseBody    []byte
	ResponseHeaders []byte
	CreatedAt       time.Time
	CompletedAt     pgtype.Timestamptz
}

type Notification struct {
	ID            uuid.UUID
	BroadcastID   pgtype.UUID
	UserID        uuid.UUID
	Kind          string
	SourceEventID uuid.UUID
	Title         string
	Body          string
	Data          []byte
	CollapseID    string
	State         string
	CreatedAt     time.Time
	DeliveredAt   pgtype.Timestamptz
}

type NotificationBroadcast struct {
	ID             uuid.UUID
	Kind           string
	SourceEventID  uuid.UUID
	RecipientCount int32
	CreatedAt      time.Time
}

type PricePoint struct {
	Mint        string
	Ts          time.Time
	PriceMicros int64
	Source      string
}

type Proposal struct {
	ID             uuid.UUID
	CabalID        uuid.UUID
	ProposerID     uuid.UUID
	Kind           string
	Symbol         string
	Mint           string
	UsdcMicros     pgtype.Int8
	TokenAmount    pgtype.Int8
	Thesis         pgtype.Text
	QuoteOutAmount int64
	Status         string
	StatusReason   pgtype.Text
	VoidReason     pgtype.Text
	ExpiresAt      time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type ProposalVoter struct {
	ProposalID uuid.UUID
	VoterID    uuid.UUID
}

type RateLimitBucket struct {
	Key         string
	TokensMilli int64
	UpdatedAt   time.Time
}

type Swap struct {
	ID               uuid.UUID
	SourceKind       string
	SourceID         uuid.UUID
	CabalID          uuid.UUID
	TreasuryAddress  string
	Action           string
	Symbol           string
	InMint           string
	OutMint          string
	InAmount         int64
	QuoteOutAmount   pgtype.Int8
	OutAmount        pgtype.Int8
	FeeMicros        pgtype.Int8
	SlippageBps      int32
	Status           string
	FailureCode      pgtype.Text
	ExecuteRequestID pgtype.Text
	SignedTx         []byte
	TxSignature      pgtype.Text
	CreatedAt        time.Time
	SubmittedAt      pgtype.Timestamptz
	ConfirmedAt      pgtype.Timestamptz
	FailedAt         pgtype.Timestamptz
	UpdatedAt        time.Time
}

type SwapView struct {
	ID          uuid.UUID
	CabalID     uuid.UUID
	SourceKind  string
	SourceID    uuid.UUID
	Action      string
	Symbol      string
	InAmount    int64
	OutAmount   pgtype.Int8
	Status      string
	FailureCode pgtype.Text
	TxSignature pgtype.Text
	CreatedAt   time.Time
	ConfirmedAt pgtype.Timestamptz
	Retryable   pgtype.Bool
}

type SystemPing struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	Note     string
	EchoedAt pgtype.Timestamptz
}

type TreasuryWallet struct {
	CabalID       uuid.UUID
	PrivyWalletID string
	Address       string
	CreatedAt     time.Time
}

type User struct {
	ID                 uuid.UUID
	PrivyUserID        string
	Handle             pgtype.Text
	HandleChangedAt    pgtype.Timestamptz
	DisplayName        string
	PhotoUrl           pgtype.Text
	Email              pgtype.Text
	LoginProvider      string
	PhoneE164          pgtype.Text
	PhoneHash          []byte
	PhoneVerifiedAt    pgtype.Timestamptz
	XUserID            pgtype.Text
	XUsername          pgtype.Text
	XLinkedAt          pgtype.Timestamptz
	AuthState          string
	AuthStateChangedAt time.Time
	AccountStatus      string
	FirstDepositAt     pgtype.Timestamptz
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DeletedAt          pgtype.Timestamptz
}

type UserPosition struct {
	UserID            uuid.UUID
	CabalID           uuid.UUID
	ShareUnits        pgtype.Numeric
	ContributedMicros pgtype.Numeric
	WithdrawnMicros   pgtype.Numeric
	UpdatedAt         time.Time
}

type UserTxn struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	CabalID     pgtype.UUID
	Kind        string
	Status      string
	TransferID  pgtype.UUID
	TxSignature pgtype.Text
	CreatedAt   time.Time
}

type UserTxnEntry struct {
	TxnID   uuid.UUID
	Seq     int16
	Account string
	Asset   string
	Amount  int64
}

type UserWallet struct {
	UserID        uuid.UUID
	PrivyWalletID string
	Address       string
	CreatedAt     time.Time
}

type Vote struct {
	ProposalID uuid.UUID
	VoterID    uuid.UUID
	Choice     string
	CastAt     time.Time
}
