// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mutes.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteFeedMute = `-- name: DeleteFeedMute :exec
DELETE FROM feed_mutes
WHERE user_id = $1 AND target_type = $2 AND target_id = $3
`

type DeleteFeedMuteParams struct {
	UserID     uuid.UUID
	TargetType string
	TargetID   string
}

func (q *Queries) DeleteFeedMute(ctx context.Context, arg DeleteFeedMuteParams) error {
	_, err := q.db.Exec(ctx, deleteFeedMute, arg.UserID, arg.TargetType, arg.TargetID)
	return err
}

const feedMuteLabel = `-- name: FeedMuteLabel :one
SELECT COALESCE(CASE $1::text
  WHEN 'cabal' THEN f.cabal_name
  WHEN 'asset' THEN f.symbol
  WHEN 'user' THEN f.payload->>'actor_name'
  WHEN 'item' THEN f.title
END, '')::text AS label
FROM feed_objects f
WHERE ($1::text = 'cabal' AND f.cabal_id = $2::uuid)
   OR ($1::text = 'asset' AND f.asset_id = $2::uuid)
   OR ($1::text = 'user' AND f.actor_id = $2::uuid)
   OR ($1::text = 'item' AND f.id = $2::uuid)
ORDER BY f.created_at DESC, f.id DESC
LIMIT 1
`

type FeedMuteLabelParams struct {
	TargetType string
	TargetID   uuid.UUID
}

func (q *Queries) FeedMuteLabel(ctx context.Context, arg FeedMuteLabelParams) (string, error) {
	row := q.db.QueryRow(ctx, feedMuteLabel, arg.TargetType, arg.TargetID)
	var label string
	err := row.Scan(&label)
	return label, err
}

const insertFeedMute = `-- name: InsertFeedMute :exec
INSERT INTO feed_mutes (user_id, target_type, target_id, label, created_at)
VALUES ($1, $2, $3, $4::text, $5)
ON CONFLICT DO NOTHING
`

type InsertFeedMuteParams struct {
	UserID     uuid.UUID
	TargetType string
	TargetID   string
	Label      string
	CreatedAt  time.Time
}

func (q *Queries) InsertFeedMute(ctx context.Context, arg InsertFeedMuteParams) error {
	_, err := q.db.Exec(ctx, insertFeedMute,
		arg.UserID,
		arg.TargetType,
		arg.TargetID,
		arg.Label,
		arg.CreatedAt,
	)
	return err
}

const listFeedMutes = `-- name: ListFeedMutes :many
SELECT target_type, target_id, label, created_at
FROM feed_mutes
WHERE user_id = $1
ORDER BY created_at DESC, target_type, target_id
`

type ListFeedMutesRow struct {
	TargetType string
	TargetID   string
	Label      pgtype.Text
	CreatedAt  time.Time
}

func (q *Queries) ListFeedMutes(ctx context.Context, userID uuid.UUID) ([]ListFeedMutesRow, error) {
	rows, err := q.db.Query(ctx, listFeedMutes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeedMutesRow
	for rows.Next() {
		var i ListFeedMutesRow
		if err := rows.Scan(
			&i.TargetType,
			&i.TargetID,
			&i.Label,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
