//go:build go1.22

// Package fundingapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by cmd/gen httpapi from api/spec/*.yaml. DO NOT EDIT.
package fundingapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	externalRef0 "github.com/monaco/monaco/apps/backend/internal/platform/httpx/api"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for OnrampSessionStatus.
const (
	OnrampSessionStatusCancelled OnrampSessionStatus = "cancelled"
	OnrampSessionStatusConfirmed OnrampSessionStatus = "confirmed"
	OnrampSessionStatusCreated   OnrampSessionStatus = "created"
	OnrampSessionStatusExpired   OnrampSessionStatus = "expired"
	OnrampSessionStatusFailed    OnrampSessionStatus = "failed"
	OnrampSessionStatusOpened    OnrampSessionStatus = "opened"
	OnrampSessionStatusSubmitted OnrampSessionStatus = "submitted"
)

// Valid indicates whether the value is a known member of the OnrampSessionStatus enum.
func (e OnrampSessionStatus) Valid() bool {
	switch e {
	case OnrampSessionStatusCancelled:
		return true
	case OnrampSessionStatusConfirmed:
		return true
	case OnrampSessionStatusCreated:
		return true
	case OnrampSessionStatusExpired:
		return true
	case OnrampSessionStatusFailed:
		return true
	case OnrampSessionStatusOpened:
		return true
	case OnrampSessionStatusSubmitted:
		return true
	default:
		return false
	}
}

// Defines values for ReportOnrampStatusRequestStatus.
const (
	ReportOnrampStatusRequestStatusCancelled ReportOnrampStatusRequestStatus = "cancelled"
	ReportOnrampStatusRequestStatusConfirmed ReportOnrampStatusRequestStatus = "confirmed"
	ReportOnrampStatusRequestStatusFailed    ReportOnrampStatusRequestStatus = "failed"
	ReportOnrampStatusRequestStatusSubmitted ReportOnrampStatusRequestStatus = "submitted"
)

// Valid indicates whether the value is a known member of the ReportOnrampStatusRequestStatus enum.
func (e ReportOnrampStatusRequestStatus) Valid() bool {
	switch e {
	case ReportOnrampStatusRequestStatusCancelled:
		return true
	case ReportOnrampStatusRequestStatusConfirmed:
		return true
	case ReportOnrampStatusRequestStatusFailed:
		return true
	case ReportOnrampStatusRequestStatusSubmitted:
		return true
	default:
		return false
	}
}

// Balance The member wallet's on-chain USDC and currently spendable platform balance.
type Balance struct {
	// AsOf Examples: 2026-10-03T15:00:00Z
	AsOf time.Time `json:"as_of"`

	// AvailableMicros Examples: 22500000
	AvailableMicros string `json:"available_micros"`

	// DepositAddress Examples: 5kwEmpcR8Txq1b4bDazRm9j4cx8Qo2aiE53rYA1dCDDP
	DepositAddress string `json:"deposit_address"`

	// InFlightMicros Examples: 2500000
	InFlightMicros string `json:"in_flight_micros"`

	// OnChainMicros Examples: 25000000
	OnChainMicros string `json:"on_chain_micros"`
}

// CreateOnrampSessionRequest What to prefill on the fund page.
type CreateOnrampSessionRequest struct {
	// CabalId The cabal the user came from, when they did.
	//
	// Examples: 01890a5d-ac96-774b-bcce-b302099a8058
	CabalId *openapi_types.UUID `json:"cabal_id,omitempty"`

	// SuggestedAmountMicros A USDC amount in micros, as a decimal string.
	//
	// Examples: 25000000
	SuggestedAmountMicros *OnrampMicros `json:"suggested_amount_micros,omitempty"`
}

// ExchangeOnrampTokenRequest The token from the fund page URL.
type ExchangeOnrampTokenRequest struct {
	// Token The `s` query parameter of the fund page URL.
	//
	// Examples: q2J9cZQxv0mYb5r8yS3dTt1uVw7xY9zA0bC2dE4fG6h
	Token string `json:"token"`
}

// OnrampExchange What the fund page needs to start the provider flow.
type OnrampExchange struct {
	// SessionId The session id.
	//
	// Examples: 01890a5d-ac96-774b-bcce-b302099a8057
	SessionId openapi_types.UUID `json:"session_id"`

	// SuggestedAmountMicros The amount to prefill in USDC micros, or null to let the user choose.
	//
	// Examples: 25000000
	SuggestedAmountMicros *string `json:"suggested_amount_micros"`

	// UsdcMint The Solana USDC mint.
	//
	// Examples: EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
	UsdcMint string `json:"usdc_mint"`

	// WalletAddress The member wallet the provider sends USDC to.
	//
	// Examples: 9xQeWvG816bUx9EPjHmaT23yvVMvM9fQj4a8PHF4H6P
	WalletAddress string `json:"wallet_address"`
}

// OnrampMicros A USDC amount in micros, as a decimal string.
//
// Examples: 25000000
type OnrampMicros = string

// OnrampSession A card deposit session.
type OnrampSession struct {
	// CompletedAt When the session reached a final status, or null while it is live.
	//
	// Examples: 2026-10-03T15:04:00Z
	CompletedAt *time.Time `json:"completed_at"`

	// CreatedAt When the session was created.
	//
	// Examples: 2026-10-03T15:00:00Z
	CreatedAt time.Time `json:"created_at"`

	// SessionId The session id.
	//
	// Examples: 01890a5d-ac96-774b-bcce-b302099a8057
	SessionId openapi_types.UUID `json:"session_id"`

	// Status Where the session is in its status machine.
	//
	// Examples: confirmed
	Status OnrampSessionStatus `json:"status"`

	// SuggestedAmountMicros The amount the app suggested in USDC micros, or null.
	//
	// Examples: 25000000
	SuggestedAmountMicros *string `json:"suggested_amount_micros"`
}

// OnrampSessionStatus Where the session is in its status machine.
//
// Examples: confirmed
type OnrampSessionStatus string

// OnrampSessionCreated A new onramp session and the page that runs it.
type OnrampSessionCreated struct {
	// ExpiresAt When the token stops working.
	//
	// Examples: 2026-10-03T15:10:00Z
	ExpiresAt time.Time `json:"expires_at"`

	// SessionId The session id.
	//
	// Examples: 01890a5d-ac96-774b-bcce-b302099a8057
	SessionId openapi_types.UUID `json:"session_id"`

	// Url The fund page URL with its one-time token. Open it in the browser.
	//
	// Examples: https://monacolabs.xyz/fund?s=q2J9cZQxv0mYb5r8yS3dTt1uVw7xY9zA0bC2dE4fG6h
	Url string `json:"url"`
}

// ReportOnrampStatusRequest How the provider flow ended.
type ReportOnrampStatusRequest struct {
	// Provider The on-ramp provider Privy chose, when the page knows it.
	//
	// Examples: moonpay
	Provider *string `json:"provider,omitempty"`

	// Status confirmed when the user finished the provider flow, submitted when they left before confirmation, cancelled or failed when it threw.
	//
	// Examples: confirmed
	Status ReportOnrampStatusRequestStatus `json:"status"`
}

// ReportOnrampStatusRequestStatus confirmed when the user finished the provider flow, submitted when they left before confirmation, cancelled or failed when it threw.
//
// Examples: confirmed
type ReportOnrampStatusRequestStatus string

// OnrampSessionId Examples: 01890a5d-ac96-774b-bcce-b302099a8057
type OnrampSessionId = openapi_types.UUID

// CreateOnrampSessionParams defines parameters for CreateOnrampSession.
type CreateOnrampSessionParams struct {
	// IdempotencyKey A key the app generates once per user action. The server stores the first response under it and replays that response for any retry with the same key and body.
	IdempotencyKey externalRef0.IdempotencyKey `json:"Idempotency-Key"`
}

// ReportOnrampStatusParams defines parameters for ReportOnrampStatus.
type ReportOnrampStatusParams struct {
	// IdempotencyKey A key the app generates once per user action. The server stores the first response under it and replays that response for any retry with the same key and body.
	IdempotencyKey externalRef0.IdempotencyKey `json:"Idempotency-Key"`
}

// CreateOnrampSessionJSONRequestBody defines body for CreateOnrampSession for application/json ContentType.
type CreateOnrampSessionJSONRequestBody = CreateOnrampSessionRequest

// ExchangeOnrampTokenJSONRequestBody defines body for ExchangeOnrampToken for application/json ContentType.
type ExchangeOnrampTokenJSONRequestBody = ExchangeOnrampTokenRequest

// ReportOnrampStatusJSONRequestBody defines body for ReportOnrampStatus for application/json ContentType.
type ReportOnrampStatusJSONRequestBody = ReportOnrampStatusRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetMyBalance Read the caller's available platform balance.
	// (GET /v1/me/balance)
	GetMyBalance(w http.ResponseWriter, r *http.Request)
	// CreateOnrampSession Start a card deposit.
	// (POST /v1/onramp/sessions)
	CreateOnrampSession(w http.ResponseWriter, r *http.Request, params CreateOnrampSessionParams)
	// ExchangeOnrampToken Exchange a fund page token for the deposit address.
	// (POST /v1/onramp/sessions/exchange)
	ExchangeOnrampToken(w http.ResponseWriter, r *http.Request)
	// GetOnrampSession Read one of the caller's card deposits.
	// (GET /v1/onramp/sessions/{id})
	GetOnrampSession(w http.ResponseWriter, r *http.Request, id OnrampSessionId)
	// ReportOnrampStatus Report how the provider flow ended.
	// (PATCH /v1/onramp/sessions/{id})
	ReportOnrampStatus(w http.ResponseWriter, r *http.Request, id OnrampSessionId, params ReportOnrampStatusParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetMyBalance operation middleware
func (siw *ServerInterfaceWrapper) GetMyBalance(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMyBalance(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOnrampSession operation middleware
func (siw *ServerInterfaceWrapper) CreateOnrampSession(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateOnrampSessionParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey externalRef0.IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOnrampSession(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExchangeOnrampToken operation middleware
func (siw *ServerInterfaceWrapper) ExchangeOnrampToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExchangeOnrampToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOnrampSession operation middleware
func (siw *ServerInterfaceWrapper) GetOnrampSession(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id OnrampSessionId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOnrampSession(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReportOnrampStatus operation middleware
func (siw *ServerInterfaceWrapper) ReportOnrampStatus(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id OnrampSessionId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ReportOnrampStatusParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey externalRef0.IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReportOnrampStatus(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/me/balance", wrapper.GetMyBalance)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/onramp/sessions", wrapper.CreateOnrampSession)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/onramp/sessions/exchange", wrapper.ExchangeOnrampToken)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/onramp/sessions/{id}", wrapper.GetOnrampSession)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/v1/onramp/sessions/{id}", wrapper.ReportOnrampStatus)

	return m
}

type GetMyBalanceRequestObject struct {
}

type GetMyBalanceResponseObject interface {
	VisitGetMyBalanceResponse(w http.ResponseWriter) error
}

type GetMyBalance200JSONResponse Balance

func (response GetMyBalance200JSONResponse) VisitGetMyBalanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMyBalancedefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response GetMyBalancedefaultApplicationProblemPlusJSONResponse) VisitGetMyBalanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOnrampSessionRequestObject struct {
	Params CreateOnrampSessionParams
	Body   *CreateOnrampSessionJSONRequestBody
}

type CreateOnrampSessionResponseObject interface {
	VisitCreateOnrampSessionResponse(w http.ResponseWriter) error
}

type CreateOnrampSession201JSONResponse OnrampSessionCreated

func (response CreateOnrampSession201JSONResponse) VisitCreateOnrampSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOnrampSessiondefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response CreateOnrampSessiondefaultApplicationProblemPlusJSONResponse) VisitCreateOnrampSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ExchangeOnrampTokenRequestObject struct {
	Body *ExchangeOnrampTokenJSONRequestBody
}

type ExchangeOnrampTokenResponseObject interface {
	VisitExchangeOnrampTokenResponse(w http.ResponseWriter) error
}

type ExchangeOnrampToken200JSONResponse OnrampExchange

func (response ExchangeOnrampToken200JSONResponse) VisitExchangeOnrampTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ExchangeOnrampTokendefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response ExchangeOnrampTokendefaultApplicationProblemPlusJSONResponse) VisitExchangeOnrampTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetOnrampSessionRequestObject struct {
	Id OnrampSessionId `json:"id"`
}

type GetOnrampSessionResponseObject interface {
	VisitGetOnrampSessionResponse(w http.ResponseWriter) error
}

type GetOnrampSession200JSONResponse OnrampSession

func (response GetOnrampSession200JSONResponse) VisitGetOnrampSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetOnrampSessiondefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response GetOnrampSessiondefaultApplicationProblemPlusJSONResponse) VisitGetOnrampSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ReportOnrampStatusRequestObject struct {
	Id     OnrampSessionId `json:"id"`
	Params ReportOnrampStatusParams
	Body   *ReportOnrampStatusJSONRequestBody
}

type ReportOnrampStatusResponseObject interface {
	VisitReportOnrampStatusResponse(w http.ResponseWriter) error
}

type ReportOnrampStatus200JSONResponse OnrampSession

func (response ReportOnrampStatus200JSONResponse) VisitReportOnrampStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ReportOnrampStatusdefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response ReportOnrampStatusdefaultApplicationProblemPlusJSONResponse) VisitReportOnrampStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetMyBalance Read the caller's available platform balance.
	// (GET /v1/me/balance)
	GetMyBalance(ctx context.Context, request GetMyBalanceRequestObject) (GetMyBalanceResponseObject, error)
	// CreateOnrampSession Start a card deposit.
	// (POST /v1/onramp/sessions)
	CreateOnrampSession(ctx context.Context, request CreateOnrampSessionRequestObject) (CreateOnrampSessionResponseObject, error)
	// ExchangeOnrampToken Exchange a fund page token for the deposit address.
	// (POST /v1/onramp/sessions/exchange)
	ExchangeOnrampToken(ctx context.Context, request ExchangeOnrampTokenRequestObject) (ExchangeOnrampTokenResponseObject, error)
	// GetOnrampSession Read one of the caller's card deposits.
	// (GET /v1/onramp/sessions/{id})
	GetOnrampSession(ctx context.Context, request GetOnrampSessionRequestObject) (GetOnrampSessionResponseObject, error)
	// ReportOnrampStatus Report how the provider flow ended.
	// (PATCH /v1/onramp/sessions/{id})
	ReportOnrampStatus(ctx context.Context, request ReportOnrampStatusRequestObject) (ReportOnrampStatusResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetMyBalance operation middleware
func (sh *strictHandler) GetMyBalance(w http.ResponseWriter, r *http.Request) {
	var request GetMyBalanceRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMyBalance(ctx, request.(GetMyBalanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMyBalance")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMyBalanceResponseObject); ok {
		if err := validResponse.VisitGetMyBalanceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateOnrampSession operation middleware
func (sh *strictHandler) CreateOnrampSession(w http.ResponseWriter, r *http.Request, params CreateOnrampSessionParams) {
	var request CreateOnrampSessionRequestObject

	request.Params = params

	var body CreateOnrampSessionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateOnrampSession(ctx, request.(CreateOnrampSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateOnrampSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateOnrampSessionResponseObject); ok {
		if err := validResponse.VisitCreateOnrampSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ExchangeOnrampToken operation middleware
func (sh *strictHandler) ExchangeOnrampToken(w http.ResponseWriter, r *http.Request) {
	var request ExchangeOnrampTokenRequestObject

	var body ExchangeOnrampTokenJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ExchangeOnrampToken(ctx, request.(ExchangeOnrampTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ExchangeOnrampToken")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ExchangeOnrampTokenResponseObject); ok {
		if err := validResponse.VisitExchangeOnrampTokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOnrampSession operation middleware
func (sh *strictHandler) GetOnrampSession(w http.ResponseWriter, r *http.Request, id OnrampSessionId) {
	var request GetOnrampSessionRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOnrampSession(ctx, request.(GetOnrampSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOnrampSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOnrampSessionResponseObject); ok {
		if err := validResponse.VisitGetOnrampSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ReportOnrampStatus operation middleware
func (sh *strictHandler) ReportOnrampStatus(w http.ResponseWriter, r *http.Request, id OnrampSessionId, params ReportOnrampStatusParams) {
	var request ReportOnrampStatusRequestObject

	request.Id = id
	request.Params = params

	var body ReportOnrampStatusJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ReportOnrampStatus(ctx, request.(ReportOnrampStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReportOnrampStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReportOnrampStatusResponseObject); ok {
		if err := validResponse.VisitReportOnrampStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
