// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: engine.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const deliveryRecorded = `-- name: DeliveryRecorded :one
SELECT EXISTS (
  SELECT 1 FROM event_deliveries WHERE handler = $1 AND event_id = $2
)::bool AS recorded
`

type DeliveryRecordedParams struct {
	Handler string
	EventID uuid.UUID
}

func (q *Queries) DeliveryRecorded(ctx context.Context, arg DeliveryRecordedParams) (bool, error) {
	row := q.db.QueryRow(ctx, deliveryRecorded, arg.Handler, arg.EventID)
	var recorded bool
	err := row.Scan(&recorded)
	return recorded, err
}
