// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stuck.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countStuckSwaps = `-- name: CountStuckSwaps :one
SELECT ((
  SELECT count(*) FROM swaps WHERE status = 'created' AND created_at < $1::timestamptz
) + (
  SELECT count(*) FROM swaps WHERE status = 'submitted' AND submitted_at < $1::timestamptz
))::bigint AS stuck
`

func (q *Queries) CountStuckSwaps(ctx context.Context, cutoff time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, countStuckSwaps, cutoff)
	var stuck int64
	err := row.Scan(&stuck)
	return stuck, err
}

const executeRequestID = `-- name: ExecuteRequestID :one
SELECT coalesce(execute_request_id, '')::text AS execute_request_id FROM swaps WHERE id = $1
`

func (q *Queries) ExecuteRequestID(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, executeRequestID, id)
	var execute_request_id string
	err := row.Scan(&execute_request_id)
	return execute_request_id, err
}

const stuckSwaps = `-- name: StuckSwaps :many
WITH stuck AS (
  SELECT u.id, u.since
  FROM (
    SELECT s.id, s.created_at AS since FROM swaps AS s
    WHERE s.status = 'created' AND s.created_at < $1::timestamptz
    UNION ALL
    SELECT s.id, s.submitted_at AS since FROM swaps AS s
    WHERE s.status = 'submitted' AND s.submitted_at < $1::timestamptz
  ) AS u
  ORDER BY u.since, u.id
  LIMIT $2::bigint
)
SELECT v.id, v.cabal_id, v.source_kind, v.source_id, v.action, v.symbol, v.in_amount, v.out_decimals, v.out_amount,
  v.status, v.failure_code, v.tx_signature, v.created_at, v.confirmed_at, v.retryable
FROM stuck
JOIN swap_views AS v ON v.id = stuck.id
ORDER BY stuck.since, v.id
`

type StuckSwapsParams struct {
	Cutoff   time.Time
	RowLimit int64
}

func (q *Queries) StuckSwaps(ctx context.Context, arg StuckSwapsParams) ([]SwapView, error) {
	rows, err := q.db.Query(ctx, stuckSwaps, arg.Cutoff, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SwapView
	for rows.Next() {
		var i SwapView
		if err := rows.Scan(
			&i.ID,
			&i.CabalID,
			&i.SourceKind,
			&i.SourceID,
			&i.Action,
			&i.Symbol,
			&i.InAmount,
			&i.OutDecimals,
			&i.OutAmount,
			&i.Status,
			&i.FailureCode,
			&i.TxSignature,
			&i.CreatedAt,
			&i.ConfirmedAt,
			&i.Retryable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
