// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: swap_detail.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const swapDetail = `-- name: SwapDetail :one
SELECT v.id, v.cabal_id, v.source_kind, v.source_id, v.action, v.symbol, v.in_amount, v.out_amount, v.status,
  v.failure_code, v.tx_signature, v.created_at, v.confirmed_at, (v.retryable AND v.source_kind = 'proposal')::bool AS retryable,
  (CASE WHEN s.action = 'buy' THEN s.out_mint ELSE s.in_mint END)::text AS token_mint
FROM swap_views v
JOIN swaps s ON s.id = v.id
WHERE v.id = $1
`

type SwapDetailRow struct {
	ID          uuid.UUID
	CabalID     uuid.UUID
	SourceKind  string
	SourceID    uuid.UUID
	Action      string
	Symbol      string
	InAmount    int64
	OutAmount   pgtype.Int8
	Status      string
	FailureCode pgtype.Text
	TxSignature pgtype.Text
	CreatedAt   time.Time
	ConfirmedAt pgtype.Timestamptz
	Retryable   bool
	TokenMint   string
}

func (q *Queries) SwapDetail(ctx context.Context, id uuid.UUID) (SwapDetailRow, error) {
	row := q.db.QueryRow(ctx, swapDetail, id)
	var i SwapDetailRow
	err := row.Scan(
		&i.ID,
		&i.CabalID,
		&i.SourceKind,
		&i.SourceID,
		&i.Action,
		&i.Symbol,
		&i.InAmount,
		&i.OutAmount,
		&i.Status,
		&i.FailureCode,
		&i.TxSignature,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.Retryable,
		&i.TokenMint,
	)
	return i, err
}
