// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: swaps.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimLive = `-- name: ClaimLive :one
SELECT id, status
FROM swaps
WHERE source_kind = $1 AND source_id = $2 AND in_mint = $3 AND status <> 'failed'
`

type ClaimLiveParams struct {
	SourceKind string
	SourceID   uuid.UUID
	InMint     string
}

type ClaimLiveRow struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) ClaimLive(ctx context.Context, arg ClaimLiveParams) (ClaimLiveRow, error) {
	row := q.db.QueryRow(ctx, claimLive, arg.SourceKind, arg.SourceID, arg.InMint)
	var i ClaimLiveRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const finishConfirmed = `-- name: FinishConfirmed :execrows
UPDATE swaps
SET status = 'confirmed', out_amount = $1::bigint, fee_micros = $2::bigint,
  confirmed_at = $3::timestamptz, updated_at = $3::timestamptz
WHERE id = $4 AND status = 'submitted'
`

type FinishConfirmedParams struct {
	OutAmount   int64
	FeeMicros   int64
	ConfirmedAt time.Time
	ID          uuid.UUID
}

func (q *Queries) FinishConfirmed(ctx context.Context, arg FinishConfirmedParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishConfirmed,
		arg.OutAmount,
		arg.FeeMicros,
		arg.ConfirmedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishFailed = `-- name: FinishFailed :execrows
UPDATE swaps
SET status = 'failed', failure_code = $1::text,
  failed_at = $2::timestamptz, updated_at = $2::timestamptz
WHERE id = $3
  AND CASE status
    WHEN 'created' THEN $1::text IN ('never_submitted', 'source_cancelled')
    WHEN 'submitted' THEN $1::text IN ('blockhash_expired', 'jupiter_failed', 'force_resolved')
    ELSE false
  END
`

type FinishFailedParams struct {
	FailureCode string
	FailedAt    time.Time
	ID          uuid.UUID
}

func (q *Queries) FinishFailed(ctx context.Context, arg FinishFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishFailed, arg.FailureCode, arg.FailedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertCreated = `-- name: InsertCreated :exec
INSERT INTO swaps (
  id, source_kind, source_id, cabal_id, treasury_address, action, symbol,
  in_mint, out_mint, in_amount, quote_out_amount, slippage_bps, status, created_at, updated_at
)
VALUES (
  $1, $2, $3, $4, $5, $6, $7,
  $8, $9, $10, $11, $12, 'created', $13, $13
)
`

type InsertCreatedParams struct {
	ID              uuid.UUID
	SourceKind      string
	SourceID        uuid.UUID
	CabalID         uuid.UUID
	TreasuryAddress string
	Action          string
	Symbol          string
	InMint          string
	OutMint         string
	InAmount        int64
	QuoteOutAmount  pgtype.Int8
	SlippageBps     int32
	CreatedAt       time.Time
}

func (q *Queries) InsertCreated(ctx context.Context, arg InsertCreatedParams) error {
	_, err := q.db.Exec(ctx, insertCreated,
		arg.ID,
		arg.SourceKind,
		arg.SourceID,
		arg.CabalID,
		arg.TreasuryAddress,
		arg.Action,
		arg.Symbol,
		arg.InMint,
		arg.OutMint,
		arg.InAmount,
		arg.QuoteOutAmount,
		arg.SlippageBps,
		arg.CreatedAt,
	)
	return err
}

const markSubmitted = `-- name: MarkSubmitted :execrows
UPDATE swaps
SET status = 'submitted', execute_request_id = $1::text, signed_tx = $2::bytea,
  tx_signature = $3::text, submitted_at = $4::timestamptz, updated_at = $4::timestamptz
WHERE id = $5 AND status = 'created' AND octet_length($2::bytea) > 0
`

type MarkSubmittedParams struct {
	ExecuteRequestID string
	SignedTx         []byte
	TxSignature      string
	SubmittedAt      time.Time
	ID               uuid.UUID
}

func (q *Queries) MarkSubmitted(ctx context.Context, arg MarkSubmittedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markSubmitted,
		arg.ExecuteRequestID,
		arg.SignedTx,
		arg.TxSignature,
		arg.SubmittedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
