// Code generated by scripts/gen-registry. DO NOT EDIT.

package flows

func (defined) ScriptsF01a() map[string]Script {
	return map[string]Script{
		"F01aSetHandleOK":             F01aSetHandleOK,
		"F01aSetHandleHandleInvalid":  F01aSetHandleHandleInvalid,
		"F01aSetHandleHandleReserved": F01aSetHandleHandleReserved,
		"F01aSetHandleHandleTaken":    F01aSetHandleHandleTaken,
		"F01aSetHandleHandleTooSoon":  F01aSetHandleHandleTooSoon,
	}
}
