// Code generated by scripts/gen-registry. DO NOT EDIT.

package flows

func (defined) ScriptsF01c() map[string]Script {
	return map[string]Script{
		"F01cLinkSocialsOK":               F01cLinkSocialsOK,
		"F01cLinkSocialsHandleRequired":   F01cLinkSocialsHandleRequired,
		"F01cLinkSocialsXNotLinked":       F01cLinkSocialsXNotLinked,
		"F01cLinkSocialsPrivyUnavailable": F01cLinkSocialsPrivyUnavailable,
	}
}
