// Code generated by scripts/gen-registry. DO NOT EDIT.

package flows

func (defined) ScriptsF04() map[string]Script {
	return map[string]Script{
		"F04LeaveCabalOK":                         F04LeaveCabalOK,
		"F04LeaveCabalUnauthorized":               F04LeaveCabalUnauthorized,
		"F04LeaveCabalNotCabalMember":             F04LeaveCabalNotCabalMember,
		"F04LeaveCabalLeaveHoldsShares":           F04LeaveCabalLeaveHoldsShares,
		"F04LeaveCabalLeaveLastMemberPotNotEmpty": F04LeaveCabalLeaveLastMemberPotNotEmpty,
		"F04LeaveCabalLeaveCreatorWithMembers":    F04LeaveCabalLeaveCreatorWithMembers,
		"F04LeaveCabalPriceUnavailable":           F04LeaveCabalPriceUnavailable,
		"F04LeaveCabalCrashBeforeCommit":          F04LeaveCabalCrashBeforeCommit,
	}
}
