// Code generated by scripts/gen-registry. DO NOT EDIT.

package flows

func (defined) ScriptsF07() map[string]Script {
	return map[string]Script{
		"F07FundCabalOK":                F07FundCabalOK,
		"F07FundCabalCrashBeforeCommit": F07FundCabalCrashBeforeCommit,
		"F07FundCabalInvalidInput":      F07FundCabalInvalidInput,
		"F07FundCabalNotCabalMember":    F07FundCabalNotCabalMember,
		"F07FundCabalInsufficientFunds": F07FundCabalInsufficientFunds,
		"F07FundCabalCabalPaused":       F07FundCabalCabalPaused,
		"F07FundCabalPotValueZero":      F07FundCabalPotValueZero,
		"F07FundCabalPrivyUnavailable":  F07FundCabalPrivyUnavailable,
	}
}
