// Code generated by scripts/gen-registry. DO NOT EDIT.

package flows

func (defined) ScriptsF18() map[string]Script {
	return map[string]Script{
		"F18SamplePricesOK":                 F18SamplePricesOK,
		"F18SamplePricesJupiterUnavailable": F18SamplePricesJupiterUnavailable,
		"F18SamplePricesUpstreamTimeout":    F18SamplePricesUpstreamTimeout,
		"F18SamplePricesCrashBeforeCommit":  F18SamplePricesCrashBeforeCommit,
	}
}
