// Code generated by scripts/gen-registry. DO NOT EDIT.

package flows

func (defined) ScriptsF19() map[string]Script {
	return map[string]Script{
		"F19RunValuationOK":                 F19RunValuationOK,
		"F19RunValuationPricesStale":        F19RunValuationPricesStale,
		"F19RunValuationConservationBroken": F19RunValuationConservationBroken,
		"F19RunValuationCabalPaused":        F19RunValuationCabalPaused,
		"F19RunValuationCrashBeforeCommit":  F19RunValuationCrashBeforeCommit,
	}
}
