// Code generated by scripts/gen-registry. DO NOT EDIT.

package flows

func (defined) ScriptsF23() map[string]Script {
	return map[string]Script{
		"F23UpdateProfileOK":                       F23UpdateProfileOK,
		"F23UpdateProfileDisplayNameInvalid":       F23UpdateProfileDisplayNameInvalid,
		"F23aUploadProfilePhotoOK":                 F23aUploadProfilePhotoOK,
		"F23aUploadProfilePhotoPhotoInvalid":       F23aUploadProfilePhotoPhotoInvalid,
		"F23aUploadProfilePhotoStorageUnavailable": F23aUploadProfilePhotoStorageUnavailable,
		"F23aUploadProfilePhotoRateLimited":        F23aUploadProfilePhotoRateLimited,
	}
}
