// Code generated by scripts/gen-registry. DO NOT EDIT.

package flows

func (defined) ScriptsF26() map[string]Script {
	return map[string]Script{
		"F26FlagPingOK":                F26FlagPingOK,
		"F26FlagPingReasonRequired":    F26FlagPingReasonRequired,
		"F26FlagPingAdminForbidden":    F26FlagPingAdminForbidden,
		"F26FlagPingAlreadyFlagged":    F26FlagPingAlreadyFlagged,
		"F26FlagPingNotFound":          F26FlagPingNotFound,
		"F26FlagPingCrashAfterPublish": F26FlagPingCrashAfterPublish,
	}
}
