//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorCode.
const (
	AccessRequestNotPending    ErrorCode = "access_request_not_pending"
	AccountBanned              ErrorCode = "account_banned"
	AccountDeleted             ErrorCode = "account_deleted"
	AccountHasBalance          ErrorCode = "account_has_balance"
	AccountHasPositions        ErrorCode = "account_has_positions"
	AccountStatusTransition    ErrorCode = "account_status_transition"
	AccountSuspended           ErrorCode = "account_suspended"
	AlreadyMember              ErrorCode = "already_member"
	AnalyticsPii               ErrorCode = "analytics_pii"
	ApnsAuthFailed             ErrorCode = "apns_auth_failed"
	ApnsUnavailable            ErrorCode = "apns_unavailable"
	AssetNotFound              ErrorCode = "asset_not_found"
	AuthStateTransition        ErrorCode = "auth_state_transition"
	CabalBanned                ErrorCode = "cabal_banned"
	CabalNotFound              ErrorCode = "cabal_not_found"
	CannotRevokeAccess         ErrorCode = "cannot_revoke_access"
	ClientClosed               ErrorCode = "client_closed"
	ConservationBroken         ErrorCode = "conservation_broken"
	DbSchemaBehind             ErrorCode = "db_schema_behind"
	DbUnavailable              ErrorCode = "db_unavailable"
	DecodeFailed               ErrorCode = "decode_failed"
	DisplayNameInvalid         ErrorCode = "display_name_invalid"
	Forbidden                  ErrorCode = "forbidden"
	HandleInvalid              ErrorCode = "handle_invalid"
	HandleRequired             ErrorCode = "handle_required"
	HandleReserved             ErrorCode = "handle_reserved"
	HandleTaken                ErrorCode = "handle_taken"
	HandleTooSoon              ErrorCode = "handle_too_soon"
	IdempotencyInFlight        ErrorCode = "idempotency_in_flight"
	IdempotencyMismatch        ErrorCode = "idempotency_mismatch"
	Internal                   ErrorCode = "internal"
	InvalidAddress             ErrorCode = "invalid_address"
	InvalidConfig              ErrorCode = "invalid_config"
	InvalidInput               ErrorCode = "invalid_input"
	InviteExpired              ErrorCode = "invite_expired"
	JoinNeedsRequest           ErrorCode = "join_needs_request"
	JupiterRejected            ErrorCode = "jupiter_rejected"
	JupiterUnavailable         ErrorCode = "jupiter_unavailable"
	LeaveCreatorWithMembers    ErrorCode = "leave_creator_with_members"
	LeaveHoldsShares           ErrorCode = "leave_holds_shares"
	LeaveLastMemberPotNotEmpty ErrorCode = "leave_last_member_pot_not_empty"
	LedgerUnbalanced           ErrorCode = "ledger_unbalanced"
	LiveSwapExists             ErrorCode = "live_swap_exists"
	LoginMethodNotAllowed      ErrorCode = "login_method_not_allowed"
	NoRoute                    ErrorCode = "no_route"
	NotAVoter                  ErrorCode = "not_a_voter"
	NotCabalCreator            ErrorCode = "not_cabal_creator"
	NotCabalMember             ErrorCode = "not_cabal_member"
	NotFound                   ErrorCode = "not_found"
	NotProposer                ErrorCode = "not_proposer"
	Panic                      ErrorCode = "panic"
	PhoneNotLinked             ErrorCode = "phone_not_linked"
	PhotoInvalid               ErrorCode = "photo_invalid"
	PostHogRejected            ErrorCode = "post_hog_rejected"
	PostHogUnavailable         ErrorCode = "post_hog_unavailable"
	PotExceeded                ErrorCode = "pot_exceeded"
	PotValueZero               ErrorCode = "pot_value_zero"
	PrivyUnavailable           ErrorCode = "privy_unavailable"
	ProposalClosed             ErrorCode = "proposal_closed"
	ProposalNotFound           ErrorCode = "proposal_not_found"
	RateLimited                ErrorCode = "rate_limited"
	RelayerUnderfunded         ErrorCode = "relayer_underfunded"
	RequestNotNeeded           ErrorCode = "request_not_needed"
	RequestPending             ErrorCode = "request_pending"
	RpcUnavailable             ErrorCode = "rpc_unavailable"
	SessionRequired            ErrorCode = "session_required"
	SlippageExceeded           ErrorCode = "slippage_exceeded"
	SwapFailed                 ErrorCode = "swap_failed"
	SwapNotFound               ErrorCode = "swap_not_found"
	SwapNotRetryable           ErrorCode = "swap_not_retryable"
	Unauthorized               ErrorCode = "unauthorized"
	UpstreamTimeout            ErrorCode = "upstream_timeout"
	UpstreamUnavailable        ErrorCode = "upstream_unavailable"
	UserNotFound               ErrorCode = "user_not_found"
	VersionConflict            ErrorCode = "version_conflict"
	WalletMismatch             ErrorCode = "wallet_mismatch"
	WithdrawNotAllowed         ErrorCode = "withdraw_not_allowed"
	XNotLinked                 ErrorCode = "x_not_linked"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case AccessRequestNotPending:
		return true
	case AccountBanned:
		return true
	case AccountDeleted:
		return true
	case AccountHasBalance:
		return true
	case AccountHasPositions:
		return true
	case AccountStatusTransition:
		return true
	case AccountSuspended:
		return true
	case AlreadyMember:
		return true
	case AnalyticsPii:
		return true
	case ApnsAuthFailed:
		return true
	case ApnsUnavailable:
		return true
	case AssetNotFound:
		return true
	case AuthStateTransition:
		return true
	case CabalBanned:
		return true
	case CabalNotFound:
		return true
	case CannotRevokeAccess:
		return true
	case ClientClosed:
		return true
	case ConservationBroken:
		return true
	case DbSchemaBehind:
		return true
	case DbUnavailable:
		return true
	case DecodeFailed:
		return true
	case DisplayNameInvalid:
		return true
	case Forbidden:
		return true
	case HandleInvalid:
		return true
	case HandleRequired:
		return true
	case HandleReserved:
		return true
	case HandleTaken:
		return true
	case HandleTooSoon:
		return true
	case IdempotencyInFlight:
		return true
	case IdempotencyMismatch:
		return true
	case Internal:
		return true
	case InvalidAddress:
		return true
	case InvalidConfig:
		return true
	case InvalidInput:
		return true
	case InviteExpired:
		return true
	case JoinNeedsRequest:
		return true
	case JupiterRejected:
		return true
	case JupiterUnavailable:
		return true
	case LeaveCreatorWithMembers:
		return true
	case LeaveHoldsShares:
		return true
	case LeaveLastMemberPotNotEmpty:
		return true
	case LedgerUnbalanced:
		return true
	case LiveSwapExists:
		return true
	case LoginMethodNotAllowed:
		return true
	case NoRoute:
		return true
	case NotAVoter:
		return true
	case NotCabalCreator:
		return true
	case NotCabalMember:
		return true
	case NotFound:
		return true
	case NotProposer:
		return true
	case Panic:
		return true
	case PhoneNotLinked:
		return true
	case PhotoInvalid:
		return true
	case PostHogRejected:
		return true
	case PostHogUnavailable:
		return true
	case PotExceeded:
		return true
	case PotValueZero:
		return true
	case PrivyUnavailable:
		return true
	case ProposalClosed:
		return true
	case ProposalNotFound:
		return true
	case RateLimited:
		return true
	case RelayerUnderfunded:
		return true
	case RequestNotNeeded:
		return true
	case RequestPending:
		return true
	case RpcUnavailable:
		return true
	case SessionRequired:
		return true
	case SlippageExceeded:
		return true
	case SwapFailed:
		return true
	case SwapNotFound:
		return true
	case SwapNotRetryable:
		return true
	case Unauthorized:
		return true
	case UpstreamTimeout:
		return true
	case UpstreamUnavailable:
		return true
	case UserNotFound:
		return true
	case VersionConflict:
		return true
	case WalletMismatch:
		return true
	case WithdrawNotAllowed:
		return true
	case XNotLinked:
		return true
	default:
		return false
	}
}

// Defines values for ProblemType.
const (
	AboutBlank ProblemType = "about:blank"
)

// Valid indicates whether the value is a known member of the ProblemType enum.
func (e ProblemType) Valid() bool {
	switch e {
	case AboutBlank:
		return true
	default:
		return false
	}
}

// ErrorCode The closed list of error codes. Generated from the errs table by monacoctl gen errors.
//
// Examples: not_found
type ErrorCode string

// Ping A recorded ping.
type Ping struct {
	// Echoed True once the `system.echo` consumer has handled the ping.
	//
	// Examples: true
	Echoed bool `json:"echoed"`

	// Id The ping id.
	//
	// Examples: 01890a5d-ac96-774b-bcce-b302099a8057
	Id openapi_types.UUID `json:"id"`

	// Note The note sent with the ping.
	//
	// Examples: hi
	Note string `json:"note"`
}

// PingRequest A note to record with the ping.
type PingRequest struct {
	// Note Free text, at most 140 characters.
	//
	// Examples: hi
	Note string `json:"note"`
}

// Problem An RFC 9457 problem details body with a stable Monaco error code.
//
// Examples: {"code":"not_found","message":"Not found.","retryable":false,"status":404,"title":"Not Found","trace_id":"4bf92f3577b34da6a3ce929d0e0e4736","type":"about:blank"}
type Problem struct {
	// Code The closed list of error codes. Generated from the errs table by monacoctl gen errors.
	//
	// Examples: not_found
	Code ErrorCode `json:"code"`

	// Message A user-facing sentence the app shows as is.
	//
	// Examples: Not found.
	Message string `json:"message"`

	// Retryable True when the same request may succeed if sent again later.
	//
	// Examples: false
	Retryable bool `json:"retryable"`

	// Status The HTTP status code of this response.
	//
	// Examples: 404
	Status int `json:"status"`

	// Title The HTTP status phrase.
	//
	// Examples: Not Found
	Title string `json:"title"`

	// TraceId The W3C trace id of the request. Logs and traces carry the same id.
	//
	// Examples: 4bf92f3577b34da6a3ce929d0e0e4736
	TraceId string `json:"trace_id"`

	// Type Always about:blank. The code field carries the problem type.
	Type ProblemType `json:"type"`
}

// ProblemType Always about:blank. The code field carries the problem type.
type ProblemType string

// IdempotencyKey Examples: 6f1c1a52-3a4e-4d0e-9d7b-2f7f3f5b9d10
type IdempotencyKey = string

// GetStreamParams defines parameters for GetStream.
type GetStreamParams struct {
	// LastEventID The id of the last event the app received before it reconnected.
	LastEventID *string `json:"Last-Event-ID,omitempty"`
}

// PostSystemPingParams defines parameters for PostSystemPing.
type PostSystemPingParams struct {
	// IdempotencyKey A key the app generates once per user action. The server stores the first response under it and replays that response for any retry with the same key and body.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// PostSystemPingJSONRequestBody defines body for PostSystemPing for application/json ContentType.
type PostSystemPingJSONRequestBody = PingRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealthz Report that the API process is serving.
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// GetStream Stream re-fetch hints for the caller.
	// (GET /v1/stream)
	GetStream(w http.ResponseWriter, r *http.Request, params GetStreamParams)
	// PostSystemPing Record a ping for the caller.
	// (POST /v1/system/pings)
	PostSystemPing(w http.ResponseWriter, r *http.Request, params PostSystemPingParams)
	// GetSystemPing Read one of the caller's pings.
	// (GET /v1/system/pings/{id})
	GetSystemPing(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStream operation middleware
func (siw *ServerInterfaceWrapper) GetStream(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetStreamParams

	headers := r.Header

	// ------------- Optional header parameter "Last-Event-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Last-Event-ID")]; found {
		var LastEventID string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Last-Event-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Last-Event-ID", valueList[0], &LastEventID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Last-Event-ID", Err: err})
			return
		}

		params.LastEventID = &LastEventID

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStream(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostSystemPing operation middleware
func (siw *ServerInterfaceWrapper) PostSystemPing(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PostSystemPingParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostSystemPing(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSystemPing operation middleware
func (siw *ServerInterfaceWrapper) GetSystemPing(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSystemPing(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealthz)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/stream", wrapper.GetStream)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/system/pings", wrapper.PostSystemPing)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/system/pings/{id}", wrapper.GetSystemPing)

	return m
}

type ProblemApplicationProblemPlusJSONResponse Problem

type GetHealthzRequestObject struct {
}

type GetHealthzResponseObject interface {
	VisitGetHealthzResponse(w http.ResponseWriter) error
}

type GetHealthz200TextResponse string

func (response GetHealthz200TextResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(fmt.Sprint(response)))
	return err
}

type GetHealthzdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetHealthzdefaultApplicationProblemPlusJSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetStreamRequestObject struct {
	Params GetStreamParams
}

type GetStreamResponseObject interface {
	VisitGetStreamResponse(w http.ResponseWriter) error
}

type GetStream200TexteventStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetStream200TexteventStreamResponse) VisitGetStreamResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	flusher, ok := w.(http.Flusher)
	if !ok {
		// If w doesn't support flushing, fall back to io.Copy.
		_, err := io.Copy(w, response.Body)
		return err
	}
	// text/event-stream messages are typically small; use a
	// modest buffer and flush after each chunk so clients see
	// events immediately instead of waiting on OS buffering.
	buf := make([]byte, 4096)
	for {
		n, err := response.Body.Read(buf)
		if n > 0 {
			if _, writeErr := w.Write(buf[:n]); writeErr != nil {
				return writeErr
			}
			flusher.Flush()
		}
		if err != nil {
			if err == io.EOF {
				return nil
			}
			return err
		}
	}
}

type GetStreamdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetStreamdefaultApplicationProblemPlusJSONResponse) VisitGetStreamResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type PostSystemPingRequestObject struct {
	Params PostSystemPingParams
	Body   *PostSystemPingJSONRequestBody
}

type PostSystemPingResponseObject interface {
	VisitPostSystemPingResponse(w http.ResponseWriter) error
}

type PostSystemPing201JSONResponse Ping

func (response PostSystemPing201JSONResponse) VisitPostSystemPingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type PostSystemPingdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response PostSystemPingdefaultApplicationProblemPlusJSONResponse) VisitPostSystemPingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetSystemPingRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetSystemPingResponseObject interface {
	VisitGetSystemPingResponse(w http.ResponseWriter) error
}

type GetSystemPing200JSONResponse Ping

func (response GetSystemPing200JSONResponse) VisitGetSystemPingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSystemPingdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetSystemPingdefaultApplicationProblemPlusJSONResponse) VisitGetSystemPingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetHealthz Report that the API process is serving.
	// (GET /healthz)
	GetHealthz(ctx context.Context, request GetHealthzRequestObject) (GetHealthzResponseObject, error)
	// GetStream Stream re-fetch hints for the caller.
	// (GET /v1/stream)
	GetStream(ctx context.Context, request GetStreamRequestObject) (GetStreamResponseObject, error)
	// PostSystemPing Record a ping for the caller.
	// (POST /v1/system/pings)
	PostSystemPing(ctx context.Context, request PostSystemPingRequestObject) (PostSystemPingResponseObject, error)
	// GetSystemPing Read one of the caller's pings.
	// (GET /v1/system/pings/{id})
	GetSystemPing(ctx context.Context, request GetSystemPingRequestObject) (GetSystemPingResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealthz operation middleware
func (sh *strictHandler) GetHealthz(w http.ResponseWriter, r *http.Request) {
	var request GetHealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthz(ctx, request.(GetHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthzResponseObject); ok {
		if err := validResponse.VisitGetHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetStream operation middleware
func (sh *strictHandler) GetStream(w http.ResponseWriter, r *http.Request, params GetStreamParams) {
	var request GetStreamRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetStream(ctx, request.(GetStreamRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetStream")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetStreamResponseObject); ok {
		if err := validResponse.VisitGetStreamResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostSystemPing operation middleware
func (sh *strictHandler) PostSystemPing(w http.ResponseWriter, r *http.Request, params PostSystemPingParams) {
	var request PostSystemPingRequestObject

	request.Params = params

	var body PostSystemPingJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostSystemPing(ctx, request.(PostSystemPingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostSystemPing")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostSystemPingResponseObject); ok {
		if err := validResponse.VisitPostSystemPingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSystemPing operation middleware
func (sh *strictHandler) GetSystemPing(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetSystemPingRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSystemPing(ctx, request.(GetSystemPingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSystemPing")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSystemPingResponseObject); ok {
		if err := validResponse.VisitGetSystemPingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
