package flows

import "strings"

func Markdown(flows []Flow) string {
	var b strings.Builder
	b.WriteString("| # | Flow | Command / trigger | Events | Consumers |\n| --- | --- | --- | --- | --- |\n")
	for _, f := range flows {
		trigger := commandTriggers(f)
		cells := []string{f.ID, cell(f.Name), trigger, codes(f.Events), cell(orNone(strings.Join(f.Consumers, ", ")))}
		b.WriteString("| " + strings.Join(cells, " | ") + " |\n")
	}
	return b.String()
}

func commandTriggers(f Flow) string {
	triggers := f.Triggers()
	if len(f.Commands) == 0 {
		return codes(triggers)
	}
	if len(triggers) == 0 {
		return codes(f.Commands)
	}
	if len(triggers) != len(f.Commands) || len(triggers) == 1 {
		return codes(f.Commands) + " on " + code(f.Trigger)
	}
	pairs := make([]string, len(f.Commands))
	for i, command := range f.Commands {
		pairs[i] = code(command) + " on " + code(triggers[i])
	}
	return strings.Join(pairs, ", ")
}

func cell(s string) string { return strings.ReplaceAll(s, "|", `\|`) }

func code(s string) string { return "`" + cell(s) + "`" }

func codes(items []string) string {
	quoted := make([]string, 0, len(items))
	for _, item := range items {
		quoted = append(quoted, code(item))
	}
	return orNone(strings.Join(quoted, ", "))
}

func orNone(s string) string {
	if s == "" {
		return "none"
	}
	return s
}

func FeatureMapPage(f Flow) string {
	var b strings.Builder
	b.WriteString("# Flow " + f.ID + ": " + f.Name + "\n\n" +
		"Generated by `monacoctl gen flows` from `" + Dir + "/" + f.ID + ".tsv`. Do not edit.\n\n")
	rows := [][2]string{
		{"Module", code(f.Module)},
		{"Status", code(string(f.Status))},
		{"Trigger", codes(f.Triggers())},
		{"Command", codes(f.Commands)},
		{"Events", codes(f.Events)},
		{"Consumers", codes(f.Consumers)},
		{"Doc", code(f.Doc)},
	}
	for _, r := range rows {
		b.WriteString("- " + r[0] + ": " + r[1] + "\n")
	}
	b.WriteString("\n| Outcome | Test | Verify |\n| --- | --- | --- |\n")
	for _, o := range f.Outcomes {
		cells := []string{
			code(string(o)),
			testCells(f, o),
			code("monacoctl verify flow " + f.ID + " --outcome " + string(o)),
		}
		b.WriteString("| " + strings.Join(cells, " | ") + " |\n")
	}
	return b.String()
}

func testCells(f Flow, o Outcome) string {
	names := make([]string, 0, len(f.Commands))
	for _, command := range f.Commands {
		names = append(names, code(TestName(f, command, o)))
	}
	return strings.Join(names, " or ")
}
