package flows

import "strings"

func Markdown(flows []Flow) string {
	var b strings.Builder
	b.WriteString("| # | Flow | Command / trigger | Events | Consumers |\n| --- | --- | --- | --- | --- |\n")
	for _, f := range flows {
		trigger := code(f.Trigger)
		if f.Command != "" {
			trigger = code(f.Command) + " on " + trigger
		}
		cells := []string{f.ID, cell(f.Name), trigger, codes(f.Events), cell(orNone(strings.Join(f.Consumers, ", ")))}
		b.WriteString("| " + strings.Join(cells, " | ") + " |\n")
	}
	return b.String()
}

func cell(s string) string { return strings.ReplaceAll(s, "|", `\|`) }

func code(s string) string { return "`" + cell(s) + "`" }

func codes(items []string) string {
	quoted := make([]string, 0, len(items))
	for _, item := range items {
		quoted = append(quoted, code(item))
	}
	return orNone(strings.Join(quoted, ", "))
}

func orNone(s string) string {
	if s == "" {
		return "none"
	}
	return s
}

func FeatureMap(flows []Flow) string {
	var b strings.Builder
	b.WriteString("# Feature map\n\n" +
		"Generated by `monacoctl docs flows --feature-map` from `apps/backend/flows.tsv`. Do not edit; " +
		"`scripts/ci/ready.sh` fails when it is stale.\n")
	for _, f := range flows {
		b.WriteString("\n## Flow " + f.ID + ": " + f.Name + "\n\n")
		rows := [][2]string{
			{"Module", code(f.Module)},
			{"Status", code(string(f.Status))},
			{"Trigger", code(f.Trigger)},
			{"Command", orNone(optionalCode(f.Command))},
			{"Events", codes(f.Events)},
			{"Consumers", codes(f.Consumers)},
			{"Doc", code(f.Doc)},
		}
		for _, r := range rows {
			b.WriteString("- " + r[0] + ": " + r[1] + "\n")
		}
		b.WriteString("\n| Outcome | Test | Verify |\n| --- | --- | --- |\n")
		for _, o := range f.Outcomes {
			cells := []string{
				code(string(o)),
				code(TestName(f, o)),
				code("monacoctl verify flow " + f.ID + " --outcome " + string(o)),
			}
			b.WriteString("| " + strings.Join(cells, " | ") + " |\n")
		}
	}
	return b.String()
}

func optionalCode(s string) string {
	if s == "" {
		return ""
	}
	return code(s)
}
