// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cabals.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const findCabal = `-- name: FindCabal :one
SELECT c.id, c.name, c.picture_url, c.creator_id, c.join_mode, c.voter_mode, c.threshold,
  c.proposal_expiry_seconds, c.slippage_bps, c.invite_code, c.status, c.created_at, c.updated_at,
  (SELECT count(*) FROM cabal_members m WHERE m.cabal_id = c.id)::int AS member_count
FROM cabals c
WHERE c.id = $1
`

type FindCabalRow struct {
	ID                    uuid.UUID
	Name                  string
	PictureUrl            pgtype.Text
	CreatorID             uuid.UUID
	JoinMode              string
	VoterMode             string
	Threshold             string
	ProposalExpirySeconds int32
	SlippageBps           int32
	InviteCode            string
	Status                string
	CreatedAt             time.Time
	UpdatedAt             time.Time
	MemberCount           int32
}

func (q *Queries) FindCabal(ctx context.Context, id uuid.UUID) (FindCabalRow, error) {
	row := q.db.QueryRow(ctx, findCabal, id)
	var i FindCabalRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PictureUrl,
		&i.CreatorID,
		&i.JoinMode,
		&i.VoterMode,
		&i.Threshold,
		&i.ProposalExpirySeconds,
		&i.SlippageBps,
		&i.InviteCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MemberCount,
	)
	return i, err
}

const findCabalByInviteCode = `-- name: FindCabalByInviteCode :one
SELECT c.id, c.name, c.picture_url, c.creator_id, c.join_mode, c.voter_mode, c.threshold,
  c.proposal_expiry_seconds, c.slippage_bps, c.invite_code, c.status, c.created_at, c.updated_at,
  (SELECT count(*) FROM cabal_members m WHERE m.cabal_id = c.id)::int AS member_count
FROM cabals c
WHERE c.invite_code = $1
`

type FindCabalByInviteCodeRow struct {
	ID                    uuid.UUID
	Name                  string
	PictureUrl            pgtype.Text
	CreatorID             uuid.UUID
	JoinMode              string
	VoterMode             string
	Threshold             string
	ProposalExpirySeconds int32
	SlippageBps           int32
	InviteCode            string
	Status                string
	CreatedAt             time.Time
	UpdatedAt             time.Time
	MemberCount           int32
}

func (q *Queries) FindCabalByInviteCode(ctx context.Context, inviteCode string) (FindCabalByInviteCodeRow, error) {
	row := q.db.QueryRow(ctx, findCabalByInviteCode, inviteCode)
	var i FindCabalByInviteCodeRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PictureUrl,
		&i.CreatorID,
		&i.JoinMode,
		&i.VoterMode,
		&i.Threshold,
		&i.ProposalExpirySeconds,
		&i.SlippageBps,
		&i.InviteCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MemberCount,
	)
	return i, err
}

const insertCabal = `-- name: InsertCabal :execrows
INSERT INTO cabals (id, name, creator_id, join_mode, voter_mode, threshold, proposal_expiry_seconds, slippage_bps,
  invite_code, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5,
  $6, $7, $8, $9,
  $10, $10)
ON CONFLICT (invite_code) DO NOTHING
`

type InsertCabalParams struct {
	ID                    uuid.UUID
	Name                  string
	CreatorID             uuid.UUID
	JoinMode              string
	VoterMode             string
	Threshold             string
	ProposalExpirySeconds int32
	SlippageBps           int32
	InviteCode            string
	Now                   time.Time
}

func (q *Queries) InsertCabal(ctx context.Context, arg InsertCabalParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertCabal,
		arg.ID,
		arg.Name,
		arg.CreatorID,
		arg.JoinMode,
		arg.VoterMode,
		arg.Threshold,
		arg.ProposalExpirySeconds,
		arg.SlippageBps,
		arg.InviteCode,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCabals = `-- name: ListCabals :many
SELECT c.id, c.name, c.picture_url, c.creator_id, c.join_mode, c.voter_mode, c.threshold,
  c.proposal_expiry_seconds, c.slippage_bps, c.invite_code, c.status, c.created_at, c.updated_at,
  (SELECT count(*) FROM cabal_members m WHERE m.cabal_id = c.id)::int AS member_count
FROM cabals c
WHERE c.id = ANY($1::uuid[])
ORDER BY c.created_at, c.id
`

type ListCabalsRow struct {
	ID                    uuid.UUID
	Name                  string
	PictureUrl            pgtype.Text
	CreatorID             uuid.UUID
	JoinMode              string
	VoterMode             string
	Threshold             string
	ProposalExpirySeconds int32
	SlippageBps           int32
	InviteCode            string
	Status                string
	CreatedAt             time.Time
	UpdatedAt             time.Time
	MemberCount           int32
}

func (q *Queries) ListCabals(ctx context.Context, cabalIds []uuid.UUID) ([]ListCabalsRow, error) {
	rows, err := q.db.Query(ctx, listCabals, cabalIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCabalsRow
	for rows.Next() {
		var i ListCabalsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PictureUrl,
			&i.CreatorID,
			&i.JoinMode,
			&i.VoterMode,
			&i.Threshold,
			&i.ProposalExpirySeconds,
			&i.SlippageBps,
			&i.InviteCode,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCabalExclusive = `-- name: LockCabalExclusive :one
SELECT id FROM cabals WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockCabalExclusive(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockCabalExclusive, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const lockCabalShared = `-- name: LockCabalShared :one
SELECT id FROM cabals WHERE id = $1 FOR SHARE
`

func (q *Queries) LockCabalShared(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockCabalShared, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const setCabalPicture = `-- name: SetCabalPicture :execrows
UPDATE cabals SET picture_url = $1, updated_at = $2
WHERE id = $3
`

type SetCabalPictureParams struct {
	PictureUrl pgtype.Text
	Now        time.Time
	ID         uuid.UUID
}

func (q *Queries) SetCabalPicture(ctx context.Context, arg SetCabalPictureParams) (int64, error) {
	result, err := q.db.Exec(ctx, setCabalPicture, arg.PictureUrl, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCabal = `-- name: UpdateCabal :execrows
UPDATE cabals SET name = $1, join_mode = $2, voter_mode = $3,
  threshold = $4, proposal_expiry_seconds = $5,
  slippage_bps = $6, updated_at = $7
WHERE id = $8
`

type UpdateCabalParams struct {
	Name                  string
	JoinMode              string
	VoterMode             string
	Threshold             string
	ProposalExpirySeconds int32
	SlippageBps           int32
	Now                   time.Time
	ID                    uuid.UUID
}

func (q *Queries) UpdateCabal(ctx context.Context, arg UpdateCabalParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCabal,
		arg.Name,
		arg.JoinMode,
		arg.VoterMode,
		arg.Threshold,
		arg.ProposalExpirySeconds,
		arg.SlippageBps,
		arg.Now,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
