// Code generated by cmd/gen flows from packages/flows/backend. DO NOT EDIT.

public enum Flow01eOutcome: Sendable, Hashable, CaseIterable {
    case ok, accountHasPositions, accountHasBalance, interrupted

    public static let flowID = "01e"
    public static let commands: [String] = ["DeleteAccount"]

    public var code: String? {
        switch self {
        case .ok, .interrupted: nil
        case .accountHasPositions: "account_has_positions"
        case .accountHasBalance: "account_has_balance"
        }
    }

    public init?(code: String) {
        switch code {
        case "account_has_positions": self = .accountHasPositions
        case "account_has_balance": self = .accountHasBalance
        default: return nil
        }
    }
}
