// Code generated by monacoctl gen flows from packages/flows/backend. DO NOT EDIT.

public enum Flow10Outcome: Sendable, Hashable, CaseIterable {
    case ok, unauthorized, proposalNotFound, notAVoter, proposalClosed, interrupted

    public static let flowID = "10"
    public static let commands: [String] = ["CastVote"]

    public var code: String? {
        switch self {
        case .ok, .interrupted: nil
        case .unauthorized: "unauthorized"
        case .proposalNotFound: "proposal_not_found"
        case .notAVoter: "not_a_voter"
        case .proposalClosed: "proposal_closed"
        }
    }

    public init?(code: String) {
        switch code {
        case "unauthorized": self = .unauthorized
        case "proposal_not_found": self = .proposalNotFound
        case "not_a_voter": self = .notAVoter
        case "proposal_closed": self = .proposalClosed
        default: return nil
        }
    }
}
