// Code generated by cmd/gen flows from packages/flows/backend. DO NOT EDIT.

public enum Flow08Outcome: Sendable, Hashable, CaseIterable {
    case ok, dust, unknownAsset, bounceFailed, interrupted

    public static let flowID = "08"
    public static let commands: [String] = ["DetectExternalDeposit"]

    public var code: String? {
        switch self {
        case .ok, .interrupted: nil
        case .dust: "dust"
        case .unknownAsset: "unknown_asset"
        case .bounceFailed: "bounce_failed"
        }
    }

    public init?(code: String) {
        switch code {
        case "dust": self = .dust
        case "unknown_asset": self = .unknownAsset
        case "bounce_failed": self = .bounceFailed
        default: return nil
        }
    }
}
