// Code generated by cmd/gen flows from packages/flows/backend. DO NOT EDIT.

public enum Flow05Outcome: Sendable, Hashable, CaseIterable {
    case ok, rPCUnavailable, interrupted

    public static let flowID = "05"
    public static let commands: [String] = ["CreditDeposit"]

    public var code: String? {
        switch self {
        case .ok, .interrupted: nil
        case .rPCUnavailable: "rpc_unavailable"
        }
    }

    public init?(code: String) {
        switch code {
        case "rpc_unavailable": self = .rPCUnavailable
        default: return nil
        }
    }
}
