// Code generated by monacoctl gen flows from packages/flows/backend. DO NOT EDIT.

public enum Flow28Outcome: Sendable, Hashable, CaseIterable {
    case ok, interrupted

    public static let flowID = "28"
    public static let commands: [String] = ["EmitNudges"]

    public var code: String? {
        switch self {
        case .ok, .interrupted: nil
        }
    }

    public init?(code: String) {
        switch code {
        default: return nil
        }
    }
}
