// Code generated by cmd/gen flows from packages/flows/backend. DO NOT EDIT.

public enum Flow27Outcome: Sendable, Hashable, CaseIterable {
    case ok, deadLetterNotOpen, notFound, adminForbidden

    public static let flowID = "27"
    public static let commands: [String] = ["RecordDeadLetter", "RedriveDeadLetter", "DiscardDeadLetter"]

    public var code: String? {
        switch self {
        case .ok: nil
        case .deadLetterNotOpen: "dead_letter_not_open"
        case .notFound: "not_found"
        case .adminForbidden: "admin_forbidden"
        }
    }

    public init?(code: String) {
        switch code {
        case "dead_letter_not_open": self = .deadLetterNotOpen
        case "not_found": self = .notFound
        case "admin_forbidden": self = .adminForbidden
        default: return nil
        }
    }
}
