// Code generated by cmd/gen flows from packages/flows/backend. DO NOT EDIT.

public enum Flow03Outcome: Sendable, Hashable, CaseIterable {
    case ok, invalidInput, unauthorized, cabalNotFound, cabalBanned, alreadyMember, joinNeedsRequest, requestNotNeeded,
        requestPending, notCabalCreator, accessRequestNotPending, cannotRevokeAccess, userNotFound, inviteExpired,
        notCabalMember

    public static let flowID = "03"
    public static let commands: [String] = ["JoinCabal", "RequestAccess", "DecideAccess", "RevokeAccess", "InviteMember"]

    public var code: String? {
        switch self {
        case .ok: nil
        case .invalidInput: "invalid_input"
        case .unauthorized: "unauthorized"
        case .cabalNotFound: "cabal_not_found"
        case .cabalBanned: "cabal_banned"
        case .alreadyMember: "already_member"
        case .joinNeedsRequest: "join_needs_request"
        case .requestNotNeeded: "request_not_needed"
        case .requestPending: "request_pending"
        case .notCabalCreator: "not_cabal_creator"
        case .accessRequestNotPending: "access_request_not_pending"
        case .cannotRevokeAccess: "cannot_revoke_access"
        case .userNotFound: "user_not_found"
        case .inviteExpired: "invite_expired"
        case .notCabalMember: "not_cabal_member"
        }
    }

    public init?(code: String) {
        switch code {
        case "invalid_input": self = .invalidInput
        case "unauthorized": self = .unauthorized
        case "cabal_not_found": self = .cabalNotFound
        case "cabal_banned": self = .cabalBanned
        case "already_member": self = .alreadyMember
        case "join_needs_request": self = .joinNeedsRequest
        case "request_not_needed": self = .requestNotNeeded
        case "request_pending": self = .requestPending
        case "not_cabal_creator": self = .notCabalCreator
        case "access_request_not_pending": self = .accessRequestNotPending
        case "cannot_revoke_access": self = .cannotRevokeAccess
        case "user_not_found": self = .userNotFound
        case "invite_expired": self = .inviteExpired
        case "not_cabal_member": self = .notCabalMember
        default: return nil
        }
    }
}
