// Code generated by cmd/gen flows from packages/flows/backend. DO NOT EDIT.

public enum Flow29Outcome: Sendable, Hashable, CaseIterable {
    case ok, sameApprover, cabalNotActive, approvalExpired, interrupted

    public static let flowID = "29"
    public static let commands: [String] = ["RequestCabalBan", "ApproveCabalBan"]

    public var code: String? {
        switch self {
        case .ok, .interrupted: nil
        case .sameApprover: "same_approver"
        case .cabalNotActive: "cabal_not_active"
        case .approvalExpired: "approval_expired"
        }
    }

    public init?(code: String) {
        switch code {
        case "same_approver": self = .sameApprover
        case "cabal_not_active": self = .cabalNotActive
        case "approval_expired": self = .approvalExpired
        default: return nil
        }
    }
}
