// Code generated by monacoctl gen flows from apps/backend/flows.tsv. DO NOT EDIT.

public enum Flow23aOutcome: Sendable, Hashable, CaseIterable {
    case ok, photoInvalid, storageUnavailable, rateLimited

    public static let flowID = "23a"
    public static let command = "UploadProfilePhoto"

    public var code: String? {
        switch self {
        case .ok: nil
        case .photoInvalid: "photo_invalid"
        case .storageUnavailable: "storage_unavailable"
        case .rateLimited: "rate_limited"
        }
    }

    public init?(code: String) {
        switch code {
        case "photo_invalid": self = .photoInvalid
        case "storage_unavailable": self = .storageUnavailable
        case "rate_limited": self = .rateLimited
        default: return nil
        }
    }
}
