// Code generated by cmd/gen flows from packages/flows/backend. DO NOT EDIT.

public enum Flow22Outcome: Sendable, Hashable, CaseIterable {
    case ok, notCabalMember, unauthorized, interrupted

    public static let flowID = "22"
    public static let commands: [String] = []

    public var code: String? {
        switch self {
        case .ok, .interrupted: nil
        case .notCabalMember: "not_cabal_member"
        case .unauthorized: "unauthorized"
        }
    }

    public init?(code: String) {
        switch code {
        case "not_cabal_member": self = .notCabalMember
        case "unauthorized": self = .unauthorized
        default: return nil
        }
    }
}
