// Code generated by cmd/gen flows from packages/flows/backend. DO NOT EDIT.

public enum Flow24Outcome: Sendable, Hashable, CaseIterable {
    case ok, aPNSUnavailable, aPNSAuthFailed, interrupted

    public static let flowID = "24"
    public static let commands: [String] = ["Notify"]

    public var code: String? {
        switch self {
        case .ok, .interrupted: nil
        case .aPNSUnavailable: "apns_unavailable"
        case .aPNSAuthFailed: "apns_auth_failed"
        }
    }

    public init?(code: String) {
        switch code {
        case "apns_unavailable": self = .aPNSUnavailable
        case "apns_auth_failed": self = .aPNSAuthFailed
        default: return nil
        }
    }
}
