// Code generated by monacoctl gen flows from apps/backend/flows.tsv. DO NOT EDIT.

public enum Flow02Outcome: Sendable, Hashable, CaseIterable {
    case ok, invalidInput, unauthorized, privyUnavailable, interrupted

    public static let flowID = "02"
    public static let command = "CreateCabal"

    public var code: String? {
        switch self {
        case .ok, .interrupted: nil
        case .invalidInput: "invalid_input"
        case .unauthorized: "unauthorized"
        case .privyUnavailable: "privy_unavailable"
        }
    }

    public init?(code: String) {
        switch code {
        case "invalid_input": self = .invalidInput
        case "unauthorized": self = .unauthorized
        case "privy_unavailable": self = .privyUnavailable
        default: return nil
        }
    }
}
