// Code generated by cmd/gen flows from packages/flows/backend. DO NOT EDIT.

public enum Flow13Outcome: Sendable, Hashable, CaseIterable {
    case ok, unauthorized, proposalNotFound, notProposer, proposalClosed, withdrawNotAllowed, interrupted

    public static let flowID = "13"
    public static let commands: [String] = ["WithdrawProposal"]

    public var code: String? {
        switch self {
        case .ok, .interrupted: nil
        case .unauthorized: "unauthorized"
        case .proposalNotFound: "proposal_not_found"
        case .notProposer: "not_proposer"
        case .proposalClosed: "proposal_closed"
        case .withdrawNotAllowed: "withdraw_not_allowed"
        }
    }

    public init?(code: String) {
        switch code {
        case "unauthorized": self = .unauthorized
        case "proposal_not_found": self = .proposalNotFound
        case "not_proposer": self = .notProposer
        case "proposal_closed": self = .proposalClosed
        case "withdraw_not_allowed": self = .withdrawNotAllowed
        default: return nil
        }
    }
}
