// Code generated by monacoctl gen flows from apps/backend/flows.tsv. DO NOT EDIT.

public enum Flow00Outcome: Sendable, Hashable, CaseIterable {
    case ok, invalidInput, unauthorized, interrupted

    public static let flowID = "00"
    public static let commands: [String] = ["RecordPing"]

    public var code: String? {
        switch self {
        case .ok, .interrupted: nil
        case .invalidInput: "invalid_input"
        case .unauthorized: "unauthorized"
        }
    }

    public init?(code: String) {
        switch code {
        case "invalid_input": self = .invalidInput
        case "unauthorized": self = .unauthorized
        default: return nil
        }
    }
}
