#!/bin/sh
while [ "$#" -gt 1 ]; do
  [ "$1" = --output ] && out="$2"
  shift
done
case "$1" in
  ./a) status=LIVED ;;
  ./slow) status="TIMED OUT" ;;
  ./broken) echo "gremlins exploded" >&2; exit 3 ;;
  ./garbled) echo "not json" > "$out"; exit 0 ;;
  ./silent) exit 0 ;;
  *) status=KILLED ;;
esac
printf '{"files":[{"file_name":"x.go","mutations":[{"type":"CONDITIONALS_NEGATION","status":"%s","line":3,"column":5},{"type":"ARITHMETIC_BASE","status":"NOT COVERED","line":4,"column":2}]}]}' "$status" > "$out"
