//go:build go1.22

// Package adminapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by cmd/gen httpapi from api/spec/*.yaml. DO NOT EDIT.
package adminapi

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	rawjson "encoding/json"

	externalRef0 "github.com/monaco/monaco/apps/backend/internal/platform/httpx/api"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AdminAccountStatus.
const (
	AdminAccountStatusActive    AdminAccountStatus = "active"
	AdminAccountStatusBanned    AdminAccountStatus = "banned"
	AdminAccountStatusDeleted   AdminAccountStatus = "deleted"
	AdminAccountStatusSuspended AdminAccountStatus = "suspended"
)

// Valid indicates whether the value is a known member of the AdminAccountStatus enum.
func (e AdminAccountStatus) Valid() bool {
	switch e {
	case AdminAccountStatusActive:
		return true
	case AdminAccountStatusBanned:
		return true
	case AdminAccountStatusDeleted:
		return true
	case AdminAccountStatusSuspended:
		return true
	default:
		return false
	}
}

// Defines values for AdminActionKind.
const (
	CabalBan       AdminActionKind = "cabal_ban"
	CommentRemove  AdminActionKind = "comment_remove"
	GlobalPause    AdminActionKind = "global_pause"
	GlobalResume   AdminActionKind = "global_resume"
	HandleReassign AdminActionKind = "handle_reassign"
	HandleRevoke   AdminActionKind = "handle_revoke"
	OpsPause       AdminActionKind = "ops_pause"
	OpsResume      AdminActionKind = "ops_resume"
	PingFlag       AdminActionKind = "ping_flag"
	ProposalVoid   AdminActionKind = "proposal_void"
	UserBan        AdminActionKind = "user_ban"
	UserUnban      AdminActionKind = "user_unban"
)

// Valid indicates whether the value is a known member of the AdminActionKind enum.
func (e AdminActionKind) Valid() bool {
	switch e {
	case CabalBan:
		return true
	case CommentRemove:
		return true
	case GlobalPause:
		return true
	case GlobalResume:
		return true
	case HandleReassign:
		return true
	case HandleRevoke:
		return true
	case OpsPause:
		return true
	case OpsResume:
		return true
	case PingFlag:
		return true
	case ProposalVoid:
		return true
	case UserBan:
		return true
	case UserUnban:
		return true
	default:
		return false
	}
}

// Defines values for AdminAuthState.
const (
	AWAITINGPHONE       AdminAuthState = "AWAITING_PHONE"
	AWAITINGSOCIALS     AdminAuthState = "AWAITING_SOCIALS"
	CREATED             AdminAuthState = "CREATED"
	ONBOARDINGCOMPLETED AdminAuthState = "ONBOARDING_COMPLETED"
)

// Valid indicates whether the value is a known member of the AdminAuthState enum.
func (e AdminAuthState) Valid() bool {
	switch e {
	case AWAITINGPHONE:
		return true
	case AWAITINGSOCIALS:
		return true
	case CREATED:
		return true
	case ONBOARDINGCOMPLETED:
		return true
	default:
		return false
	}
}

// Defines values for AdminCabalStatus.
const (
	AdminCabalStatusActive AdminCabalStatus = "active"
	AdminCabalStatusBanned AdminCabalStatus = "banned"
)

// Valid indicates whether the value is a known member of the AdminCabalStatus enum.
func (e AdminCabalStatus) Valid() bool {
	switch e {
	case AdminCabalStatusActive:
		return true
	case AdminCabalStatusBanned:
		return true
	default:
		return false
	}
}

// Defines values for AdminRole.
const (
	Moderator AdminRole = "moderator"
	Operator  AdminRole = "operator"
	Viewer    AdminRole = "viewer"
)

// Valid indicates whether the value is a known member of the AdminRole enum.
func (e AdminRole) Valid() bool {
	switch e {
	case Moderator:
		return true
	case Operator:
		return true
	case Viewer:
		return true
	default:
		return false
	}
}

// Defines values for AdminTargetType.
const (
	AdminTargetTypeCabal      AdminTargetType = "cabal"
	AdminTargetTypeComment    AdminTargetType = "comment"
	AdminTargetTypeGlobal     AdminTargetType = "global"
	AdminTargetTypeHandle     AdminTargetType = "handle"
	AdminTargetTypeProposal   AdminTargetType = "proposal"
	AdminTargetTypeSystemPing AdminTargetType = "system_ping"
	AdminTargetTypeUser       AdminTargetType = "user"
)

// Valid indicates whether the value is a known member of the AdminTargetType enum.
func (e AdminTargetType) Valid() bool {
	switch e {
	case AdminTargetTypeCabal:
		return true
	case AdminTargetTypeComment:
		return true
	case AdminTargetTypeGlobal:
		return true
	case AdminTargetTypeHandle:
		return true
	case AdminTargetTypeProposal:
		return true
	case AdminTargetTypeSystemPing:
		return true
	case AdminTargetTypeUser:
		return true
	default:
		return false
	}
}

// Defines values for AdminTxnScope.
const (
	AdminTxnScopeCabal AdminTxnScope = "cabal"
	AdminTxnScopeUser  AdminTxnScope = "user"
)

// Valid indicates whether the value is a known member of the AdminTxnScope enum.
func (e AdminTxnScope) Valid() bool {
	switch e {
	case AdminTxnScopeCabal:
		return true
	case AdminTxnScopeUser:
		return true
	default:
		return false
	}
}

// Defines values for DeadLetterStatus.
const (
	Discarded DeadLetterStatus = "discarded"
	Open      DeadLetterStatus = "open"
	Redriven  DeadLetterStatus = "redriven"
	Resolved  DeadLetterStatus = "resolved"
)

// Valid indicates whether the value is a known member of the DeadLetterStatus enum.
func (e DeadLetterStatus) Valid() bool {
	switch e {
	case Discarded:
		return true
	case Open:
		return true
	case Redriven:
		return true
	case Resolved:
		return true
	default:
		return false
	}
}

// AdminAccountStatus Whether the account may be used.
//
// Examples: active
type AdminAccountStatus string

// AdminActionKind What the administrator did.
//
// Examples: ping_flag
type AdminActionKind string

// AdminActionRecord One audited admin action.
//
// Examples: {"action":"ping_flag","admin_id":"01890a5d-ac96-774b-bcce-b302099a8059","after":{"flagged_at":"2026-10-06T12:00:00Z"},"approved_by":null,"before":{"flagged_at":null},"created_at":"2026-10-06T12:00:00Z","id":"01890a5d-ac96-774b-bcce-b302099a805a","reason":"spam","target_id":"01890a5d-ac96-774b-bcce-b302099a8057","target_type":"system_ping"}
type AdminActionRecord struct {
	// Action What the administrator did.
	//
	// Examples: ping_flag
	Action AdminActionKind `json:"action"`

	// AdminId The administrator who took the action.
	//
	// Examples: 01890a5d-ac96-774b-bcce-b302099a8059
	AdminId openapi_types.UUID `json:"admin_id"`

	// After The fields the action changed, as they are now. A JSON object, or null.
	//
	// Examples: {"flagged_at":"2026-10-06T12:00:00Z"}
	After *rawjson.RawMessage `json:"after"`

	// ApprovedBy The second administrator who approved the action. Null unless the action needs approval.
	//
	// Examples: null
	ApprovedBy *openapi_types.UUID `json:"approved_by"`

	// Before The fields the action changed, as they were before. A JSON object, or null when nothing existed.
	//
	// Examples: {"flagged_at":null}
	Before *rawjson.RawMessage `json:"before"`

	// CreatedAt When the audit consumer recorded the action.
	//
	// Examples: 2026-10-06T12:00:00Z
	CreatedAt time.Time `json:"created_at"`

	// Id The action id. Ids sort by time, so a later action has a greater id.
	//
	// Examples: 01890a5d-ac96-774b-bcce-b302099a805a
	Id openapi_types.UUID `json:"id"`

	// Reason The reason the administrator gave.
	//
	// Examples: spam
	Reason string `json:"reason"`

	// TargetId The id of the target. Its format depends on `target_type`.
	//
	// Examples: 01890a5d-ac96-774b-bcce-b302099a8057
	TargetId string `json:"target_id"`

	// TargetType The kind of thing the action changed.
	//
	// Examples: system_ping
	TargetType AdminTargetType `json:"target_type"`
}

// AdminActions One page of admin actions, newest first.
//
// Examples: {"items":[],"next_cursor":null}
type AdminActions struct {
	// Items The actions on this page.
	Items []AdminActionRecord `json:"items"`

	// NextCursor Pass it as `cursor` to read the next page. Null on the last page.
	//
	// Examples: null
	NextCursor *openapi_types.UUID `json:"next_cursor"`
}

// AdminAuthState Where the user stands in onboarding.
//
// Examples: ONBOARDING_COMPLETED
type AdminAuthState string

// AdminAuthTransition One change of auth state, read from a user.auth_state_changed event.
//
// Examples: {"at":"2026-10-06T12:00:00Z","cause":"otp_sent","from":"CREATED","to":"AWAITING_PHONE"}
type AdminAuthTransition struct {
	// At When the user moved.
	//
	// Examples: 2026-10-06T12:00:00Z
	At time.Time `json:"at"`

	// Cause What moved the user.
	//
	// Examples: otp_sent
	Cause string `json:"cause"`

	// From The state the user left.
	//
	// Examples: CREATED
	From string `json:"from"`

	// To The state the user entered.
	//
	// Examples: AWAITING_PHONE
	To string `json:"to"`
}

// AdminCabal One cabal as an operator sees them.
//
// Examples: {"created_at":"2026-10-06T12:00:00Z","creator_id":"019cc330-1111-7000-8000-000000000001","id":"019cc330-2222-7000-8000-000000000001","member_count":1,"members":[],"name":"Tech bros","positions":[],"recent_admin_actions":[],"recent_txns":[],"rules":{"join_mode":"open","proposal_expiry_seconds":86400,"slippage_bps":100,"threshold":"majority","voter_mode":"all"},"status":"active","treasury_address":"9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin"}
type AdminCabal struct {
	// CreatedAt When the cabal was created.
	//
	// Examples: 2026-10-06T12:00:00Z
	CreatedAt time.Time `json:"created_at"`

	// CreatorId The user who created the cabal.
	//
	// Examples: 019cc330-1111-7000-8000-000000000001
	CreatorId openapi_types.UUID `json:"creator_id"`

	// Id The cabal id.
	//
	// Examples: 019cc330-2222-7000-8000-000000000001
	Id openapi_types.UUID `json:"id"`

	// MemberCount How many members the cabal has.
	//
	// Examples: 1
	MemberCount int64 `json:"member_count"`

	// Members Every member, oldest first.
	Members []AdminCabalMember `json:"members"`

	// Name The cabal name.
	//
	// Examples: Tech bros
	Name string `json:"name"`

	// Positions The tokens the treasury holds, USDC included. A mint the catalog does not list has a null symbol.
	Positions []AdminHolding `json:"positions"`

	// RecentAdminActions The 20 newest admin actions on the cabal, newest first.
	RecentAdminActions []AdminActionRecord `json:"recent_admin_actions"`

	// RecentTxns The 20 newest ledger transactions of the cabal, newest first.
	RecentTxns []AdminTxnHeader `json:"recent_txns"`

	// Rules The rules the cabal runs on.
	//
	// Examples: {"join_mode":"open","proposal_expiry_seconds":86400,"slippage_bps":100,"threshold":"majority","voter_mode":"all"}
	Rules AdminCabalRules `json:"rules"`

	// Status Whether the cabal may trade.
	//
	// Examples: active
	Status AdminCabalStatus `json:"status"`

	// TreasuryAddress The Solana address of the cabal treasury.
	//
	// Examples: 9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin
	TreasuryAddress string `json:"treasury_address"`
}

// AdminCabalMember One member of a cabal with the shares they hold.
//
// Examples: {"can_vote":true,"handle":"devadmin","joined_at":"2026-10-06T12:00:00Z","role":"creator","share_units":"25000000","user_id":"019cc330-1111-7000-8000-000000000001"}
type AdminCabalMember struct {
	// CanVote Whether the member votes on proposals.
	//
	// Examples: true
	CanVote bool `json:"can_vote"`

	// Handle The handle. Null before the user picks one.
	//
	// Examples: devadmin
	Handle *string `json:"handle"`

	// JoinedAt When the member joined.
	//
	// Examples: 2026-10-06T12:00:00Z
	JoinedAt time.Time `json:"joined_at"`

	// Role The role: creator or member.
	//
	// Examples: creator
	Role string `json:"role"`

	// ShareUnits The share units as a decimal integer. Zero for a member without a stake.
	//
	// Examples: 25000000
	ShareUnits string `json:"share_units"`

	// UserId The user id.
	//
	// Examples: 019cc330-1111-7000-8000-000000000001
	UserId openapi_types.UUID `json:"user_id"`
}

// AdminCabalRef A cabal named by id.
//
// Examples: {"id":"019cc330-2222-7000-8000-000000000001","name":"Tech bros"}
type AdminCabalRef struct {
	// Id The cabal id.
	//
	// Examples: 019cc330-2222-7000-8000-000000000001
	Id openapi_types.UUID `json:"id"`

	// Name The cabal name.
	//
	// Examples: Tech bros
	Name string `json:"name"`
}

// AdminCabalRules The rules the cabal runs on.
//
// Examples: {"join_mode":"open","proposal_expiry_seconds":86400,"slippage_bps":100,"threshold":"majority","voter_mode":"all"}
type AdminCabalRules struct {
	// JoinMode How people join: open or request.
	//
	// Examples: open
	JoinMode string `json:"join_mode"`

	// ProposalExpirySeconds How long a proposal stays open.
	//
	// Examples: 86400
	ProposalExpirySeconds int64 `json:"proposal_expiry_seconds"`

	// SlippageBps The slippage the cabal accepts, in basis points.
	//
	// Examples: 100
	SlippageBps int32 `json:"slippage_bps"`

	// Threshold What passes a proposal: majority or unanimous.
	//
	// Examples: majority
	Threshold string `json:"threshold"`

	// VoterMode Who votes: all or list.
	//
	// Examples: all
	VoterMode string `json:"voter_mode"`
}

// AdminCabalStatus Whether the cabal may trade.
//
// Examples: active
type AdminCabalStatus string

// AdminHolding One token the cabal treasury holds.
//
// Examples: {"mint":"XsbEhLAtcf6HdfpFZ5xEMdqW8nfAvcsP5bdudRLJzJp","symbol":"AAPLx","units":"300000000"}
type AdminHolding struct {
	// Mint The token mint address.
	//
	// Examples: XsbEhLAtcf6HdfpFZ5xEMdqW8nfAvcsP5bdudRLJzJp
	Mint string `json:"mint"`

	// Symbol The catalog symbol. Null for a mint the catalog does not list.
	//
	// Examples: AAPLx
	Symbol *string `json:"symbol"`

	// Units The base units held, as a decimal integer.
	//
	// Examples: 300000000
	Units string `json:"units"`
}

// AdminLedgerTxn One ledger transaction with its entries.
//
// Examples: {"cabal_id":"019cc330-2222-7000-8000-000000000001","created_at":"2026-10-06T12:00:00Z","entries":[],"id":"019cc330-3333-7000-8000-000000000001","kind":"swap","scope":"cabal","status":"settled","swap_id":"019cc330-4444-7000-8000-000000000001","transfer_id":null,"tx_signature":null,"user_id":null}
type AdminLedgerTxn struct {
	// CabalId The cabal the transaction touches. Null for a deposit or withdrawal.
	//
	// Examples: 019cc330-2222-7000-8000-000000000001
	CabalId *openapi_types.UUID `json:"cabal_id"`

	// CreatedAt When the ledger recorded it.
	//
	// Examples: 2026-10-06T12:00:00Z
	CreatedAt time.Time `json:"created_at"`

	// Entries The entries of the transaction, in order.
	Entries []AdminTxnEntry `json:"entries"`

	// Id The transaction id.
	//
	// Examples: 019cc330-3333-7000-8000-000000000001
	Id openapi_types.UUID `json:"id"`

	// Kind The kind: deposit, withdrawal, fund, cash_out or swap.
	//
	// Examples: swap
	Kind string `json:"kind"`

	// Scope Which ledger the transaction sits in.
	//
	// Examples: user
	Scope AdminTxnScope `json:"scope"`

	// Status The status: pending, settled or failed.
	//
	// Examples: settled
	Status string `json:"status"`

	// SwapId The swap a cabal-scope swap transaction records. Null otherwise.
	//
	// Examples: 019cc330-4444-7000-8000-000000000001
	SwapId *openapi_types.UUID `json:"swap_id"`

	// TransferId The fund or withdrawal transfer that links a user and a cabal transaction.
	//
	// Examples: null
	TransferId *openapi_types.UUID `json:"transfer_id"`

	// TxSignature The Solana signature. Null until the transaction has one.
	//
	// Examples: null
	TxSignature *string `json:"tx_signature"`

	// UserId The user of a user-scope transaction. Null in the cabal scope.
	//
	// Examples: null
	UserId *openapi_types.UUID `json:"user_id"`
}

// AdminMe An active administrator and their role.
//
// Examples: {"role":"operator","user_id":"019cc330-1111-7000-8000-000000000001"}
type AdminMe struct {
	// Role The administrator's access level.
	//
	// Examples: operator
	Role AdminRole `json:"role"`

	// UserId The administrator's user id.
	//
	// Examples: 019cc330-1111-7000-8000-000000000001
	UserId openapi_types.UUID `json:"user_id"`
}

// AdminRole The administrator's access level.
//
// Examples: operator
type AdminRole string

// AdminSharePosition The share units a user holds in one cabal.
//
// Examples: {"cabal_id":"019cc330-2222-7000-8000-000000000001","share_units":"25000000"}
type AdminSharePosition struct {
	// CabalId The cabal id.
	//
	// Examples: 019cc330-2222-7000-8000-000000000001
	CabalId openapi_types.UUID `json:"cabal_id"`

	// ShareUnits The share units as a decimal integer.
	//
	// Examples: 25000000
	ShareUnits string `json:"share_units"`
}

// AdminSwap One swap with the history of its trade events.
//
// Examples: {"created_at":"2026-10-06T12:00:00Z","execute_request_id":"req-1","failure_code":null,"id":"019cc330-4444-7000-8000-000000000001","status":"submitted","status_history":[],"tx_signature":null}
type AdminSwap struct {
	// CreatedAt When the swap was created.
	//
	// Examples: 2026-10-06T12:00:00Z
	CreatedAt time.Time `json:"created_at"`

	// ExecuteRequestId The Jupiter execute request id. Null until the swap is submitted.
	//
	// Examples: req-1
	ExecuteRequestId *string `json:"execute_request_id"`

	// FailureCode Why the swap failed. Null unless it failed.
	//
	// Examples: null
	FailureCode *string `json:"failure_code"`

	// Id The swap id.
	//
	// Examples: 019cc330-4444-7000-8000-000000000001
	Id openapi_types.UUID `json:"id"`

	// Status The status: created, submitted, confirmed or failed.
	//
	// Examples: submitted
	Status string `json:"status"`

	// StatusHistory The trade events of the swap, oldest first.
	StatusHistory []AdminSwapEvent `json:"status_history"`

	// TxSignature The Solana signature. Null until the swap is submitted.
	//
	// Examples: null
	TxSignature *string `json:"tx_signature"`
}

// AdminSwapEvent One trade event of a swap.
//
// Examples: {"at":"2026-10-06T12:00:00Z","type":"trade.submitted"}
type AdminSwapEvent struct {
	// At When the event was recorded.
	//
	// Examples: 2026-10-06T12:00:00Z
	At time.Time `json:"at"`

	// Type The event type: trade.submitted, trade.confirmed or trade.failed.
	//
	// Examples: trade.submitted
	Type string `json:"type"`
}

// AdminTargetType The kind of thing the action changed.
//
// Examples: system_ping
type AdminTargetType string

// AdminTxn One transaction as an operator sees it. At least one of `ledger` and `swap` is present. `explorer_url` is present when a signature is known.
//
// Examples: {"explorer_url":"https://solscan.io/tx/5VERv8NMvzbJMEkV8xnrLkEaWRtSz9CosKDYjCJjBRnbJLgp8uirBgmQpjKhoR4tjF3ZpRzrFmBV6UjKdiSZkQUW"}
type AdminTxn struct {
	// ExplorerUrl The Solscan page of the signature on mainnet.
	//
	// Examples: https://solscan.io/tx/5VERv8NMvzbJMEkV8xnrLkEaWRtSz9CosKDYjCJjBRnbJLgp8uirBgmQpjKhoR4tjF3ZpRzrFmBV6UjKdiSZkQUW
	ExplorerUrl *string `json:"explorer_url,omitempty"`

	// Ledger One ledger transaction with its entries.
	//
	// Examples: {"cabal_id":"019cc330-2222-7000-8000-000000000001","created_at":"2026-10-06T12:00:00Z","entries":[],"id":"019cc330-3333-7000-8000-000000000001","kind":"swap","scope":"cabal","status":"settled","swap_id":"019cc330-4444-7000-8000-000000000001","transfer_id":null,"tx_signature":null,"user_id":null}
	Ledger *AdminLedgerTxn `json:"ledger,omitempty"`

	// Swap One swap with the history of its trade events.
	//
	// Examples: {"created_at":"2026-10-06T12:00:00Z","execute_request_id":"req-1","failure_code":null,"id":"019cc330-4444-7000-8000-000000000001","status":"submitted","status_history":[],"tx_signature":null}
	Swap *AdminSwap `json:"swap,omitempty"`
}

// AdminTxnEntry One signed line of a ledger transaction.
//
// Examples: {"account":"wallet","amount":"-10000000","asset":"EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v","seq":0}
type AdminTxnEntry struct {
	// Account The account the entry moves, such as wallet or treasury.
	//
	// Examples: wallet
	Account string `json:"account"`

	// Amount The signed amount in base units as a decimal integer.
	//
	// Examples: -10000000
	Amount string `json:"amount"`

	// Asset The asset moved: a mint address or a shares asset.
	//
	// Examples: EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
	Asset string `json:"asset"`

	// Seq The position of the entry in the transaction.
	//
	// Examples: 0
	Seq int32 `json:"seq"`
}

// AdminTxnHeader The header of one ledger transaction, without its entries.
//
// Examples: {"cabal_id":"019cc330-2222-7000-8000-000000000001","created_at":"2026-10-06T12:00:00Z","id":"019cc330-3333-7000-8000-000000000001","kind":"fund","scope":"user","status":"settled","tx_signature":null}
type AdminTxnHeader struct {
	// CabalId The cabal the transaction touches. Null for a deposit or withdrawal.
	//
	// Examples: 019cc330-2222-7000-8000-000000000001
	CabalId *openapi_types.UUID `json:"cabal_id"`

	// CreatedAt When the ledger recorded it.
	//
	// Examples: 2026-10-06T12:00:00Z
	CreatedAt time.Time `json:"created_at"`

	// Id The transaction id.
	//
	// Examples: 019cc330-3333-7000-8000-000000000001
	Id openapi_types.UUID `json:"id"`

	// Kind The kind: deposit, withdrawal, fund, cash_out or swap.
	//
	// Examples: fund
	Kind string `json:"kind"`

	// Scope Which ledger the transaction sits in.
	//
	// Examples: user
	Scope AdminTxnScope `json:"scope"`

	// Status The status: pending, settled or failed.
	//
	// Examples: settled
	Status string `json:"status"`

	// TxSignature The Solana signature. Null until the transaction has one.
	//
	// Examples: null
	TxSignature *string `json:"tx_signature"`
}

// AdminTxnScope Which ledger the transaction sits in.
//
// Examples: user
type AdminTxnScope string

// AdminUser One user as an operator sees them. It carries no email, phone number or X handle.
//
// Examples: {"account_status":"active","auth_state":"ONBOARDING_COMPLETED","auth_state_history":[],"cabals":[],"created_at":"2026-10-06T12:00:00Z","first_deposit_at":null,"handle":"devadmin","id":"019cc330-1111-7000-8000-000000000001","phone_verified":true,"positions":[],"recent_admin_actions":[],"recent_txns":[],"wallet":"9xQe…VFin","x_linked":false}
type AdminUser struct {
	// AccountStatus Whether the account may be used.
	//
	// Examples: active
	AccountStatus AdminAccountStatus `json:"account_status"`

	// AuthState Where the user stands in onboarding.
	//
	// Examples: ONBOARDING_COMPLETED
	AuthState AdminAuthState `json:"auth_state"`

	// AuthStateHistory Every auth state change, oldest first.
	AuthStateHistory []AdminAuthTransition `json:"auth_state_history"`

	// Cabals The cabals the user belongs to.
	Cabals []AdminCabalRef `json:"cabals"`

	// CreatedAt When the user signed up.
	//
	// Examples: 2026-10-06T12:00:00Z
	CreatedAt time.Time `json:"created_at"`

	// FirstDepositAt When the first deposit arrived. Null if none did.
	//
	// Examples: null
	FirstDepositAt *time.Time `json:"first_deposit_at"`

	// Handle The handle. Null before the user picks one.
	//
	// Examples: devadmin
	Handle *string `json:"handle"`

	// Id The user id.
	//
	// Examples: 019cc330-1111-7000-8000-000000000001
	Id openapi_types.UUID `json:"id"`

	// PhoneVerified Whether the user verified a phone number.
	//
	// Examples: true
	PhoneVerified bool `json:"phone_verified"`

	// Positions The cabals where the user holds shares.
	Positions []AdminSharePosition `json:"positions"`

	// RecentAdminActions The 20 newest admin actions on the user, newest first.
	RecentAdminActions []AdminActionRecord `json:"recent_admin_actions"`

	// RecentTxns The 20 newest ledger transactions of the user, newest first.
	RecentTxns []AdminTxnHeader `json:"recent_txns"`

	// Wallet The wallet address as its first four and last four characters. Null when the user has no wallet.
	//
	// Examples: 9xQe…VFin
	Wallet *string `json:"wallet"`

	// XLinked Whether the user linked an X account.
	//
	// Examples: false
	XLinked bool `json:"x_linked"`
}

// Admins The active administrator list.
//
// Examples: {"admins":[{"role":"operator","user_id":"019cc330-1111-7000-8000-000000000001"}]}
type Admins struct {
	// Admins Every non-revoked administrator.
	Admins []AdminMe `json:"admins"`
}

// DeadLetter One dead letter, without its stored message body.
//
// Examples: {"code":"posthog_rejected","consumer":"analytics","error":"posthog.Capture: posthog_rejected","event_id":"01890a5d-ac96-774b-bcce-b302099a8057","first_seen_at":"2026-10-06T12:00:00Z","handler":"analytics.posthog.follow.created","id":"01890a5d-ac96-774b-bcce-b302099a805a","last_seen_at":"2026-10-06T12:00:00Z","occurrences":1,"redriven_at":null,"resolve_reason":null,"resolved_at":null,"resolved_by":null,"status":"open","stream_seq":12,"subject":"events.follow.created"}
type DeadLetter struct {
	// Code The error code of the failure, or `max_deliveries`.
	//
	// Examples: posthog_rejected
	Code string `json:"code"`

	// Consumer The durable consumer that gave up on the message.
	//
	// Examples: analytics
	Consumer string `json:"consumer"`

	// Error The error text of the failure.
	//
	// Examples: posthog.Capture: posthog_rejected
	Error string `json:"error"`

	// EventId The id of the event. Null when the original event has left the stream.
	//
	// Examples: 01890a5d-ac96-774b-bcce-b302099a8057
	EventId *openapi_types.UUID `json:"event_id"`

	// FirstSeenAt When the sink first recorded the letter.
	//
	// Examples: 2026-10-06T12:00:00Z
	FirstSeenAt time.Time `json:"first_seen_at"`

	// Handler The handler that failed. Empty for a max-deliveries letter.
	//
	// Examples: analytics.posthog.follow.created
	Handler string `json:"handler"`

	// Id The dead letter id. Ids sort by time, so a later letter has a greater id.
	//
	// Examples: 01890a5d-ac96-774b-bcce-b302099a805a
	Id openapi_types.UUID `json:"id"`

	// LastSeenAt When the sink last recorded the letter.
	//
	// Examples: 2026-10-06T12:00:00Z
	LastSeenAt time.Time `json:"last_seen_at"`

	// Occurrences How many times the message ended in a dead letter, counting redrives that failed again.
	//
	// Examples: 1
	Occurrences int32 `json:"occurrences"`

	// RedrivenAt When an administrator last redrove the letter. Null if none did.
	//
	// Examples: null
	RedrivenAt *time.Time `json:"redriven_at"`

	// ResolveReason The reason that administrator gave. Null if none did.
	//
	// Examples: null
	ResolveReason *string `json:"resolve_reason"`

	// ResolvedAt When the letter was resolved or discarded. Null while it is open or redriven.
	//
	// Examples: null
	ResolvedAt *time.Time `json:"resolved_at"`

	// ResolvedBy The administrator who last redrove or discarded the letter. Null if none did.
	//
	// Examples: null
	ResolvedBy *openapi_types.UUID `json:"resolved_by"`

	// Status Where a dead letter stands in the queue.
	//
	// Examples: open
	Status DeadLetterStatus `json:"status"`

	// StreamSeq The sequence of the letter in the dead-letter stream, or of the latest one for a reopened row.
	//
	// Examples: 12
	StreamSeq int64 `json:"stream_seq"`

	// Subject The subject of the message. Empty when the original event has left the stream.
	//
	// Examples: events.follow.created
	Subject string `json:"subject"`
}

// DeadLetterStatus Where a dead letter stands in the queue.
//
// Examples: open
type DeadLetterStatus string

// DeadLetters One page of dead letters, newest first.
//
// Examples: {"items":[],"next_cursor":null}
type DeadLetters struct {
	// Items The letters on this page.
	Items []DeadLetter `json:"items"`

	// NextCursor Pass it as `cursor` to read the next page. Null on the last page.
	//
	// Examples: null
	NextCursor *openapi_types.UUID `json:"next_cursor"`
}

// GetAdminActionsParams defines parameters for GetAdminActions.
type GetAdminActionsParams struct {
	// AdminId Only actions taken by this administrator.
	AdminId *openapi_types.UUID `form:"admin_id,omitempty" json:"admin_id,omitempty"`

	// TargetType Only actions on this kind of target.
	TargetType *AdminTargetType `form:"target_type,omitempty" json:"target_type,omitempty"`

	// TargetId Only actions on the target with this id. Pair it with `target_type`.
	TargetId *string `form:"target_id,omitempty" json:"target_id,omitempty"`

	// Action Only actions of this kind.
	Action *AdminActionKind `form:"action,omitempty" json:"action,omitempty"`

	// Cursor The `next_cursor` of the previous page. Absent reads the first page.
	Cursor *openapi_types.UUID `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Page size. Defaults to 50 and cannot exceed 200.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetDeadLettersParams defines parameters for GetDeadLetters.
type GetDeadLettersParams struct {
	// Status Only letters in this state. Defaults to `open`.
	Status *DeadLetterStatus `form:"status,omitempty" json:"status,omitempty"`

	// Consumer Only letters of this consumer.
	Consumer *string `form:"consumer,omitempty" json:"consumer,omitempty"`

	// Cursor The `next_cursor` of the previous page. Absent reads the first page.
	Cursor *openapi_types.UUID `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Page size. Defaults to 50 and cannot exceed 200.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// DiscardDeadLetterParams defines parameters for DiscardDeadLetter.
type DiscardDeadLetterParams struct {
	// IdempotencyKey A key the app generates once per user action. The server stores the first response under it and replays that response for any retry with the same key and body.
	IdempotencyKey externalRef0.IdempotencyKey `json:"Idempotency-Key"`
}

// RedriveDeadLetterParams defines parameters for RedriveDeadLetter.
type RedriveDeadLetterParams struct {
	// IdempotencyKey A key the app generates once per user action. The server stores the first response under it and replays that response for any retry with the same key and body.
	IdempotencyKey externalRef0.IdempotencyKey `json:"Idempotency-Key"`
}

// FindAdminTxnParams defines parameters for FindAdminTxn.
type FindAdminTxnParams struct {
	// Signature The Solana transaction signature.
	Signature string `form:"signature" json:"signature"`
}

// FindAdminUserParams defines parameters for FindAdminUser.
type FindAdminUserParams struct {
	// Handle The handle of the user, without the at sign.
	Handle string `form:"handle" json:"handle"`
}

// DiscardDeadLetterJSONRequestBody defines body for DiscardDeadLetter for application/json ContentType.
type DiscardDeadLetterJSONRequestBody = externalRef0.ReasonBody

// RedriveDeadLetterJSONRequestBody defines body for RedriveDeadLetter for application/json ContentType.
type RedriveDeadLetterJSONRequestBody = externalRef0.ReasonBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetAdminActions List admin actions.
	// (GET /v1/admin/actions)
	GetAdminActions(w http.ResponseWriter, r *http.Request, params GetAdminActionsParams)
	// GetAdmins List current administrators.
	// (GET /v1/admin/admins)
	GetAdmins(w http.ResponseWriter, r *http.Request)
	// GetAdminCabal Look up a cabal by id.
	// (GET /v1/admin/cabals/{id})
	GetAdminCabal(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// GetDeadLetters List dead letters.
	// (GET /v1/admin/dead-letters)
	GetDeadLetters(w http.ResponseWriter, r *http.Request, params GetDeadLettersParams)
	// DiscardDeadLetter Discard a dead letter.
	// (POST /v1/admin/dead-letters/{id}/discard)
	DiscardDeadLetter(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params DiscardDeadLetterParams)
	// RedriveDeadLetter Redrive a dead letter.
	// (POST /v1/admin/dead-letters/{id}/redrive)
	RedriveDeadLetter(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params RedriveDeadLetterParams)
	// GetAdminMe Read the active administrator role.
	// (GET /v1/admin/me)
	GetAdminMe(w http.ResponseWriter, r *http.Request)
	// FindAdminTxn Look up a transaction by signature.
	// (GET /v1/admin/txns)
	FindAdminTxn(w http.ResponseWriter, r *http.Request, params FindAdminTxnParams)
	// GetAdminTxn Look up a transaction by id.
	// (GET /v1/admin/txns/{id})
	GetAdminTxn(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// FindAdminUser Look up a user by handle.
	// (GET /v1/admin/users)
	FindAdminUser(w http.ResponseWriter, r *http.Request, params FindAdminUserParams)
	// GetAdminUser Look up a user by id.
	// (GET /v1/admin/users/{id})
	GetAdminUser(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAdminActions operation middleware
func (siw *ServerInterfaceWrapper) GetAdminActions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAdminActionsParams

	// ------------- Optional query parameter "admin_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "admin_id", r.URL.Query(), &params.AdminId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "admin_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "admin_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "target_type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "target_type", r.URL.Query(), &params.TargetType, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "target_type"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "target_type", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "target_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "target_id", r.URL.Query(), &params.TargetId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "target_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "target_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "action" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "action", r.URL.Query(), &params.Action, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "action"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "action", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminActions(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdmins operation middleware
func (siw *ServerInterfaceWrapper) GetAdmins(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdmins(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminCabal operation middleware
func (siw *ServerInterfaceWrapper) GetAdminCabal(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminCabal(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDeadLetters operation middleware
func (siw *ServerInterfaceWrapper) GetDeadLetters(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDeadLettersParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "consumer" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "consumer", r.URL.Query(), &params.Consumer, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "consumer"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "consumer", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDeadLetters(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DiscardDeadLetter operation middleware
func (siw *ServerInterfaceWrapper) DiscardDeadLetter(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DiscardDeadLetterParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey externalRef0.IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DiscardDeadLetter(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RedriveDeadLetter operation middleware
func (siw *ServerInterfaceWrapper) RedriveDeadLetter(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params RedriveDeadLetterParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey externalRef0.IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RedriveDeadLetter(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminMe operation middleware
func (siw *ServerInterfaceWrapper) GetAdminMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FindAdminTxn operation middleware
func (siw *ServerInterfaceWrapper) FindAdminTxn(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params FindAdminTxnParams

	// ------------- Required query parameter "signature" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "signature", r.URL.Query(), &params.Signature, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "signature"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "signature", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FindAdminTxn(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminTxn operation middleware
func (siw *ServerInterfaceWrapper) GetAdminTxn(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminTxn(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FindAdminUser operation middleware
func (siw *ServerInterfaceWrapper) FindAdminUser(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params FindAdminUserParams

	// ------------- Required query parameter "handle" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "handle", r.URL.Query(), &params.Handle, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "handle"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "handle", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FindAdminUser(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminUser operation middleware
func (siw *ServerInterfaceWrapper) GetAdminUser(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminUser(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/admin/actions", wrapper.GetAdminActions)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/admin/admins", wrapper.GetAdmins)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/admin/cabals/{id}", wrapper.GetAdminCabal)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/admin/dead-letters", wrapper.GetDeadLetters)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/admin/dead-letters/{id}/discard", wrapper.DiscardDeadLetter)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/admin/dead-letters/{id}/redrive", wrapper.RedriveDeadLetter)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/admin/me", wrapper.GetAdminMe)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/admin/txns", wrapper.FindAdminTxn)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/admin/txns/{id}", wrapper.GetAdminTxn)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/admin/users", wrapper.FindAdminUser)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/admin/users/{id}", wrapper.GetAdminUser)

	return m
}

type GetAdminActionsRequestObject struct {
	Params GetAdminActionsParams
}

type GetAdminActionsResponseObject interface {
	VisitGetAdminActionsResponse(w http.ResponseWriter) error
}

type GetAdminActions200JSONResponse AdminActions

func (response GetAdminActions200JSONResponse) VisitGetAdminActionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAdminActionsdefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response GetAdminActionsdefaultApplicationProblemPlusJSONResponse) VisitGetAdminActionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetAdminsRequestObject struct {
}

type GetAdminsResponseObject interface {
	VisitGetAdminsResponse(w http.ResponseWriter) error
}

type GetAdmins200JSONResponse Admins

func (response GetAdmins200JSONResponse) VisitGetAdminsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAdminsdefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response GetAdminsdefaultApplicationProblemPlusJSONResponse) VisitGetAdminsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetAdminCabalRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetAdminCabalResponseObject interface {
	VisitGetAdminCabalResponse(w http.ResponseWriter) error
}

type GetAdminCabal200JSONResponse AdminCabal

func (response GetAdminCabal200JSONResponse) VisitGetAdminCabalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAdminCabaldefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response GetAdminCabaldefaultApplicationProblemPlusJSONResponse) VisitGetAdminCabalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetDeadLettersRequestObject struct {
	Params GetDeadLettersParams
}

type GetDeadLettersResponseObject interface {
	VisitGetDeadLettersResponse(w http.ResponseWriter) error
}

type GetDeadLetters200JSONResponse DeadLetters

func (response GetDeadLetters200JSONResponse) VisitGetDeadLettersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetDeadLettersdefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response GetDeadLettersdefaultApplicationProblemPlusJSONResponse) VisitGetDeadLettersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type DiscardDeadLetterRequestObject struct {
	Id     openapi_types.UUID `json:"id"`
	Params DiscardDeadLetterParams
	Body   *DiscardDeadLetterJSONRequestBody
}

type DiscardDeadLetterResponseObject interface {
	VisitDiscardDeadLetterResponse(w http.ResponseWriter) error
}

type DiscardDeadLetter204Response struct {
}

func (response DiscardDeadLetter204Response) VisitDiscardDeadLetterResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DiscardDeadLetterdefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response DiscardDeadLetterdefaultApplicationProblemPlusJSONResponse) VisitDiscardDeadLetterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type RedriveDeadLetterRequestObject struct {
	Id     openapi_types.UUID `json:"id"`
	Params RedriveDeadLetterParams
	Body   *RedriveDeadLetterJSONRequestBody
}

type RedriveDeadLetterResponseObject interface {
	VisitRedriveDeadLetterResponse(w http.ResponseWriter) error
}

type RedriveDeadLetter204Response struct {
}

func (response RedriveDeadLetter204Response) VisitRedriveDeadLetterResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RedriveDeadLetterdefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response RedriveDeadLetterdefaultApplicationProblemPlusJSONResponse) VisitRedriveDeadLetterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetAdminMeRequestObject struct {
}

type GetAdminMeResponseObject interface {
	VisitGetAdminMeResponse(w http.ResponseWriter) error
}

type GetAdminMe200JSONResponse AdminMe

func (response GetAdminMe200JSONResponse) VisitGetAdminMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAdminMedefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response GetAdminMedefaultApplicationProblemPlusJSONResponse) VisitGetAdminMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type FindAdminTxnRequestObject struct {
	Params FindAdminTxnParams
}

type FindAdminTxnResponseObject interface {
	VisitFindAdminTxnResponse(w http.ResponseWriter) error
}

type FindAdminTxn200JSONResponse AdminTxn

func (response FindAdminTxn200JSONResponse) VisitFindAdminTxnResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type FindAdminTxndefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response FindAdminTxndefaultApplicationProblemPlusJSONResponse) VisitFindAdminTxnResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetAdminTxnRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetAdminTxnResponseObject interface {
	VisitGetAdminTxnResponse(w http.ResponseWriter) error
}

type GetAdminTxn200JSONResponse AdminTxn

func (response GetAdminTxn200JSONResponse) VisitGetAdminTxnResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAdminTxndefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response GetAdminTxndefaultApplicationProblemPlusJSONResponse) VisitGetAdminTxnResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type FindAdminUserRequestObject struct {
	Params FindAdminUserParams
}

type FindAdminUserResponseObject interface {
	VisitFindAdminUserResponse(w http.ResponseWriter) error
}

type FindAdminUser200JSONResponse AdminUser

func (response FindAdminUser200JSONResponse) VisitFindAdminUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type FindAdminUserdefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response FindAdminUserdefaultApplicationProblemPlusJSONResponse) VisitFindAdminUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetAdminUserRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetAdminUserResponseObject interface {
	VisitGetAdminUserResponse(w http.ResponseWriter) error
}

type GetAdminUser200JSONResponse AdminUser

func (response GetAdminUser200JSONResponse) VisitGetAdminUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAdminUserdefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response GetAdminUserdefaultApplicationProblemPlusJSONResponse) VisitGetAdminUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetAdminActions List admin actions.
	// (GET /v1/admin/actions)
	GetAdminActions(ctx context.Context, request GetAdminActionsRequestObject) (GetAdminActionsResponseObject, error)
	// GetAdmins List current administrators.
	// (GET /v1/admin/admins)
	GetAdmins(ctx context.Context, request GetAdminsRequestObject) (GetAdminsResponseObject, error)
	// GetAdminCabal Look up a cabal by id.
	// (GET /v1/admin/cabals/{id})
	GetAdminCabal(ctx context.Context, request GetAdminCabalRequestObject) (GetAdminCabalResponseObject, error)
	// GetDeadLetters List dead letters.
	// (GET /v1/admin/dead-letters)
	GetDeadLetters(ctx context.Context, request GetDeadLettersRequestObject) (GetDeadLettersResponseObject, error)
	// DiscardDeadLetter Discard a dead letter.
	// (POST /v1/admin/dead-letters/{id}/discard)
	DiscardDeadLetter(ctx context.Context, request DiscardDeadLetterRequestObject) (DiscardDeadLetterResponseObject, error)
	// RedriveDeadLetter Redrive a dead letter.
	// (POST /v1/admin/dead-letters/{id}/redrive)
	RedriveDeadLetter(ctx context.Context, request RedriveDeadLetterRequestObject) (RedriveDeadLetterResponseObject, error)
	// GetAdminMe Read the active administrator role.
	// (GET /v1/admin/me)
	GetAdminMe(ctx context.Context, request GetAdminMeRequestObject) (GetAdminMeResponseObject, error)
	// FindAdminTxn Look up a transaction by signature.
	// (GET /v1/admin/txns)
	FindAdminTxn(ctx context.Context, request FindAdminTxnRequestObject) (FindAdminTxnResponseObject, error)
	// GetAdminTxn Look up a transaction by id.
	// (GET /v1/admin/txns/{id})
	GetAdminTxn(ctx context.Context, request GetAdminTxnRequestObject) (GetAdminTxnResponseObject, error)
	// FindAdminUser Look up a user by handle.
	// (GET /v1/admin/users)
	FindAdminUser(ctx context.Context, request FindAdminUserRequestObject) (FindAdminUserResponseObject, error)
	// GetAdminUser Look up a user by id.
	// (GET /v1/admin/users/{id})
	GetAdminUser(ctx context.Context, request GetAdminUserRequestObject) (GetAdminUserResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetAdminActions operation middleware
func (sh *strictHandler) GetAdminActions(w http.ResponseWriter, r *http.Request, params GetAdminActionsParams) {
	var request GetAdminActionsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAdminActions(ctx, request.(GetAdminActionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAdminActions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAdminActionsResponseObject); ok {
		if err := validResponse.VisitGetAdminActionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAdmins operation middleware
func (sh *strictHandler) GetAdmins(w http.ResponseWriter, r *http.Request) {
	var request GetAdminsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAdmins(ctx, request.(GetAdminsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAdmins")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAdminsResponseObject); ok {
		if err := validResponse.VisitGetAdminsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAdminCabal operation middleware
func (sh *strictHandler) GetAdminCabal(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetAdminCabalRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAdminCabal(ctx, request.(GetAdminCabalRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAdminCabal")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAdminCabalResponseObject); ok {
		if err := validResponse.VisitGetAdminCabalResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDeadLetters operation middleware
func (sh *strictHandler) GetDeadLetters(w http.ResponseWriter, r *http.Request, params GetDeadLettersParams) {
	var request GetDeadLettersRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDeadLetters(ctx, request.(GetDeadLettersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDeadLetters")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDeadLettersResponseObject); ok {
		if err := validResponse.VisitGetDeadLettersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DiscardDeadLetter operation middleware
func (sh *strictHandler) DiscardDeadLetter(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params DiscardDeadLetterParams) {
	var request DiscardDeadLetterRequestObject

	request.Id = id
	request.Params = params

	var body DiscardDeadLetterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DiscardDeadLetter(ctx, request.(DiscardDeadLetterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DiscardDeadLetter")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DiscardDeadLetterResponseObject); ok {
		if err := validResponse.VisitDiscardDeadLetterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RedriveDeadLetter operation middleware
func (sh *strictHandler) RedriveDeadLetter(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params RedriveDeadLetterParams) {
	var request RedriveDeadLetterRequestObject

	request.Id = id
	request.Params = params

	var body RedriveDeadLetterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RedriveDeadLetter(ctx, request.(RedriveDeadLetterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RedriveDeadLetter")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RedriveDeadLetterResponseObject); ok {
		if err := validResponse.VisitRedriveDeadLetterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAdminMe operation middleware
func (sh *strictHandler) GetAdminMe(w http.ResponseWriter, r *http.Request) {
	var request GetAdminMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAdminMe(ctx, request.(GetAdminMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAdminMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAdminMeResponseObject); ok {
		if err := validResponse.VisitGetAdminMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// FindAdminTxn operation middleware
func (sh *strictHandler) FindAdminTxn(w http.ResponseWriter, r *http.Request, params FindAdminTxnParams) {
	var request FindAdminTxnRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.FindAdminTxn(ctx, request.(FindAdminTxnRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "FindAdminTxn")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(FindAdminTxnResponseObject); ok {
		if err := validResponse.VisitFindAdminTxnResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAdminTxn operation middleware
func (sh *strictHandler) GetAdminTxn(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetAdminTxnRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAdminTxn(ctx, request.(GetAdminTxnRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAdminTxn")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAdminTxnResponseObject); ok {
		if err := validResponse.VisitGetAdminTxnResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// FindAdminUser operation middleware
func (sh *strictHandler) FindAdminUser(w http.ResponseWriter, r *http.Request, params FindAdminUserParams) {
	var request FindAdminUserRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.FindAdminUser(ctx, request.(FindAdminUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "FindAdminUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(FindAdminUserResponseObject); ok {
		if err := validResponse.VisitFindAdminUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAdminUser operation middleware
func (sh *strictHandler) GetAdminUser(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetAdminUserRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAdminUser(ctx, request.(GetAdminUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAdminUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAdminUserResponseObject); ok {
		if err := validResponse.VisitGetAdminUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
