// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const delistMissingAssets = `-- name: DelistMissingAssets :execrows
UPDATE assets SET issuer_tradable = false, updated_at = $1::timestamptz
WHERE issuer = $2::text
  AND issuer_tradable
  AND NOT (mint = ANY ($3::text[]))
`

type DelistMissingAssetsParams struct {
	Now    time.Time
	Issuer string
	Listed []string
}

func (q *Queries) DelistMissingAssets(ctx context.Context, arg DelistMissingAssetsParams) (int64, error) {
	result, err := q.db.Exec(ctx, delistMissingAssets, arg.Now, arg.Issuer, arg.Listed)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertAssets = `-- name: UpsertAssets :execrows
INSERT INTO assets (
  id, symbol, mint, decimals, issuer, kind, display_name, logo_url,
  issuer_tradable, popular_rank, company_key, first_seen_at, updated_at
)
SELECT
  u.id, u.symbol, u.mint, u.decimals, $1::text, u.kind, u.display_name, NULLIF(u.logo_url, ''),
  u.issuer_tradable, NULLIF(u.popular_rank, 0), u.company_key, $2::timestamptz, $2::timestamptz
FROM ROWS FROM (
  unnest($3::uuid[]), unnest($4::text[]), unnest($5::text[]),
  unnest($6::smallint[]), unnest($7::text[]), unnest($8::text[]),
  unnest($9::text[]), unnest($10::bool[]),
  unnest($11::smallint[]), unnest($12::text[])
) AS u (id, symbol, mint, decimals, kind, display_name, logo_url, issuer_tradable, popular_rank, company_key)
ON CONFLICT (mint) DO UPDATE SET
  symbol = excluded.symbol,
  decimals = CASE WHEN assets.chain_checked_at IS NULL THEN excluded.decimals ELSE assets.decimals END,
  kind = excluded.kind,
  display_name = excluded.display_name,
  logo_url = excluded.logo_url,
  issuer_tradable = excluded.issuer_tradable,
  popular_rank = excluded.popular_rank,
  company_key = excluded.company_key,
  updated_at = excluded.updated_at
WHERE assets.issuer = excluded.issuer
  AND (
    assets.symbol, assets.decimals, assets.kind, assets.display_name, assets.logo_url,
    assets.issuer_tradable, assets.popular_rank, assets.company_key
  ) IS DISTINCT FROM (
    excluded.symbol,
    CASE WHEN assets.chain_checked_at IS NULL THEN excluded.decimals ELSE assets.decimals END,
    excluded.kind, excluded.display_name, excluded.logo_url,
    excluded.issuer_tradable, excluded.popular_rank, excluded.company_key
  )
`

type UpsertAssetsParams struct {
	Issuer          string
	Now             time.Time
	Ids             []uuid.UUID
	Symbols         []string
	Mints           []string
	Decimals        []int16
	Kinds           []string
	DisplayNames    []string
	LogoUrls        []string
	IssuerTradables []bool
	PopularRanks    []int16
	CompanyKeys     []string
}

func (q *Queries) UpsertAssets(ctx context.Context, arg UpsertAssetsParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertAssets,
		arg.Issuer,
		arg.Now,
		arg.Ids,
		arg.Symbols,
		arg.Mints,
		arg.Decimals,
		arg.Kinds,
		arg.DisplayNames,
		arg.LogoUrls,
		arg.IssuerTradables,
		arg.PopularRanks,
		arg.CompanyKeys,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
