// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chain_facts.sql

package sqlc

import (
	"context"
	"time"
)

const storeChainFacts = `-- name: StoreChainFacts :many
UPDATE assets SET
  decimals = f.chain_decimals,
  ui_multiplier_num = f.multiplier_num,
  ui_multiplier_den = f.multiplier_den,
  chain_checked_at = $1::timestamptz,
  updated_at = $1::timestamptz
FROM ROWS FROM (
  unnest($2::text[]), unnest($3::smallint[]),
  unnest($4::smallint[]), unnest($5::bigint[]),
  unnest($6::bigint[])
) AS f (mint, issuer_decimals, chain_decimals, multiplier_num, multiplier_den)
WHERE assets.mint = f.mint AND assets.chain_checked_at IS NULL AND assets.decimals = f.issuer_decimals
RETURNING assets.mint
`

type StoreChainFactsParams struct {
	Now            time.Time
	Mints          []string
	IssuerDecimals []int16
	ChainDecimals  []int16
	MultiplierNums []int64
	MultiplierDens []int64
}

func (q *Queries) StoreChainFacts(ctx context.Context, arg StoreChainFactsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, storeChainFacts,
		arg.Now,
		arg.Mints,
		arg.IssuerDecimals,
		arg.ChainDecimals,
		arg.MultiplierNums,
		arg.MultiplierDens,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var mint string
		if err := rows.Scan(&mint); err != nil {
			return nil, err
		}
		items = append(items, mint)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const uncheckedAssets = `-- name: UncheckedAssets :many
SELECT id, symbol, mint, decimals, issuer, kind, display_name, logo_url, ui_multiplier_num, ui_multiplier_den, issuer_tradable, tradable_override, popular_rank, company_key, first_seen_at, updated_at, chain_checked_at FROM assets
WHERE chain_checked_at IS NULL
ORDER BY coalesce(tradable_override, issuer_tradable) DESC, popular_rank NULLS LAST, symbol
LIMIT $1
`

func (q *Queries) UncheckedAssets(ctx context.Context, maxAssets int32) ([]Asset, error) {
	rows, err := q.db.Query(ctx, uncheckedAssets, maxAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.Mint,
			&i.Decimals,
			&i.Issuer,
			&i.Kind,
			&i.DisplayName,
			&i.LogoUrl,
			&i.UiMultiplierNum,
			&i.UiMultiplierDen,
			&i.IssuerTradable,
			&i.TradableOverride,
			&i.PopularRank,
			&i.CompanyKey,
			&i.FirstSeenAt,
			&i.UpdatedAt,
			&i.ChainCheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
