// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prices.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertBackfilledPricePoints = `-- name: InsertBackfilledPricePoints :execrows
INSERT INTO price_points (mint, ts, price_micros, source)
SELECT $1::text, u.ts, u.price_micros, $2::text
FROM ROWS FROM (
  unnest($3::timestamptz[]), unnest($4::bigint[])
) AS u (ts, price_micros)
ON CONFLICT (mint, ts) DO NOTHING
`

type InsertBackfilledPricePointsParams struct {
	Mint        string
	Source      string
	Timestamps  []time.Time
	PriceMicros []int64
}

func (q *Queries) InsertBackfilledPricePoints(ctx context.Context, arg InsertBackfilledPricePointsParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertBackfilledPricePoints,
		arg.Mint,
		arg.Source,
		arg.Timestamps,
		arg.PriceMicros,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertPricePoints = `-- name: InsertPricePoints :execrows
INSERT INTO price_points (mint, ts, price_micros, source)
SELECT u.mint, $1::timestamptz, u.price_micros, $2::text
FROM ROWS FROM (
  unnest($3::text[]), unnest($4::bigint[])
) AS u (mint, price_micros)
ON CONFLICT (mint, ts) DO NOTHING
`

type InsertPricePointsParams struct {
	Ts          time.Time
	Source      string
	Mints       []string
	PriceMicros []int64
}

func (q *Queries) InsertPricePoints(ctx context.Context, arg InsertPricePointsParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPricePoints,
		arg.Ts,
		arg.Source,
		arg.Mints,
		arg.PriceMicros,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recentPriceSamples = `-- name: RecentPriceSamples :many
SELECT a.id AS asset_id, p.ts, p.price_micros
FROM assets AS a
CROSS JOIN LATERAL (
  SELECT price_points.ts, price_points.price_micros
  FROM price_points
  WHERE price_points.mint = a.mint AND price_points.ts <= $1::timestamptz
  ORDER BY price_points.ts DESC
  LIMIT $2::integer
) AS p
WHERE $3::boolean OR a.id = ANY ($4::uuid[])
ORDER BY a.id, p.ts DESC
`

type RecentPriceSamplesParams struct {
	At         time.Time
	PerAsset   int32
	EveryAsset bool
	Ids        []uuid.UUID
}

type RecentPriceSamplesRow struct {
	AssetID     uuid.UUID
	Ts          time.Time
	PriceMicros int64
}

func (q *Queries) RecentPriceSamples(ctx context.Context, arg RecentPriceSamplesParams) ([]RecentPriceSamplesRow, error) {
	rows, err := q.db.Query(ctx, recentPriceSamples,
		arg.At,
		arg.PerAsset,
		arg.EveryAsset,
		arg.Ids,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecentPriceSamplesRow
	for rows.Next() {
		var i RecentPriceSamplesRow
		if err := rows.Scan(&i.AssetID, &i.Ts, &i.PriceMicros); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const thinPricePoints = `-- name: ThinPricePoints :many
DELETE FROM price_points
WHERE ctid IN (
  SELECT p.ctid
  FROM price_points AS p
  WHERE p.ts >= $1::timestamptz
    AND p.ts < $2::timestamptz
    AND p.ts < (SELECT max(latest.ts) FROM price_points AS latest WHERE latest.mint = p.mint)
    AND EXISTS (
      SELECT 1
      FROM price_points AS earlier
      WHERE earlier.mint = p.mint
        AND earlier.ts >= date_bin(($3::text)::interval, p.ts, TIMESTAMPTZ 'epoch')
        AND earlier.ts < p.ts
    )
  ORDER BY p.ts
  LIMIT $4::integer
)
RETURNING ts
`

type ThinPricePointsParams struct {
	After      time.Time
	OlderThan  time.Time
	Bucket     string
	BatchLimit int32
}

func (q *Queries) ThinPricePoints(ctx context.Context, arg ThinPricePointsParams) ([]time.Time, error) {
	rows, err := q.db.Query(ctx, thinPricePoints,
		arg.After,
		arg.OlderThan,
		arg.Bucket,
		arg.BatchLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []time.Time
	for rows.Next() {
		var ts time.Time
		if err := rows.Scan(&ts); err != nil {
			return nil, err
		}
		items = append(items, ts)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
