//go:build go1.22

// Package analyticsapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by cmd/gen httpapi from api/spec/*.yaml. DO NOT EDIT.
package analyticsapi

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	externalRef0 "github.com/monaco/monaco/apps/backend/internal/platform/httpx/api"
	"github.com/oapi-codegen/runtime"
)

// Defines values for DashboardBucket.
const (
	Day  DashboardBucket = "day"
	Week DashboardBucket = "week"
)

// Valid indicates whether the value is a known member of the DashboardBucket enum.
func (e DashboardBucket) Valid() bool {
	switch e {
	case Day:
		return true
	case Week:
		return true
	default:
		return false
	}
}

// DashboardBucket The size of one bucket.
//
// Examples: day
type DashboardBucket string

// DashboardMicros A USDC amount in micros as a decimal string.
//
// Examples: 25000000
type DashboardMicros = string

// MoneyBucket The settled money movement of one bucket.
//
// Examples: {"bucket_start":"2026-09-01T00:00:00Z","cash_out_count":0,"cash_out_micros":"0","deposit_count":2,"deposit_micros":"50000000","fund_count":1,"fund_micros":"25000000","swap_buy_micros":"10000000","swap_sell_micros":"0","withdrawal_count":0,"withdrawal_micros":"0"}
type MoneyBucket struct {
	// BucketStart The start of the bucket in UTC.
	//
	// Examples: 2026-09-01T00:00:00Z
	BucketStart time.Time `json:"bucket_start"`

	// CashOutCount Cash-outs paid to members.
	//
	// Examples: 0
	CashOutCount int64 `json:"cash_out_count"`

	// CashOutMicros A USDC amount in micros as a decimal string.
	//
	// Examples: 25000000
	CashOutMicros DashboardMicros `json:"cash_out_micros"`

	// DepositCount Deposits credited to member wallets.
	//
	// Examples: 2
	DepositCount int64 `json:"deposit_count"`

	// DepositMicros A USDC amount in micros as a decimal string.
	//
	// Examples: 25000000
	DepositMicros DashboardMicros `json:"deposit_micros"`

	// FundCount Transfers from a member wallet into a cabal.
	//
	// Examples: 1
	FundCount int64 `json:"fund_count"`

	// FundMicros A USDC amount in micros as a decimal string.
	//
	// Examples: 25000000
	FundMicros DashboardMicros `json:"fund_micros"`

	// SwapBuyMicros A USDC amount in micros as a decimal string.
	//
	// Examples: 25000000
	SwapBuyMicros DashboardMicros `json:"swap_buy_micros"`

	// SwapSellMicros A USDC amount in micros as a decimal string.
	//
	// Examples: 25000000
	SwapSellMicros DashboardMicros `json:"swap_sell_micros"`

	// WithdrawalCount Withdrawals to external wallets.
	//
	// Examples: 0
	WithdrawalCount int64 `json:"withdrawal_count"`

	// WithdrawalMicros A USDC amount in micros as a decimal string.
	//
	// Examples: 25000000
	WithdrawalMicros DashboardMicros `json:"withdrawal_micros"`
}

// MoneyDashboard Money moving through the platform and the total value it holds.
//
// Examples: {"as_of":"2026-09-30T23:55:00Z","bucket":"day","buckets":[],"from":"2026-09-01T00:00:00Z","platform_balance_micros":"20000000","pot_micros":"80000000","to":"2026-10-01T00:00:00Z","total_value_held_micros":"100000000"}
type MoneyDashboard struct {
	// AsOf When the latest valuation run priced the pots. Null before the first run.
	//
	// Examples: 2026-09-30T23:55:00Z
	AsOf *time.Time `json:"as_of"`

	// Bucket The size of one bucket.
	//
	// Examples: day
	Bucket DashboardBucket `json:"bucket"`

	// Buckets The buckets with activity, oldest first.
	Buckets []MoneyBucket `json:"buckets"`

	// From The start of the range.
	//
	// Examples: 2026-09-01T00:00:00Z
	From time.Time `json:"from"`

	// PlatformBalanceMicros A USDC amount in micros as a decimal string.
	//
	// Examples: 25000000
	PlatformBalanceMicros DashboardMicros `json:"platform_balance_micros"`

	// PotMicros A USDC amount in micros as a decimal string.
	//
	// Examples: 25000000
	PotMicros DashboardMicros `json:"pot_micros"`

	// To The end of the range, exclusive.
	//
	// Examples: 2026-10-01T00:00:00Z
	To time.Time `json:"to"`

	// TotalValueHeldMicros A USDC amount in micros as a decimal string.
	//
	// Examples: 25000000
	TotalValueHeldMicros DashboardMicros `json:"total_value_held_micros"`
}

// DashboardFrom Examples: 2026-09-01
type DashboardFrom = string

// DashboardTo Examples: 2026-10-01
type DashboardTo = string

// GetMoneyDashboardParams defines parameters for GetMoneyDashboard.
type GetMoneyDashboardParams struct {
	// From The start of the range, inclusive, as a date such as 2026-09-01 or an RFC 3339 time. Dates are UTC.
	From DashboardFrom `form:"from" json:"from"`

	// To The end of the range, exclusive, as a date or an RFC 3339 time. It cannot be more than 400 days after `from`.
	To DashboardTo `form:"to" json:"to"`

	// Bucket The bucket size. A week starts on Monday, UTC.
	Bucket DashboardBucket `form:"bucket" json:"bucket"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetMoneyDashboard Read the money dashboard.
	// (GET /v1/admin/dashboards/money)
	GetMoneyDashboard(w http.ResponseWriter, r *http.Request, params GetMoneyDashboardParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetMoneyDashboard operation middleware
func (siw *ServerInterfaceWrapper) GetMoneyDashboard(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMoneyDashboardParams

	// ------------- Required query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Required query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Required query parameter "bucket" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "bucket", r.URL.Query(), &params.Bucket, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "bucket"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bucket", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMoneyDashboard(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/admin/dashboards/money", wrapper.GetMoneyDashboard)

	return m
}

type GetMoneyDashboardRequestObject struct {
	Params GetMoneyDashboardParams
}

type GetMoneyDashboardResponseObject interface {
	VisitGetMoneyDashboardResponse(w http.ResponseWriter) error
}

type GetMoneyDashboard200JSONResponse MoneyDashboard

func (response GetMoneyDashboard200JSONResponse) VisitGetMoneyDashboardResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMoneyDashboarddefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response GetMoneyDashboarddefaultApplicationProblemPlusJSONResponse) VisitGetMoneyDashboardResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetMoneyDashboard Read the money dashboard.
	// (GET /v1/admin/dashboards/money)
	GetMoneyDashboard(ctx context.Context, request GetMoneyDashboardRequestObject) (GetMoneyDashboardResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetMoneyDashboard operation middleware
func (sh *strictHandler) GetMoneyDashboard(w http.ResponseWriter, r *http.Request, params GetMoneyDashboardParams) {
	var request GetMoneyDashboardRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMoneyDashboard(ctx, request.(GetMoneyDashboardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMoneyDashboard")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMoneyDashboardResponseObject); ok {
		if err := validResponse.VisitGetMoneyDashboardResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
