//go:build go1.22

// Package analyticsapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by cmd/gen httpapi from api/spec/*.yaml. DO NOT EDIT.
package analyticsapi

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	externalRef0 "github.com/monaco/monaco/apps/backend/internal/platform/httpx/api"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for DashboardBucket.
const (
	Day  DashboardBucket = "day"
	Week DashboardBucket = "week"
)

// Valid indicates whether the value is a known member of the DashboardBucket enum.
func (e DashboardBucket) Valid() bool {
	switch e {
	case Day:
		return true
	case Week:
		return true
	default:
		return false
	}
}

// DashboardBucket The size of one bucket.
//
// Examples: day
type DashboardBucket string

// DashboardCabals How many cabals exist and how large they are.
//
// Examples: {"banned":1,"members_max":15,"members_p50":4,"members_p90":9,"total":12}
type DashboardCabals struct {
	// Banned Banned cabals.
	//
	// Examples: 1
	Banned int64 `json:"banned"`

	// MembersMax Members of the largest cabal.
	//
	// Examples: 15
	MembersMax int64 `json:"members_max"`

	// MembersP50 Members of the median cabal.
	//
	// Examples: 4
	MembersP50 int64 `json:"members_p50"`

	// MembersP90 Members of the cabal at the 90th percentile.
	//
	// Examples: 9
	MembersP90 int64 `json:"members_p90"`

	// Total Cabals, banned ones included.
	//
	// Examples: 12
	Total int64 `json:"total"`
}

// DashboardMicros A USDC amount in micros as a decimal string.
//
// Examples: 25000000
type DashboardMicros = string

// DashboardPoint The number of events of one metric and group in one bucket.
//
// Examples: {"bucket_start":"2026-09-01T00:00:00Z","count":4,"group":"contacts","metric":"follows_created"}
type DashboardPoint struct {
	// BucketStart The start of the bucket in UTC.
	//
	// Examples: 2026-09-01T00:00:00Z
	BucketStart time.Time `json:"bucket_start"`

	// Count Events in the bucket.
	//
	// Examples: 4
	Count int64 `json:"count"`

	// Group The value the metric is grouped by, empty when the metric has no grouping.
	//
	// Examples: contacts
	Group string `json:"group"`

	// Metric What was counted.
	//
	// Examples: follows_created
	Metric string `json:"metric"`
}

// GovernanceBucket The proposal events of one bucket.
//
// Examples: {"bucket_start":"2026-09-01T00:00:00Z","created":3,"execution_blocked":0,"expired":0,"failed":1,"passed":1}
type GovernanceBucket struct {
	// BucketStart The start of the bucket in UTC.
	//
	// Examples: 2026-09-01T00:00:00Z
	BucketStart time.Time `json:"bucket_start"`

	// Created Proposals opened.
	//
	// Examples: 3
	Created int64 `json:"created"`

	// ExecutionBlocked Passed proposals whose trade was blocked.
	//
	// Examples: 0
	ExecutionBlocked int64 `json:"execution_blocked"`

	// Expired Proposals that expired.
	//
	// Examples: 0
	Expired int64 `json:"expired"`

	// Failed Proposals that failed.
	//
	// Examples: 1
	Failed int64 `json:"failed"`

	// Passed Proposals that passed.
	//
	// Examples: 1
	Passed int64 `json:"passed"`
}

// GovernanceDashboard Proposal activity and voter participation.
//
// Examples: {"bucket":"day","buckets":[],"from":"2026-09-01T00:00:00Z","median_seconds_to_pass":10800,"open_proposals":2,"participation":[],"passed_in_range":4,"to":"2026-10-01T00:00:00Z"}
type GovernanceDashboard struct {
	// Bucket The size of one bucket.
	//
	// Examples: day
	Bucket DashboardBucket `json:"bucket"`

	// Buckets The buckets with proposal events, oldest first.
	Buckets []GovernanceBucket `json:"buckets"`

	// From The start of the range.
	//
	// Examples: 2026-09-01T00:00:00Z
	From time.Time `json:"from"`

	// MedianSecondsToPass The median seconds from creation to pass over the proposals that passed in the range. Null when none did.
	//
	// Examples: 10800
	MedianSecondsToPass *int64 `json:"median_seconds_to_pass"`

	// OpenProposals Proposals open now.
	//
	// Examples: 2
	OpenProposals int64 `json:"open_proposals"`

	// Participation One row per cabal that opened a proposal in the range, by cabal id.
	Participation []GovernanceParticipation `json:"participation"`

	// PassedInRange Proposals that passed in the range.
	//
	// Examples: 4
	PassedInRange int64 `json:"passed_in_range"`

	// To The end of the range, exclusive.
	//
	// Examples: 2026-10-01T00:00:00Z
	To time.Time `json:"to"`
}

// GovernanceParticipation How much of its electorate one cabal used on the proposals it opened in the range.
//
// Examples: {"cabal_id":"019cc330-1111-7000-8000-000000000001","eligible_votes":6,"participation_bps":5000,"proposals":2,"votes_cast":3}
type GovernanceParticipation struct {
	// CabalId The cabal.
	//
	// Examples: 019cc330-1111-7000-8000-000000000001
	CabalId openapi_types.UUID `json:"cabal_id"`

	// EligibleVotes Votes the voters could cast across those proposals.
	//
	// Examples: 6
	EligibleVotes int64 `json:"eligible_votes"`

	// ParticipationBps Votes cast out of the votes eligible in basis points, 0 when none were eligible.
	//
	// Examples: 5000
	ParticipationBps int64 `json:"participation_bps"`

	// Proposals Proposals the cabal opened in the range.
	//
	// Examples: 2
	Proposals int64 `json:"proposals"`

	// VotesCast Votes cast across those proposals.
	//
	// Examples: 3
	VotesCast int64 `json:"votes_cast"`
}

// MoneyBucket The settled money movement of one bucket.
//
// Examples: {"bucket_start":"2026-09-01T00:00:00Z","cash_out_count":0,"cash_out_micros":"0","deposit_count":2,"deposit_micros":"50000000","fund_count":1,"fund_micros":"25000000","swap_buy_micros":"10000000","swap_sell_micros":"0","withdrawal_count":0,"withdrawal_micros":"0"}
type MoneyBucket struct {
	// BucketStart The start of the bucket in UTC.
	//
	// Examples: 2026-09-01T00:00:00Z
	BucketStart time.Time `json:"bucket_start"`

	// CashOutCount Cash-outs paid to members.
	//
	// Examples: 0
	CashOutCount int64 `json:"cash_out_count"`

	// CashOutMicros A USDC amount in micros as a decimal string.
	//
	// Examples: 25000000
	CashOutMicros DashboardMicros `json:"cash_out_micros"`

	// DepositCount Deposits credited to member wallets.
	//
	// Examples: 2
	DepositCount int64 `json:"deposit_count"`

	// DepositMicros A USDC amount in micros as a decimal string.
	//
	// Examples: 25000000
	DepositMicros DashboardMicros `json:"deposit_micros"`

	// FundCount Transfers from a member wallet into a cabal.
	//
	// Examples: 1
	FundCount int64 `json:"fund_count"`

	// FundMicros A USDC amount in micros as a decimal string.
	//
	// Examples: 25000000
	FundMicros DashboardMicros `json:"fund_micros"`

	// SwapBuyMicros A USDC amount in micros as a decimal string.
	//
	// Examples: 25000000
	SwapBuyMicros DashboardMicros `json:"swap_buy_micros"`

	// SwapSellMicros A USDC amount in micros as a decimal string.
	//
	// Examples: 25000000
	SwapSellMicros DashboardMicros `json:"swap_sell_micros"`

	// WithdrawalCount Withdrawals to external wallets.
	//
	// Examples: 0
	WithdrawalCount int64 `json:"withdrawal_count"`

	// WithdrawalMicros A USDC amount in micros as a decimal string.
	//
	// Examples: 25000000
	WithdrawalMicros DashboardMicros `json:"withdrawal_micros"`
}

// MoneyDashboard Money moving through the platform and the total value it holds.
//
// Examples: {"as_of":"2026-09-30T23:55:00Z","bucket":"day","buckets":[],"from":"2026-09-01T00:00:00Z","platform_balance_micros":"20000000","pot_micros":"80000000","series":[],"to":"2026-10-01T00:00:00Z","total_value_held_micros":"100000000"}
type MoneyDashboard struct {
	// AsOf When the latest valuation run priced the pots. Null before the first run.
	//
	// Examples: 2026-09-30T23:55:00Z
	AsOf *time.Time `json:"as_of"`

	// Bucket The size of one bucket.
	//
	// Examples: day
	Bucket DashboardBucket `json:"bucket"`

	// Buckets The buckets with activity, oldest first.
	Buckets []MoneyBucket `json:"buckets"`

	// From The start of the range.
	//
	// Examples: 2026-09-01T00:00:00Z
	From time.Time `json:"from"`

	// PlatformBalanceMicros A USDC amount in micros as a decimal string.
	//
	// Examples: 25000000
	PlatformBalanceMicros DashboardMicros `json:"platform_balance_micros"`

	// PotMicros A USDC amount in micros as a decimal string.
	//
	// Examples: 25000000
	PotMicros DashboardMicros `json:"pot_micros"`

	// Series Card onramp status changes per bucket and status, oldest first.
	Series []DashboardPoint `json:"series"`

	// To The end of the range, exclusive.
	//
	// Examples: 2026-10-01T00:00:00Z
	To time.Time `json:"to"`

	// TotalValueHeldMicros A USDC amount in micros as a decimal string.
	//
	// Examples: 25000000
	TotalValueHeldMicros DashboardMicros `json:"total_value_held_micros"`
}

// SafetyDashboard Pauses, outside deposits, bans and administrator actions.
//
// Examples: {"banned_cabals":1,"banned_users":2,"bucket":"day","from":"2026-09-01T00:00:00Z","series":[],"to":"2026-10-01T00:00:00Z"}
type SafetyDashboard struct {
	// BannedCabals Cabals that are banned now.
	//
	// Examples: 1
	BannedCabals int64 `json:"banned_cabals"`

	// BannedUsers Users whose account is banned now.
	//
	// Examples: 2
	BannedUsers int64 `json:"banned_users"`

	// Bucket The size of one bucket.
	//
	// Examples: day
	Bucket DashboardBucket `json:"bucket"`

	// From The start of the range.
	//
	// Examples: 2026-09-01T00:00:00Z
	From time.Time `json:"from"`

	// Series Events per bucket, metric and group, oldest first.
	Series []DashboardPoint `json:"series"`

	// To The end of the range, exclusive.
	//
	// Examples: 2026-10-01T00:00:00Z
	To time.Time `json:"to"`
}

// SocialDashboard The size and activity of the social graph.
//
// Examples: {"bucket":"day","cabals":{"banned":1,"members_max":15,"members_p50":4,"members_p90":9,"total":12},"from":"2026-09-01T00:00:00Z","series":[],"to":"2026-10-01T00:00:00Z","user_states":[],"users_total":130}
type SocialDashboard struct {
	// Bucket The size of one bucket.
	//
	// Examples: day
	Bucket DashboardBucket `json:"bucket"`

	// Cabals How many cabals exist and how large they are.
	//
	// Examples: {"banned":1,"members_max":15,"members_p50":4,"members_p90":9,"total":12}
	Cabals DashboardCabals `json:"cabals"`

	// From The start of the range.
	//
	// Examples: 2026-09-01T00:00:00Z
	From time.Time `json:"from"`

	// Series Events per bucket, metric and group, oldest first.
	Series []DashboardPoint `json:"series"`

	// To The end of the range, exclusive.
	//
	// Examples: 2026-10-01T00:00:00Z
	To time.Time `json:"to"`

	// UserStates Users by auth state and account status.
	UserStates []UserStateCount `json:"user_states"`

	// UsersTotal Users in every state, deleted accounts included.
	//
	// Examples: 130
	UsersTotal int64 `json:"users_total"`
}

// UserStateCount The users in one auth state and account status.
//
// Examples: {"account_status":"active","auth_state":"ONBOARDING_COMPLETED","users":120}
type UserStateCount struct {
	// AccountStatus The account status.
	//
	// Examples: active
	AccountStatus string `json:"account_status"`

	// AuthState The auth state.
	//
	// Examples: ONBOARDING_COMPLETED
	AuthState string `json:"auth_state"`

	// Users Users in this state.
	//
	// Examples: 120
	Users int64 `json:"users"`
}

// DashboardFrom Examples: 2026-09-01
type DashboardFrom = string

// DashboardTo Examples: 2026-10-01
type DashboardTo = string

// GetGovernanceDashboardParams defines parameters for GetGovernanceDashboard.
type GetGovernanceDashboardParams struct {
	// From The start of the range, inclusive, as a date such as 2026-09-01 or an RFC 3339 time. Dates are UTC.
	From DashboardFrom `form:"from" json:"from"`

	// To The end of the range, exclusive, as a date or an RFC 3339 time. It cannot be more than 400 days after `from`.
	To DashboardTo `form:"to" json:"to"`

	// Bucket The bucket size. A week starts on Monday, UTC.
	Bucket DashboardBucket `form:"bucket" json:"bucket"`
}

// GetMoneyDashboardParams defines parameters for GetMoneyDashboard.
type GetMoneyDashboardParams struct {
	// From The start of the range, inclusive, as a date such as 2026-09-01 or an RFC 3339 time. Dates are UTC.
	From DashboardFrom `form:"from" json:"from"`

	// To The end of the range, exclusive, as a date or an RFC 3339 time. It cannot be more than 400 days after `from`.
	To DashboardTo `form:"to" json:"to"`

	// Bucket The bucket size. A week starts on Monday, UTC.
	Bucket DashboardBucket `form:"bucket" json:"bucket"`
}

// GetSafetyDashboardParams defines parameters for GetSafetyDashboard.
type GetSafetyDashboardParams struct {
	// From The start of the range, inclusive, as a date such as 2026-09-01 or an RFC 3339 time. Dates are UTC.
	From DashboardFrom `form:"from" json:"from"`

	// To The end of the range, exclusive, as a date or an RFC 3339 time. It cannot be more than 400 days after `from`.
	To DashboardTo `form:"to" json:"to"`

	// Bucket The bucket size. A week starts on Monday, UTC.
	Bucket DashboardBucket `form:"bucket" json:"bucket"`
}

// GetSocialDashboardParams defines parameters for GetSocialDashboard.
type GetSocialDashboardParams struct {
	// From The start of the range, inclusive, as a date such as 2026-09-01 or an RFC 3339 time. Dates are UTC.
	From DashboardFrom `form:"from" json:"from"`

	// To The end of the range, exclusive, as a date or an RFC 3339 time. It cannot be more than 400 days after `from`.
	To DashboardTo `form:"to" json:"to"`

	// Bucket The bucket size. A week starts on Monday, UTC.
	Bucket DashboardBucket `form:"bucket" json:"bucket"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetGovernanceDashboard Read the governance dashboard.
	// (GET /v1/admin/dashboards/governance)
	GetGovernanceDashboard(w http.ResponseWriter, r *http.Request, params GetGovernanceDashboardParams)
	// GetMoneyDashboard Read the money dashboard.
	// (GET /v1/admin/dashboards/money)
	GetMoneyDashboard(w http.ResponseWriter, r *http.Request, params GetMoneyDashboardParams)
	// GetSafetyDashboard Read the safety dashboard.
	// (GET /v1/admin/dashboards/safety)
	GetSafetyDashboard(w http.ResponseWriter, r *http.Request, params GetSafetyDashboardParams)
	// GetSocialDashboard Read the social dashboard.
	// (GET /v1/admin/dashboards/social)
	GetSocialDashboard(w http.ResponseWriter, r *http.Request, params GetSocialDashboardParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetGovernanceDashboard operation middleware
func (siw *ServerInterfaceWrapper) GetGovernanceDashboard(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetGovernanceDashboardParams

	// ------------- Required query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Required query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Required query parameter "bucket" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "bucket", r.URL.Query(), &params.Bucket, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "bucket"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bucket", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGovernanceDashboard(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMoneyDashboard operation middleware
func (siw *ServerInterfaceWrapper) GetMoneyDashboard(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMoneyDashboardParams

	// ------------- Required query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Required query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Required query parameter "bucket" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "bucket", r.URL.Query(), &params.Bucket, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "bucket"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bucket", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMoneyDashboard(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSafetyDashboard operation middleware
func (siw *ServerInterfaceWrapper) GetSafetyDashboard(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSafetyDashboardParams

	// ------------- Required query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Required query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Required query parameter "bucket" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "bucket", r.URL.Query(), &params.Bucket, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "bucket"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bucket", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSafetyDashboard(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSocialDashboard operation middleware
func (siw *ServerInterfaceWrapper) GetSocialDashboard(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSocialDashboardParams

	// ------------- Required query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Required query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Required query parameter "bucket" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "bucket", r.URL.Query(), &params.Bucket, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "bucket"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bucket", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSocialDashboard(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/admin/dashboards/governance", wrapper.GetGovernanceDashboard)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/admin/dashboards/money", wrapper.GetMoneyDashboard)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/admin/dashboards/safety", wrapper.GetSafetyDashboard)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/admin/dashboards/social", wrapper.GetSocialDashboard)

	return m
}

type GetGovernanceDashboardRequestObject struct {
	Params GetGovernanceDashboardParams
}

type GetGovernanceDashboardResponseObject interface {
	VisitGetGovernanceDashboardResponse(w http.ResponseWriter) error
}

type GetGovernanceDashboard200JSONResponse GovernanceDashboard

func (response GetGovernanceDashboard200JSONResponse) VisitGetGovernanceDashboardResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetGovernanceDashboarddefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response GetGovernanceDashboarddefaultApplicationProblemPlusJSONResponse) VisitGetGovernanceDashboardResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetMoneyDashboardRequestObject struct {
	Params GetMoneyDashboardParams
}

type GetMoneyDashboardResponseObject interface {
	VisitGetMoneyDashboardResponse(w http.ResponseWriter) error
}

type GetMoneyDashboard200JSONResponse MoneyDashboard

func (response GetMoneyDashboard200JSONResponse) VisitGetMoneyDashboardResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMoneyDashboarddefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response GetMoneyDashboarddefaultApplicationProblemPlusJSONResponse) VisitGetMoneyDashboardResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetSafetyDashboardRequestObject struct {
	Params GetSafetyDashboardParams
}

type GetSafetyDashboardResponseObject interface {
	VisitGetSafetyDashboardResponse(w http.ResponseWriter) error
}

type GetSafetyDashboard200JSONResponse SafetyDashboard

func (response GetSafetyDashboard200JSONResponse) VisitGetSafetyDashboardResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSafetyDashboarddefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response GetSafetyDashboarddefaultApplicationProblemPlusJSONResponse) VisitGetSafetyDashboardResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetSocialDashboardRequestObject struct {
	Params GetSocialDashboardParams
}

type GetSocialDashboardResponseObject interface {
	VisitGetSocialDashboardResponse(w http.ResponseWriter) error
}

type GetSocialDashboard200JSONResponse SocialDashboard

func (response GetSocialDashboard200JSONResponse) VisitGetSocialDashboardResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSocialDashboarddefaultApplicationProblemPlusJSONResponse struct {
	Body       externalRef0.Problem
	StatusCode int
}

func (response GetSocialDashboarddefaultApplicationProblemPlusJSONResponse) VisitGetSocialDashboardResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetGovernanceDashboard Read the governance dashboard.
	// (GET /v1/admin/dashboards/governance)
	GetGovernanceDashboard(ctx context.Context, request GetGovernanceDashboardRequestObject) (GetGovernanceDashboardResponseObject, error)
	// GetMoneyDashboard Read the money dashboard.
	// (GET /v1/admin/dashboards/money)
	GetMoneyDashboard(ctx context.Context, request GetMoneyDashboardRequestObject) (GetMoneyDashboardResponseObject, error)
	// GetSafetyDashboard Read the safety dashboard.
	// (GET /v1/admin/dashboards/safety)
	GetSafetyDashboard(ctx context.Context, request GetSafetyDashboardRequestObject) (GetSafetyDashboardResponseObject, error)
	// GetSocialDashboard Read the social dashboard.
	// (GET /v1/admin/dashboards/social)
	GetSocialDashboard(ctx context.Context, request GetSocialDashboardRequestObject) (GetSocialDashboardResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetGovernanceDashboard operation middleware
func (sh *strictHandler) GetGovernanceDashboard(w http.ResponseWriter, r *http.Request, params GetGovernanceDashboardParams) {
	var request GetGovernanceDashboardRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetGovernanceDashboard(ctx, request.(GetGovernanceDashboardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGovernanceDashboard")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetGovernanceDashboardResponseObject); ok {
		if err := validResponse.VisitGetGovernanceDashboardResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMoneyDashboard operation middleware
func (sh *strictHandler) GetMoneyDashboard(w http.ResponseWriter, r *http.Request, params GetMoneyDashboardParams) {
	var request GetMoneyDashboardRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMoneyDashboard(ctx, request.(GetMoneyDashboardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMoneyDashboard")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMoneyDashboardResponseObject); ok {
		if err := validResponse.VisitGetMoneyDashboardResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSafetyDashboard operation middleware
func (sh *strictHandler) GetSafetyDashboard(w http.ResponseWriter, r *http.Request, params GetSafetyDashboardParams) {
	var request GetSafetyDashboardRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSafetyDashboard(ctx, request.(GetSafetyDashboardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSafetyDashboard")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSafetyDashboardResponseObject); ok {
		if err := validResponse.VisitGetSafetyDashboardResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSocialDashboard operation middleware
func (sh *strictHandler) GetSocialDashboard(w http.ResponseWriter, r *http.Request, params GetSocialDashboardParams) {
	var request GetSocialDashboardRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSocialDashboard(ctx, request.(GetSocialDashboardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSocialDashboard")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSocialDashboardResponseObject); ok {
		if err := validResponse.VisitGetSocialDashboardResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
