// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: approvals.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const decideApproval = `-- name: DecideApproval :execrows
UPDATE admin_approvals
SET status = $1, decided_by = $2::uuid,
  decided_reason = $3::text, decided_at = $4::timestamptz
WHERE id = $5 AND status = 'pending' AND expires_at > $4::timestamptz
`

type DecideApprovalParams struct {
	ToStatus      string
	DecidedBy     uuid.UUID
	DecidedReason string
	DecidedAt     time.Time
	ID            uuid.UUID
}

func (q *Queries) DecideApproval(ctx context.Context, arg DecideApprovalParams) (int64, error) {
	result, err := q.db.Exec(ctx, decideApproval,
		arg.ToStatus,
		arg.DecidedBy,
		arg.DecidedReason,
		arg.DecidedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireApprovals = `-- name: ExpireApprovals :execrows
UPDATE admin_approvals
SET status = 'expired', decided_at = $1::timestamptz
WHERE status = 'pending' AND expires_at <= $1::timestamptz
`

func (q *Queries) ExpireApprovals(ctx context.Context, now time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, expireApprovals, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expirePendingApproval = `-- name: ExpirePendingApproval :execrows
UPDATE admin_approvals
SET status = 'expired', decided_at = $1::timestamptz
WHERE action = $2 AND target_id = $3 AND status = 'pending'
  AND expires_at <= $1::timestamptz
`

type ExpirePendingApprovalParams struct {
	Now      time.Time
	Action   string
	TargetID uuid.UUID
}

func (q *Queries) ExpirePendingApproval(ctx context.Context, arg ExpirePendingApprovalParams) (int64, error) {
	result, err := q.db.Exec(ctx, expirePendingApproval, arg.Now, arg.Action, arg.TargetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getApproval = `-- name: GetApproval :one
SELECT id, action, target_id, requested_by, reason, status, decided_by, decided_reason, created_at, decided_at,
  expires_at
FROM admin_approvals
WHERE id = $1
`

func (q *Queries) GetApproval(ctx context.Context, id uuid.UUID) (AdminApproval, error) {
	row := q.db.QueryRow(ctx, getApproval, id)
	var i AdminApproval
	err := row.Scan(
		&i.ID,
		&i.Action,
		&i.TargetID,
		&i.RequestedBy,
		&i.Reason,
		&i.Status,
		&i.DecidedBy,
		&i.DecidedReason,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertApproval = `-- name: InsertApproval :execrows
INSERT INTO admin_approvals (id, action, target_id, requested_by, reason, status, created_at, expires_at)
VALUES (
  $1, $2, $3, $4, $5, 'pending',
  $6, $7
)
ON CONFLICT (action, target_id) WHERE status = 'pending' DO NOTHING
`

type InsertApprovalParams struct {
	ID          uuid.UUID
	Action      string
	TargetID    uuid.UUID
	RequestedBy uuid.UUID
	Reason      string
	CreatedAt   time.Time
	ExpiresAt   time.Time
}

func (q *Queries) InsertApproval(ctx context.Context, arg InsertApprovalParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertApproval,
		arg.ID,
		arg.Action,
		arg.TargetID,
		arg.RequestedBy,
		arg.Reason,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listApprovals = `-- name: ListApprovals :many
SELECT id, action, target_id, requested_by, reason, status, decided_by, decided_reason, created_at, decided_at,
  expires_at
FROM admin_approvals
WHERE status = $1
  AND ($2::uuid IS NULL OR id < $2::uuid)
ORDER BY id DESC
LIMIT $3::bigint
`

type ListApprovalsParams struct {
	Status   string
	Cursor   pgtype.UUID
	RowLimit int64
}

func (q *Queries) ListApprovals(ctx context.Context, arg ListApprovalsParams) ([]AdminApproval, error) {
	rows, err := q.db.Query(ctx, listApprovals, arg.Status, arg.Cursor, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminApproval
	for rows.Next() {
		var i AdminApproval
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.TargetID,
			&i.RequestedBy,
			&i.Reason,
			&i.Status,
			&i.DecidedBy,
			&i.DecidedReason,
			&i.CreatedAt,
			&i.DecidedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
