// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dead_letters.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countLiveDeadLetters = `-- name: CountLiveDeadLetters :many
SELECT consumer, count(*)::bigint AS live
FROM dead_letters
WHERE status IN ('open', 'redriven')
GROUP BY consumer
`

type CountLiveDeadLettersRow struct {
	Consumer string
	Live     int64
}

func (q *Queries) CountLiveDeadLetters(ctx context.Context) ([]CountLiveDeadLettersRow, error) {
	rows, err := q.db.Query(ctx, countLiveDeadLetters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountLiveDeadLettersRow
	for rows.Next() {
		var i CountLiveDeadLettersRow
		if err := rows.Scan(&i.Consumer, &i.Live); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deadLetterSeen = `-- name: DeadLetterSeen :one
SELECT EXISTS (SELECT 1 FROM dead_letters WHERE stream_seq = $1)
`

func (q *Queries) DeadLetterSeen(ctx context.Context, streamSeq int64) (bool, error) {
	row := q.db.QueryRow(ctx, deadLetterSeen, streamSeq)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getDeadLetter = `-- name: GetDeadLetter :one
SELECT id, stream_seq, occurrences, status, letter FROM dead_letters WHERE id = $1
`

type GetDeadLetterRow struct {
	ID          uuid.UUID
	StreamSeq   int64
	Occurrences int32
	Status      string
	Letter      []byte
}

func (q *Queries) GetDeadLetter(ctx context.Context, id uuid.UUID) (GetDeadLetterRow, error) {
	row := q.db.QueryRow(ctx, getDeadLetter, id)
	var i GetDeadLetterRow
	err := row.Scan(
		&i.ID,
		&i.StreamSeq,
		&i.Occurrences,
		&i.Status,
		&i.Letter,
	)
	return i, err
}

const listDeadLetters = `-- name: ListDeadLetters :many
SELECT id, stream_seq, consumer, handler, subject, event_id, code, error, occurrences, status, first_seen_at,
  last_seen_at, redriven_at, resolved_at, resolved_by, resolve_reason
FROM dead_letters
WHERE status = $1::text
  AND ($2::text IS NULL OR consumer = $2::text)
  AND ($3::uuid IS NULL OR id < $3::uuid)
ORDER BY id DESC
LIMIT $4::bigint
`

type ListDeadLettersParams struct {
	Status   string
	Consumer pgtype.Text
	Cursor   pgtype.UUID
	RowLimit int64
}

type ListDeadLettersRow struct {
	ID            uuid.UUID
	StreamSeq     int64
	Consumer      string
	Handler       string
	Subject       string
	EventID       pgtype.UUID
	Code          string
	Error         string
	Occurrences   int32
	Status        string
	FirstSeenAt   time.Time
	LastSeenAt    time.Time
	RedrivenAt    pgtype.Timestamptz
	ResolvedAt    pgtype.Timestamptz
	ResolvedBy    pgtype.UUID
	ResolveReason pgtype.Text
}

func (q *Queries) ListDeadLetters(ctx context.Context, arg ListDeadLettersParams) ([]ListDeadLettersRow, error) {
	rows, err := q.db.Query(ctx, listDeadLetters,
		arg.Status,
		arg.Consumer,
		arg.Cursor,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeadLettersRow
	for rows.Next() {
		var i ListDeadLettersRow
		if err := rows.Scan(
			&i.ID,
			&i.StreamSeq,
			&i.Consumer,
			&i.Handler,
			&i.Subject,
			&i.EventID,
			&i.Code,
			&i.Error,
			&i.Occurrences,
			&i.Status,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.RedrivenAt,
			&i.ResolvedAt,
			&i.ResolvedBy,
			&i.ResolveReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDiscarded = `-- name: MarkDiscarded :execrows
UPDATE dead_letters
SET status = 'discarded', resolved_at = $1::timestamptz, resolved_by = $2::uuid,
  resolve_reason = $3::text
WHERE id = $4 AND status IN ('open', 'redriven')
`

type MarkDiscardedParams struct {
	ResolvedAt time.Time
	AdminID    uuid.UUID
	Reason     string
	ID         uuid.UUID
}

func (q *Queries) MarkDiscarded(ctx context.Context, arg MarkDiscardedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDiscarded,
		arg.ResolvedAt,
		arg.AdminID,
		arg.Reason,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markRedriven = `-- name: MarkRedriven :execrows
UPDATE dead_letters
SET status = 'redriven', redriven_at = $1::timestamptz, resolved_by = $2::uuid,
  resolve_reason = $3::text
WHERE id = $4 AND status IN ('open', 'redriven')
`

type MarkRedrivenParams struct {
	RedrivenAt time.Time
	AdminID    uuid.UUID
	Reason     string
	ID         uuid.UUID
}

func (q *Queries) MarkRedriven(ctx context.Context, arg MarkRedrivenParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRedriven,
		arg.RedrivenAt,
		arg.AdminID,
		arg.Reason,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolveDeadLetter = `-- name: ResolveDeadLetter :execrows
UPDATE dead_letters
SET status = 'resolved', resolved_at = $1::timestamptz
WHERE consumer = $2 AND event_id = $3::uuid AND status IN ('open', 'redriven')
`

type ResolveDeadLetterParams struct {
	ResolvedAt time.Time
	Consumer   string
	EventID    uuid.UUID
}

func (q *Queries) ResolveDeadLetter(ctx context.Context, arg ResolveDeadLetterParams) (int64, error) {
	result, err := q.db.Exec(ctx, resolveDeadLetter, arg.ResolvedAt, arg.Consumer, arg.EventID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertDeadLetter = `-- name: UpsertDeadLetter :one
INSERT INTO dead_letters (
  id, stream_seq, consumer, handler, subject, event_id, code, error, letter, occurrences, status,
  first_seen_at, last_seen_at
)
VALUES (
  $1, $2, $3, $4, $5,
  NULLIF($6::text, '')::uuid, $7, $8, $9, 1, 'open',
  $10, $10
)
ON CONFLICT (consumer, event_id) WHERE event_id IS NOT NULL AND status IN ('open', 'redriven') DO UPDATE SET
  stream_seq = EXCLUDED.stream_seq,
  occurrences = dead_letters.occurrences + 1,
  last_seen_at = EXCLUDED.last_seen_at,
  code = EXCLUDED.code,
  error = EXCLUDED.error,
  letter = EXCLUDED.letter,
  status = 'open'
RETURNING id, occurrences, status
`

type UpsertDeadLetterParams struct {
	ID        uuid.UUID
	StreamSeq int64
	Consumer  string
	Handler   string
	Subject   string
	EventID   string
	Code      string
	Error     string
	Letter    []byte
	SeenAt    time.Time
}

type UpsertDeadLetterRow struct {
	ID          uuid.UUID
	Occurrences int32
	Status      string
}

func (q *Queries) UpsertDeadLetter(ctx context.Context, arg UpsertDeadLetterParams) (UpsertDeadLetterRow, error) {
	row := q.db.QueryRow(ctx, upsertDeadLetter,
		arg.ID,
		arg.StreamSeq,
		arg.Consumer,
		arg.Handler,
		arg.Subject,
		arg.EventID,
		arg.Code,
		arg.Error,
		arg.Letter,
		arg.SeenAt,
	)
	var i UpsertDeadLetterRow
	err := row.Scan(&i.ID, &i.Occurrences, &i.Status)
	return i, err
}
